// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: storage_iot.proto

package storage_iot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Thing represents an IoT thing/device.
type Thing struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ThingName        string                 `protobuf:"bytes,1,opt,name=thing_name,json=thingName,proto3" json:"thing_name,omitempty"`
	ThingArn         string                 `protobuf:"bytes,2,opt,name=thing_arn,json=thingArn,proto3" json:"thing_arn,omitempty"`
	ThingId          string                 `protobuf:"bytes,3,opt,name=thing_id,json=thingId,proto3" json:"thing_id,omitempty"`
	ThingTypeName    string                 `protobuf:"bytes,4,opt,name=thing_type_name,json=thingTypeName,proto3" json:"thing_type_name,omitempty"`
	AttributeNames   []string               `protobuf:"bytes,5,rep,name=attribute_names,json=attributeNames,proto3" json:"attribute_names,omitempty"`
	Attributes       map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version          int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreationDate     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Thing) Reset() {
	*x = Thing{}
	mi := &file_storage_iot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thing) ProtoMessage() {}

func (x *Thing) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thing.ProtoReflect.Descriptor instead.
func (*Thing) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{0}
}

func (x *Thing) GetThingName() string {
	if x != nil {
		return x.ThingName
	}
	return ""
}

func (x *Thing) GetThingArn() string {
	if x != nil {
		return x.ThingArn
	}
	return ""
}

func (x *Thing) GetThingId() string {
	if x != nil {
		return x.ThingId
	}
	return ""
}

func (x *Thing) GetThingTypeName() string {
	if x != nil {
		return x.ThingTypeName
	}
	return ""
}

func (x *Thing) GetAttributeNames() []string {
	if x != nil {
		return x.AttributeNames
	}
	return nil
}

func (x *Thing) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Thing) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Thing) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Thing) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

// ThingType represents an IoT thing type.
type ThingType struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ThingTypeName       string                 `protobuf:"bytes,1,opt,name=thing_type_name,json=thingTypeName,proto3" json:"thing_type_name,omitempty"`
	ThingTypeArn        string                 `protobuf:"bytes,2,opt,name=thing_type_arn,json=thingTypeArn,proto3" json:"thing_type_arn,omitempty"`
	ThingTypeId         string                 `protobuf:"bytes,3,opt,name=thing_type_id,json=thingTypeId,proto3" json:"thing_type_id,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ThingTypeProperties []*ThingTypeProperty   `protobuf:"bytes,5,rep,name=thing_type_properties,json=thingTypeProperties,proto3" json:"thing_type_properties,omitempty"`
	Tags                map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version             int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreationDate        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ThingType) Reset() {
	*x = ThingType{}
	mi := &file_storage_iot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingType) ProtoMessage() {}

func (x *ThingType) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThingType.ProtoReflect.Descriptor instead.
func (*ThingType) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{1}
}

func (x *ThingType) GetThingTypeName() string {
	if x != nil {
		return x.ThingTypeName
	}
	return ""
}

func (x *ThingType) GetThingTypeArn() string {
	if x != nil {
		return x.ThingTypeArn
	}
	return ""
}

func (x *ThingType) GetThingTypeId() string {
	if x != nil {
		return x.ThingTypeId
	}
	return ""
}

func (x *ThingType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ThingType) GetThingTypeProperties() []*ThingTypeProperty {
	if x != nil {
		return x.ThingTypeProperties
	}
	return nil
}

func (x *ThingType) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ThingType) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ThingType) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *ThingType) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

// ThingTypeProperty represents a thing type property definition.
type ThingTypeProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	FieldName     string                 `protobuf:"bytes,5,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThingTypeProperty) Reset() {
	*x = ThingTypeProperty{}
	mi := &file_storage_iot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingTypeProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingTypeProperty) ProtoMessage() {}

func (x *ThingTypeProperty) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThingTypeProperty.ProtoReflect.Descriptor instead.
func (*ThingTypeProperty) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{2}
}

func (x *ThingTypeProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ThingTypeProperty) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ThingTypeProperty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ThingTypeProperty) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ThingTypeProperty) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

// ThingGroup represents a group of IoT things.
type ThingGroup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupName        string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupArn         string                 `protobuf:"bytes,2,opt,name=group_arn,json=groupArn,proto3" json:"group_arn,omitempty"`
	GroupId          string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ParentGroupName  string                 `protobuf:"bytes,4,opt,name=parent_group_name,json=parentGroupName,proto3" json:"parent_group_name,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Attributes       map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags             map[string]string      `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreationDate     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	Version          int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ThingGroup) Reset() {
	*x = ThingGroup{}
	mi := &file_storage_iot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThingGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThingGroup) ProtoMessage() {}

func (x *ThingGroup) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThingGroup.ProtoReflect.Descriptor instead.
func (*ThingGroup) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{3}
}

func (x *ThingGroup) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ThingGroup) GetGroupArn() string {
	if x != nil {
		return x.GroupArn
	}
	return ""
}

func (x *ThingGroup) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ThingGroup) GetParentGroupName() string {
	if x != nil {
		return x.ParentGroupName
	}
	return ""
}

func (x *ThingGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ThingGroup) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ThingGroup) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ThingGroup) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *ThingGroup) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

func (x *ThingGroup) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// BillingGroup represents a billing group for IoT things.
type BillingGroup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupName        string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupArn         string                 `protobuf:"bytes,2,opt,name=group_arn,json=groupArn,proto3" json:"group_arn,omitempty"`
	GroupId          string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Attributes       map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags             map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreationDate     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BillingGroup) Reset() {
	*x = BillingGroup{}
	mi := &file_storage_iot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingGroup) ProtoMessage() {}

func (x *BillingGroup) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingGroup.ProtoReflect.Descriptor instead.
func (*BillingGroup) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{4}
}

func (x *BillingGroup) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *BillingGroup) GetGroupArn() string {
	if x != nil {
		return x.GroupArn
	}
	return ""
}

func (x *BillingGroup) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *BillingGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BillingGroup) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *BillingGroup) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BillingGroup) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *BillingGroup) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

// Certificate represents an IoT device certificate.
type Certificate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CertificateId       string                 `protobuf:"bytes,1,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	CertificateArn      string                 `protobuf:"bytes,2,opt,name=certificate_arn,json=certificateArn,proto3" json:"certificate_arn,omitempty"`
	CertificatePem      string                 `protobuf:"bytes,3,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	CertificateMode     string                 `protobuf:"bytes,4,opt,name=certificate_mode,json=certificateMode,proto3" json:"certificate_mode,omitempty"`
	CreationDate        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	Status              string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CaCertificateId     string                 `protobuf:"bytes,8,opt,name=ca_certificate_id,json=caCertificateId,proto3" json:"ca_certificate_id,omitempty"`
	PublicKey           []byte                 `protobuf:"bytes,9,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	TransferDate        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=transfer_date,json=transferDate,proto3" json:"transfer_date,omitempty"`
	TransferToAccountId string                 `protobuf:"bytes,11,opt,name=transfer_to_account_id,json=transferToAccountId,proto3" json:"transfer_to_account_id,omitempty"`
	AutoActive          bool                   `protobuf:"varint,12,opt,name=auto_active,json=autoActive,proto3" json:"auto_active,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_storage_iot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{5}
}

func (x *Certificate) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *Certificate) GetCertificateArn() string {
	if x != nil {
		return x.CertificateArn
	}
	return ""
}

func (x *Certificate) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *Certificate) GetCertificateMode() string {
	if x != nil {
		return x.CertificateMode
	}
	return ""
}

func (x *Certificate) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Certificate) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

func (x *Certificate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Certificate) GetCaCertificateId() string {
	if x != nil {
		return x.CaCertificateId
	}
	return ""
}

func (x *Certificate) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Certificate) GetTransferDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TransferDate
	}
	return nil
}

func (x *Certificate) GetTransferToAccountId() string {
	if x != nil {
		return x.TransferToAccountId
	}
	return ""
}

func (x *Certificate) GetAutoActive() bool {
	if x != nil {
		return x.AutoActive
	}
	return false
}

// Policy represents an IoT policy document.
type Policy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PolicyName       string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyArn        string                 `protobuf:"bytes,2,opt,name=policy_arn,json=policyArn,proto3" json:"policy_arn,omitempty"`
	PolicyDocument   string                 `protobuf:"bytes,3,opt,name=policy_document,json=policyDocument,proto3" json:"policy_document,omitempty"`
	CreationDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	Version          int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_storage_iot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{6}
}

func (x *Policy) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *Policy) GetPolicyArn() string {
	if x != nil {
		return x.PolicyArn
	}
	return ""
}

func (x *Policy) GetPolicyDocument() string {
	if x != nil {
		return x.PolicyDocument
	}
	return ""
}

func (x *Policy) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Policy) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

func (x *Policy) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// TopicRule represents an IoT rules engine topic rule.
type TopicRule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RuleName         string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Arn              string                 `protobuf:"bytes,2,opt,name=arn,proto3" json:"arn,omitempty"`
	TopicPattern     string                 `protobuf:"bytes,3,opt,name=topic_pattern,json=topicPattern,proto3" json:"topic_pattern,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RuleDisabled     bool                   `protobuf:"varint,5,opt,name=rule_disabled,json=ruleDisabled,proto3" json:"rule_disabled,omitempty"`
	Sql              string                 `protobuf:"bytes,6,opt,name=sql,proto3" json:"sql,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AwsIotSqlVersion string                 `protobuf:"bytes,8,opt,name=aws_iot_sql_version,json=awsIotSqlVersion,proto3" json:"aws_iot_sql_version,omitempty"`
	Actions          *structpb.Struct       `protobuf:"bytes,9,opt,name=actions,proto3" json:"actions,omitempty"`
	ErrorAction      *structpb.Struct       `protobuf:"bytes,10,opt,name=error_action,json=errorAction,proto3" json:"error_action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TopicRule) Reset() {
	*x = TopicRule{}
	mi := &file_storage_iot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicRule) ProtoMessage() {}

func (x *TopicRule) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicRule.ProtoReflect.Descriptor instead.
func (*TopicRule) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{7}
}

func (x *TopicRule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *TopicRule) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

func (x *TopicRule) GetTopicPattern() string {
	if x != nil {
		return x.TopicPattern
	}
	return ""
}

func (x *TopicRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TopicRule) GetRuleDisabled() bool {
	if x != nil {
		return x.RuleDisabled
	}
	return false
}

func (x *TopicRule) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *TopicRule) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TopicRule) GetAwsIotSqlVersion() string {
	if x != nil {
		return x.AwsIotSqlVersion
	}
	return ""
}

func (x *TopicRule) GetActions() *structpb.Struct {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *TopicRule) GetErrorAction() *structpb.Struct {
	if x != nil {
		return x.ErrorAction
	}
	return nil
}

// Job represents an IoT job.
type Job struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobArn             string                 `protobuf:"bytes,1,opt,name=job_arn,json=jobArn,proto3" json:"job_arn,omitempty"`
	JobId              string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version            int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Force              bool                   `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	JobTemplateArn     string                 `protobuf:"bytes,9,opt,name=job_template_arn,json=jobTemplateArn,proto3" json:"job_template_arn,omitempty"`
	Status             string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	TargetSelection    string                 `protobuf:"bytes,11,opt,name=target_selection,json=targetSelection,proto3" json:"target_selection,omitempty"`
	JobProcessDetails  int64                  `protobuf:"varint,12,opt,name=job_process_details,json=jobProcessDetails,proto3" json:"job_process_details,omitempty"`
	ScheduledJobLaunch *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=scheduled_job_launch,json=scheduledJobLaunch,proto3" json:"scheduled_job_launch,omitempty"`
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ForceCanceledAt    *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=force_canceled_at,json=forceCanceledAt,proto3" json:"force_canceled_at,omitempty"`
	Tags               map[string]string      `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_storage_iot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{8}
}

func (x *Job) GetJobArn() string {
	if x != nil {
		return x.JobArn
	}
	return ""
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Job) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

func (x *Job) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Job) GetJobTemplateArn() string {
	if x != nil {
		return x.JobTemplateArn
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetTargetSelection() string {
	if x != nil {
		return x.TargetSelection
	}
	return ""
}

func (x *Job) GetJobProcessDetails() int64 {
	if x != nil {
		return x.JobProcessDetails
	}
	return 0
}

func (x *Job) GetScheduledJobLaunch() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledJobLaunch
	}
	return nil
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetForceCanceledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ForceCanceledAt
	}
	return nil
}

func (x *Job) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// JobExecution represents the execution of a job on a thing.
type JobExecution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ThingArn        string                 `protobuf:"bytes,2,opt,name=thing_arn,json=thingArn,proto3" json:"thing_arn,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Version         int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	ExecutionNumber int64                  `protobuf:"varint,5,opt,name=execution_number,json=executionNumber,proto3" json:"execution_number,omitempty"`
	StartedAt       int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	QueuedAt        int64                  `protobuf:"varint,7,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	LastUpdatedAt   int64                  `protobuf:"varint,8,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	CompletedAt     int64                  `protobuf:"varint,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	StatusDetails   *structpb.Struct       `protobuf:"bytes,10,opt,name=status_details,json=statusDetails,proto3" json:"status_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobExecution) Reset() {
	*x = JobExecution{}
	mi := &file_storage_iot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecution) ProtoMessage() {}

func (x *JobExecution) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecution.ProtoReflect.Descriptor instead.
func (*JobExecution) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{9}
}

func (x *JobExecution) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobExecution) GetThingArn() string {
	if x != nil {
		return x.ThingArn
	}
	return ""
}

func (x *JobExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobExecution) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *JobExecution) GetExecutionNumber() int64 {
	if x != nil {
		return x.ExecutionNumber
	}
	return 0
}

func (x *JobExecution) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *JobExecution) GetQueuedAt() int64 {
	if x != nil {
		return x.QueuedAt
	}
	return 0
}

func (x *JobExecution) GetLastUpdatedAt() int64 {
	if x != nil {
		return x.LastUpdatedAt
	}
	return 0
}

func (x *JobExecution) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *JobExecution) GetStatusDetails() *structpb.Struct {
	if x != nil {
		return x.StatusDetails
	}
	return nil
}

// ShadowDocument represents a device shadow document.
type ShadowDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThingName     string                 `protobuf:"bytes,1,opt,name=thing_name,json=thingName,proto3" json:"thing_name,omitempty"`
	Version       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	VersionNumber int64                  `protobuf:"varint,3,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowDocument) Reset() {
	*x = ShadowDocument{}
	mi := &file_storage_iot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowDocument) ProtoMessage() {}

func (x *ShadowDocument) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowDocument.ProtoReflect.Descriptor instead.
func (*ShadowDocument) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{10}
}

func (x *ShadowDocument) GetThingName() string {
	if x != nil {
		return x.ThingName
	}
	return ""
}

func (x *ShadowDocument) GetVersion() *timestamppb.Timestamp {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ShadowDocument) GetVersionNumber() int64 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *ShadowDocument) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ShadowDocument) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ShadowDocument) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// Authorizer represents a custom authorizer for MQTT connections.
type Authorizer struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AuthorizerName        string                 `protobuf:"bytes,1,opt,name=authorizer_name,json=authorizerName,proto3" json:"authorizer_name,omitempty"`
	AuthorizerArn         string                 `protobuf:"bytes,2,opt,name=authorizer_arn,json=authorizerArn,proto3" json:"authorizer_arn,omitempty"`
	AuthorizerFunctionArn string                 `protobuf:"bytes,3,opt,name=authorizer_function_arn,json=authorizerFunctionArn,proto3" json:"authorizer_function_arn,omitempty"`
	TokenKeyName          string                 `protobuf:"bytes,4,opt,name=token_key_name,json=tokenKeyName,proto3" json:"token_key_name,omitempty"`
	TokenSignature        string                 `protobuf:"bytes,5,opt,name=token_signature,json=tokenSignature,proto3" json:"token_signature,omitempty"`
	Status                bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreationDate          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	EnableCachingForHttp  bool                   `protobuf:"varint,9,opt,name=enable_caching_for_http,json=enableCachingForHttp,proto3" json:"enable_caching_for_http,omitempty"`
	CachingDisabled       int64                  `protobuf:"varint,10,opt,name=caching_disabled,json=cachingDisabled,proto3" json:"caching_disabled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Authorizer) Reset() {
	*x = Authorizer{}
	mi := &file_storage_iot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorizer) ProtoMessage() {}

func (x *Authorizer) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorizer.ProtoReflect.Descriptor instead.
func (*Authorizer) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{11}
}

func (x *Authorizer) GetAuthorizerName() string {
	if x != nil {
		return x.AuthorizerName
	}
	return ""
}

func (x *Authorizer) GetAuthorizerArn() string {
	if x != nil {
		return x.AuthorizerArn
	}
	return ""
}

func (x *Authorizer) GetAuthorizerFunctionArn() string {
	if x != nil {
		return x.AuthorizerFunctionArn
	}
	return ""
}

func (x *Authorizer) GetTokenKeyName() string {
	if x != nil {
		return x.TokenKeyName
	}
	return ""
}

func (x *Authorizer) GetTokenSignature() string {
	if x != nil {
		return x.TokenSignature
	}
	return ""
}

func (x *Authorizer) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Authorizer) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Authorizer) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

func (x *Authorizer) GetEnableCachingForHttp() bool {
	if x != nil {
		return x.EnableCachingForHttp
	}
	return false
}

func (x *Authorizer) GetCachingDisabled() int64 {
	if x != nil {
		return x.CachingDisabled
	}
	return 0
}

// RoleAlias represents an IoT role alias for IAM credential mapping.
type RoleAlias struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RoleAlias                 string                 `protobuf:"bytes,1,opt,name=role_alias,json=roleAlias,proto3" json:"role_alias,omitempty"`
	RoleAliasArn              string                 `protobuf:"bytes,2,opt,name=role_alias_arn,json=roleAliasArn,proto3" json:"role_alias_arn,omitempty"`
	RoleArn                   string                 `protobuf:"bytes,3,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	CredentialDurationSeconds string                 `protobuf:"bytes,4,opt,name=credential_duration_seconds,json=credentialDurationSeconds,proto3" json:"credential_duration_seconds,omitempty"`
	Owner                     string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	CreationDate              *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RoleAlias) Reset() {
	*x = RoleAlias{}
	mi := &file_storage_iot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlias) ProtoMessage() {}

func (x *RoleAlias) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlias.ProtoReflect.Descriptor instead.
func (*RoleAlias) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{12}
}

func (x *RoleAlias) GetRoleAlias() string {
	if x != nil {
		return x.RoleAlias
	}
	return ""
}

func (x *RoleAlias) GetRoleAliasArn() string {
	if x != nil {
		return x.RoleAliasArn
	}
	return ""
}

func (x *RoleAlias) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *RoleAlias) GetCredentialDurationSeconds() string {
	if x != nil {
		return x.CredentialDurationSeconds
	}
	return ""
}

func (x *RoleAlias) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RoleAlias) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *RoleAlias) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

// ProvisioningTemplate represents a fleet provisioning template.
type ProvisioningTemplate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TemplateName        string                 `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateArn         string                 `protobuf:"bytes,2,opt,name=template_arn,json=templateArn,proto3" json:"template_arn,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled             bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PreProvisioningHook *structpb.Struct       `protobuf:"bytes,5,opt,name=pre_provisioning_hook,json=preProvisioningHook,proto3" json:"pre_provisioning_hook,omitempty"`
	ProvisioningRoleArn string                 `protobuf:"bytes,6,opt,name=provisioning_role_arn,json=provisioningRoleArn,proto3" json:"provisioning_role_arn,omitempty"`
	TemplateBody        *structpb.Struct       `protobuf:"bytes,7,opt,name=template_body,json=templateBody,proto3" json:"template_body,omitempty"`
	Tags                map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreationDate        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProvisioningTemplate) Reset() {
	*x = ProvisioningTemplate{}
	mi := &file_storage_iot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningTemplate) ProtoMessage() {}

func (x *ProvisioningTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningTemplate.ProtoReflect.Descriptor instead.
func (*ProvisioningTemplate) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{13}
}

func (x *ProvisioningTemplate) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *ProvisioningTemplate) GetTemplateArn() string {
	if x != nil {
		return x.TemplateArn
	}
	return ""
}

func (x *ProvisioningTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProvisioningTemplate) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ProvisioningTemplate) GetPreProvisioningHook() *structpb.Struct {
	if x != nil {
		return x.PreProvisioningHook
	}
	return nil
}

func (x *ProvisioningTemplate) GetProvisioningRoleArn() string {
	if x != nil {
		return x.ProvisioningRoleArn
	}
	return ""
}

func (x *ProvisioningTemplate) GetTemplateBody() *structpb.Struct {
	if x != nil {
		return x.TemplateBody
	}
	return nil
}

func (x *ProvisioningTemplate) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProvisioningTemplate) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *ProvisioningTemplate) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

// DetectorModel represents an IoT Events detector model definition.
type DetectorModel struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DetectorModelName        string                 `protobuf:"bytes,1,opt,name=detector_model_name,json=detectorModelName,proto3" json:"detector_model_name,omitempty"`
	DetectorModelArn         string                 `protobuf:"bytes,2,opt,name=detector_model_arn,json=detectorModelArn,proto3" json:"detector_model_arn,omitempty"`
	DetectorModelDescription string                 `protobuf:"bytes,3,opt,name=detector_model_description,json=detectorModelDescription,proto3" json:"detector_model_description,omitempty"`
	RoleArn                  string                 `protobuf:"bytes,4,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	DetectorModelDefinition  *structpb.Struct       `protobuf:"bytes,5,opt,name=detector_model_definition,json=detectorModelDefinition,proto3" json:"detector_model_definition,omitempty"`
	Tags                     map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreationDate             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	Status                   string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Key                      string                 `protobuf:"bytes,10,opt,name=key,proto3" json:"key,omitempty"`
	EvaluationMethod         string                 `protobuf:"bytes,11,opt,name=evaluation_method,json=evaluationMethod,proto3" json:"evaluation_method,omitempty"`
	DetectorModelVersion     string                 `protobuf:"bytes,12,opt,name=detector_model_version,json=detectorModelVersion,proto3" json:"detector_model_version,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DetectorModel) Reset() {
	*x = DetectorModel{}
	mi := &file_storage_iot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorModel) ProtoMessage() {}

func (x *DetectorModel) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorModel.ProtoReflect.Descriptor instead.
func (*DetectorModel) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{14}
}

func (x *DetectorModel) GetDetectorModelName() string {
	if x != nil {
		return x.DetectorModelName
	}
	return ""
}

func (x *DetectorModel) GetDetectorModelArn() string {
	if x != nil {
		return x.DetectorModelArn
	}
	return ""
}

func (x *DetectorModel) GetDetectorModelDescription() string {
	if x != nil {
		return x.DetectorModelDescription
	}
	return ""
}

func (x *DetectorModel) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *DetectorModel) GetDetectorModelDefinition() *structpb.Struct {
	if x != nil {
		return x.DetectorModelDefinition
	}
	return nil
}

func (x *DetectorModel) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DetectorModel) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *DetectorModel) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

func (x *DetectorModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DetectorModel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DetectorModel) GetEvaluationMethod() string {
	if x != nil {
		return x.EvaluationMethod
	}
	return ""
}

func (x *DetectorModel) GetDetectorModelVersion() string {
	if x != nil {
		return x.DetectorModelVersion
	}
	return ""
}

// Input represents an IoT Events input definition.
type Input struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputName        string                 `protobuf:"bytes,1,opt,name=input_name,json=inputName,proto3" json:"input_name,omitempty"`
	InputArn         string                 `protobuf:"bytes,2,opt,name=input_arn,json=inputArn,proto3" json:"input_arn,omitempty"`
	InputDescription string                 `protobuf:"bytes,3,opt,name=input_description,json=inputDescription,proto3" json:"input_description,omitempty"`
	InputDefinition  *structpb.Struct       `protobuf:"bytes,4,opt,name=input_definition,json=inputDefinition,proto3" json:"input_definition,omitempty"`
	Tags             map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreationDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_storage_iot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_storage_iot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_storage_iot_proto_rawDescGZIP(), []int{15}
}

func (x *Input) GetInputName() string {
	if x != nil {
		return x.InputName
	}
	return ""
}

func (x *Input) GetInputArn() string {
	if x != nil {
		return x.InputArn
	}
	return ""
}

func (x *Input) GetInputDescription() string {
	if x != nil {
		return x.InputDescription
	}
	return ""
}

func (x *Input) GetInputDefinition() *structpb.Struct {
	if x != nil {
		return x.InputDefinition
	}
	return nil
}

func (x *Input) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Input) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Input) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

func (x *Input) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_storage_iot_proto protoreflect.FileDescriptor

const file_storage_iot_proto_rawDesc = "" +
	"\n" +
	"\x11storage_iot.proto\x12\vstorage.iot\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd7\x03\n" +
	"\x05Thing\x12\x1d\n" +
	"\n" +
	"thing_name\x18\x01 \x01(\tR\tthingName\x12\x1b\n" +
	"\tthing_arn\x18\x02 \x01(\tR\bthingArn\x12\x19\n" +
	"\bthing_id\x18\x03 \x01(\tR\athingId\x12&\n" +
	"\x0fthing_type_name\x18\x04 \x01(\tR\rthingTypeName\x12'\n" +
	"\x0fattribute_names\x18\x05 \x03(\tR\x0eattributeNames\x12B\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2\".storage.iot.Thing.AttributesEntryR\n" +
	"attributes\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12?\n" +
	"\rcreation_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x04\n" +
	"\tThingType\x12&\n" +
	"\x0fthing_type_name\x18\x01 \x01(\tR\rthingTypeName\x12$\n" +
	"\x0ething_type_arn\x18\x02 \x01(\tR\fthingTypeArn\x12\"\n" +
	"\rthing_type_id\x18\x03 \x01(\tR\vthingTypeId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12R\n" +
	"\x15thing_type_properties\x18\x05 \x03(\v2\x1e.storage.iot.ThingTypePropertyR\x13thingTypeProperties\x124\n" +
	"\x04tags\x18\x06 \x03(\v2 .storage.iot.ThingType.TagsEntryR\x04tags\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12?\n" +
	"\rcreation_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x11ThingTypeProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1d\n" +
	"\n" +
	"field_name\x18\x05 \x01(\tR\tfieldName\"\xce\x04\n" +
	"\n" +
	"ThingGroup\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x1b\n" +
	"\tgroup_arn\x18\x02 \x01(\tR\bgroupArn\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12*\n" +
	"\x11parent_group_name\x18\x04 \x01(\tR\x0fparentGroupName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12G\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2'.storage.iot.ThingGroup.AttributesEntryR\n" +
	"attributes\x125\n" +
	"\x04tags\x18\a \x03(\v2!.storage.iot.ThingGroup.TagsEntryR\x04tags\x12?\n" +
	"\rcreation_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x04\n" +
	"\fBillingGroup\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x1b\n" +
	"\tgroup_arn\x18\x02 \x01(\tR\bgroupArn\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12I\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2).storage.iot.BillingGroup.AttributesEntryR\n" +
	"attributes\x127\n" +
	"\x04tags\x18\x06 \x03(\v2#.storage.iot.BillingGroup.TagsEntryR\x04tags\x12?\n" +
	"\rcreation_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x04\n" +
	"\vCertificate\x12%\n" +
	"\x0ecertificate_id\x18\x01 \x01(\tR\rcertificateId\x12'\n" +
	"\x0fcertificate_arn\x18\x02 \x01(\tR\x0ecertificateArn\x12'\n" +
	"\x0fcertificate_pem\x18\x03 \x01(\tR\x0ecertificatePem\x12)\n" +
	"\x10certificate_mode\x18\x04 \x01(\tR\x0fcertificateMode\x12?\n" +
	"\rcreation_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12*\n" +
	"\x11ca_certificate_id\x18\b \x01(\tR\x0fcaCertificateId\x12\x1d\n" +
	"\n" +
	"public_key\x18\t \x01(\fR\tpublicKey\x12?\n" +
	"\rtransfer_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ftransferDate\x123\n" +
	"\x16transfer_to_account_id\x18\v \x01(\tR\x13transferToAccountId\x12\x1f\n" +
	"\vauto_active\x18\f \x01(\bR\n" +
	"autoActive\"\x96\x02\n" +
	"\x06Policy\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12\x1d\n" +
	"\n" +
	"policy_arn\x18\x02 \x01(\tR\tpolicyArn\x12'\n" +
	"\x0fpolicy_document\x18\x03 \x01(\tR\x0epolicyDocument\x12?\n" +
	"\rcreation_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\"\xf5\x02\n" +
	"\tTopicRule\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12\x10\n" +
	"\x03arn\x18\x02 \x01(\tR\x03arn\x12#\n" +
	"\rtopic_pattern\x18\x03 \x01(\tR\ftopicPattern\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rrule_disabled\x18\x05 \x01(\bR\fruleDisabled\x12\x10\n" +
	"\x03sql\x18\x06 \x01(\tR\x03sql\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12-\n" +
	"\x13aws_iot_sql_version\x18\b \x01(\tR\x10awsIotSqlVersion\x121\n" +
	"\aactions\x18\t \x01(\v2\x17.google.protobuf.StructR\aactions\x12:\n" +
	"\ferror_action\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\verrorAction\"\x80\x06\n" +
	"\x03Job\x12\x17\n" +
	"\ajob_arn\x18\x01 \x01(\tR\x06jobArn\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x14\n" +
	"\x05force\x18\x05 \x01(\bR\x05force\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\x0flast_updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\tR\vcompletedAt\x12(\n" +
	"\x10job_template_arn\x18\t \x01(\tR\x0ejobTemplateArn\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12)\n" +
	"\x10target_selection\x18\v \x01(\tR\x0ftargetSelection\x12.\n" +
	"\x13job_process_details\x18\f \x01(\x03R\x11jobProcessDetails\x12L\n" +
	"\x14scheduled_job_launch\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x12scheduledJobLaunch\x129\n" +
	"\n" +
	"started_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12F\n" +
	"\x11force_canceled_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x0fforceCanceledAt\x12.\n" +
	"\x04tags\x18\x10 \x03(\v2\x1a.storage.iot.Job.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x02\n" +
	"\fJobExecution\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tthing_arn\x18\x02 \x01(\tR\bthingArn\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12)\n" +
	"\x10execution_number\x18\x05 \x01(\x03R\x0fexecutionNumber\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x1b\n" +
	"\tqueued_at\x18\a \x01(\x03R\bqueuedAt\x12&\n" +
	"\x0flast_updated_at\x18\b \x01(\x03R\rlastUpdatedAt\x12!\n" +
	"\fcompleted_at\x18\t \x01(\x03R\vcompletedAt\x12>\n" +
	"\x0estatus_details\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\rstatusDetails\"\xf8\x01\n" +
	"\x0eShadowDocument\x12\x1d\n" +
	"\n" +
	"thing_name\x18\x01 \x01(\tR\tthingName\x124\n" +
	"\aversion\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aversion\x12%\n" +
	"\x0eversion_number\x18\x03 \x01(\x03R\rversionNumber\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"\xe8\x03\n" +
	"\n" +
	"Authorizer\x12'\n" +
	"\x0fauthorizer_name\x18\x01 \x01(\tR\x0eauthorizerName\x12%\n" +
	"\x0eauthorizer_arn\x18\x02 \x01(\tR\rauthorizerArn\x126\n" +
	"\x17authorizer_function_arn\x18\x03 \x01(\tR\x15authorizerFunctionArn\x12$\n" +
	"\x0etoken_key_name\x18\x04 \x01(\tR\ftokenKeyName\x12'\n" +
	"\x0ftoken_signature\x18\x05 \x01(\tR\x0etokenSignature\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12?\n" +
	"\rcreation_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x125\n" +
	"\x17enable_caching_for_http\x18\t \x01(\bR\x14enableCachingForHttp\x12)\n" +
	"\x10caching_disabled\x18\n" +
	" \x01(\x03R\x0fcachingDisabled\"\xcc\x02\n" +
	"\tRoleAlias\x12\x1d\n" +
	"\n" +
	"role_alias\x18\x01 \x01(\tR\troleAlias\x12$\n" +
	"\x0erole_alias_arn\x18\x02 \x01(\tR\froleAliasArn\x12\x19\n" +
	"\brole_arn\x18\x03 \x01(\tR\aroleArn\x12>\n" +
	"\x1bcredential_duration_seconds\x18\x04 \x01(\tR\x19credentialDurationSeconds\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12?\n" +
	"\rcreation_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\"\xde\x04\n" +
	"\x14ProvisioningTemplate\x12#\n" +
	"\rtemplate_name\x18\x01 \x01(\tR\ftemplateName\x12!\n" +
	"\ftemplate_arn\x18\x02 \x01(\tR\vtemplateArn\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12K\n" +
	"\x15pre_provisioning_hook\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x13preProvisioningHook\x122\n" +
	"\x15provisioning_role_arn\x18\x06 \x01(\tR\x13provisioningRoleArn\x12<\n" +
	"\rtemplate_body\x18\a \x01(\v2\x17.google.protobuf.StructR\ftemplateBody\x12?\n" +
	"\x04tags\x18\b \x03(\v2+.storage.iot.ProvisioningTemplate.TagsEntryR\x04tags\x12?\n" +
	"\rcreation_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x05\n" +
	"\rDetectorModel\x12.\n" +
	"\x13detector_model_name\x18\x01 \x01(\tR\x11detectorModelName\x12,\n" +
	"\x12detector_model_arn\x18\x02 \x01(\tR\x10detectorModelArn\x12<\n" +
	"\x1adetector_model_description\x18\x03 \x01(\tR\x18detectorModelDescription\x12\x19\n" +
	"\brole_arn\x18\x04 \x01(\tR\aroleArn\x12S\n" +
	"\x19detector_model_definition\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x17detectorModelDefinition\x128\n" +
	"\x04tags\x18\x06 \x03(\v2$.storage.iot.DetectorModel.TagsEntryR\x04tags\x12?\n" +
	"\rcreation_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x10\n" +
	"\x03key\x18\n" +
	" \x01(\tR\x03key\x12+\n" +
	"\x11evaluation_method\x18\v \x01(\tR\x10evaluationMethod\x124\n" +
	"\x16detector_model_version\x18\f \x01(\tR\x14detectorModelVersion\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x03\n" +
	"\x05Input\x12\x1d\n" +
	"\n" +
	"input_name\x18\x01 \x01(\tR\tinputName\x12\x1b\n" +
	"\tinput_arn\x18\x02 \x01(\tR\binputArn\x12+\n" +
	"\x11input_description\x18\x03 \x01(\tR\x10inputDescription\x12B\n" +
	"\x10input_definition\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0finputDefinition\x120\n" +
	"\x04tags\x18\x05 \x03(\v2\x1c.storage.iot.Input.TagsEntryR\x04tags\x12?\n" +
	"\rcreation_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12H\n" +
	"\x12last_modified_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z,vorpalstacks/internal/pb/storage/storage_iotb\x06proto3"

var (
	file_storage_iot_proto_rawDescOnce sync.Once
	file_storage_iot_proto_rawDescData []byte
)

func file_storage_iot_proto_rawDescGZIP() []byte {
	file_storage_iot_proto_rawDescOnce.Do(func() {
		file_storage_iot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_iot_proto_rawDesc), len(file_storage_iot_proto_rawDesc)))
	})
	return file_storage_iot_proto_rawDescData
}

var file_storage_iot_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_storage_iot_proto_goTypes = []any{
	(*Thing)(nil),                 // 0: storage.iot.Thing
	(*ThingType)(nil),             // 1: storage.iot.ThingType
	(*ThingTypeProperty)(nil),     // 2: storage.iot.ThingTypeProperty
	(*ThingGroup)(nil),            // 3: storage.iot.ThingGroup
	(*BillingGroup)(nil),          // 4: storage.iot.BillingGroup
	(*Certificate)(nil),           // 5: storage.iot.Certificate
	(*Policy)(nil),                // 6: storage.iot.Policy
	(*TopicRule)(nil),             // 7: storage.iot.TopicRule
	(*Job)(nil),                   // 8: storage.iot.Job
	(*JobExecution)(nil),          // 9: storage.iot.JobExecution
	(*ShadowDocument)(nil),        // 10: storage.iot.ShadowDocument
	(*Authorizer)(nil),            // 11: storage.iot.Authorizer
	(*RoleAlias)(nil),             // 12: storage.iot.RoleAlias
	(*ProvisioningTemplate)(nil),  // 13: storage.iot.ProvisioningTemplate
	(*DetectorModel)(nil),         // 14: storage.iot.DetectorModel
	(*Input)(nil),                 // 15: storage.iot.Input
	nil,                           // 16: storage.iot.Thing.AttributesEntry
	nil,                           // 17: storage.iot.ThingType.TagsEntry
	nil,                           // 18: storage.iot.ThingGroup.AttributesEntry
	nil,                           // 19: storage.iot.ThingGroup.TagsEntry
	nil,                           // 20: storage.iot.BillingGroup.AttributesEntry
	nil,                           // 21: storage.iot.BillingGroup.TagsEntry
	nil,                           // 22: storage.iot.Job.TagsEntry
	nil,                           // 23: storage.iot.ProvisioningTemplate.TagsEntry
	nil,                           // 24: storage.iot.DetectorModel.TagsEntry
	nil,                           // 25: storage.iot.Input.TagsEntry
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 27: google.protobuf.Struct
}
var file_storage_iot_proto_depIdxs = []int32{
	16, // 0: storage.iot.Thing.attributes:type_name -> storage.iot.Thing.AttributesEntry
	26, // 1: storage.iot.Thing.creation_date:type_name -> google.protobuf.Timestamp
	26, // 2: storage.iot.Thing.last_modified_date:type_name -> google.protobuf.Timestamp
	2,  // 3: storage.iot.ThingType.thing_type_properties:type_name -> storage.iot.ThingTypeProperty
	17, // 4: storage.iot.ThingType.tags:type_name -> storage.iot.ThingType.TagsEntry
	26, // 5: storage.iot.ThingType.creation_date:type_name -> google.protobuf.Timestamp
	26, // 6: storage.iot.ThingType.last_modified_date:type_name -> google.protobuf.Timestamp
	18, // 7: storage.iot.ThingGroup.attributes:type_name -> storage.iot.ThingGroup.AttributesEntry
	19, // 8: storage.iot.ThingGroup.tags:type_name -> storage.iot.ThingGroup.TagsEntry
	26, // 9: storage.iot.ThingGroup.creation_date:type_name -> google.protobuf.Timestamp
	26, // 10: storage.iot.ThingGroup.last_modified_date:type_name -> google.protobuf.Timestamp
	20, // 11: storage.iot.BillingGroup.attributes:type_name -> storage.iot.BillingGroup.AttributesEntry
	21, // 12: storage.iot.BillingGroup.tags:type_name -> storage.iot.BillingGroup.TagsEntry
	26, // 13: storage.iot.BillingGroup.creation_date:type_name -> google.protobuf.Timestamp
	26, // 14: storage.iot.BillingGroup.last_modified_date:type_name -> google.protobuf.Timestamp
	26, // 15: storage.iot.Certificate.creation_date:type_name -> google.protobuf.Timestamp
	26, // 16: storage.iot.Certificate.last_modified_date:type_name -> google.protobuf.Timestamp
	26, // 17: storage.iot.Certificate.transfer_date:type_name -> google.protobuf.Timestamp
	26, // 18: storage.iot.Policy.creation_date:type_name -> google.protobuf.Timestamp
	26, // 19: storage.iot.Policy.last_modified_date:type_name -> google.protobuf.Timestamp
	27, // 20: storage.iot.TopicRule.actions:type_name -> google.protobuf.Struct
	27, // 21: storage.iot.TopicRule.error_action:type_name -> google.protobuf.Struct
	26, // 22: storage.iot.Job.created_at:type_name -> google.protobuf.Timestamp
	26, // 23: storage.iot.Job.last_updated_at:type_name -> google.protobuf.Timestamp
	26, // 24: storage.iot.Job.scheduled_job_launch:type_name -> google.protobuf.Timestamp
	26, // 25: storage.iot.Job.started_at:type_name -> google.protobuf.Timestamp
	26, // 26: storage.iot.Job.force_canceled_at:type_name -> google.protobuf.Timestamp
	22, // 27: storage.iot.Job.tags:type_name -> storage.iot.Job.TagsEntry
	27, // 28: storage.iot.JobExecution.status_details:type_name -> google.protobuf.Struct
	26, // 29: storage.iot.ShadowDocument.version:type_name -> google.protobuf.Timestamp
	26, // 30: storage.iot.ShadowDocument.timestamp:type_name -> google.protobuf.Timestamp
	26, // 31: storage.iot.Authorizer.creation_date:type_name -> google.protobuf.Timestamp
	26, // 32: storage.iot.Authorizer.last_modified_date:type_name -> google.protobuf.Timestamp
	26, // 33: storage.iot.RoleAlias.creation_date:type_name -> google.protobuf.Timestamp
	26, // 34: storage.iot.RoleAlias.last_modified_date:type_name -> google.protobuf.Timestamp
	27, // 35: storage.iot.ProvisioningTemplate.pre_provisioning_hook:type_name -> google.protobuf.Struct
	27, // 36: storage.iot.ProvisioningTemplate.template_body:type_name -> google.protobuf.Struct
	23, // 37: storage.iot.ProvisioningTemplate.tags:type_name -> storage.iot.ProvisioningTemplate.TagsEntry
	26, // 38: storage.iot.ProvisioningTemplate.creation_date:type_name -> google.protobuf.Timestamp
	26, // 39: storage.iot.ProvisioningTemplate.last_modified_date:type_name -> google.protobuf.Timestamp
	27, // 40: storage.iot.DetectorModel.detector_model_definition:type_name -> google.protobuf.Struct
	24, // 41: storage.iot.DetectorModel.tags:type_name -> storage.iot.DetectorModel.TagsEntry
	26, // 42: storage.iot.DetectorModel.creation_date:type_name -> google.protobuf.Timestamp
	26, // 43: storage.iot.DetectorModel.last_modified_date:type_name -> google.protobuf.Timestamp
	27, // 44: storage.iot.Input.input_definition:type_name -> google.protobuf.Struct
	25, // 45: storage.iot.Input.tags:type_name -> storage.iot.Input.TagsEntry
	26, // 46: storage.iot.Input.creation_date:type_name -> google.protobuf.Timestamp
	26, // 47: storage.iot.Input.last_modified_date:type_name -> google.protobuf.Timestamp
	48, // [48:48] is the sub-list for method output_type
	48, // [48:48] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_storage_iot_proto_init() }
func file_storage_iot_proto_init() {
	if File_storage_iot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_iot_proto_rawDesc), len(file_storage_iot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_iot_proto_goTypes,
		DependencyIndexes: file_storage_iot_proto_depIdxs,
		MessageInfos:      file_storage_iot_proto_msgTypes,
	}.Build()
	File_storage_iot_proto = out.File
	file_storage_iot_proto_goTypes = nil
	file_storage_iot_proto_depIdxs = nil
}
