package sfn

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"time"

	sfnstore "vorpalstacks/internal/store/aws/sfn"
)

func (e *Executor) executePass(ctx context.Context, execCtx *ExecutionContext, state *sfnstore.PassState) (string, string, error) {
	isJSONata := IsJSONataState(state, execCtx.QueryLanguage)

	if isJSONata {
		return e.executePassJSONata(ctx, execCtx, state)
	}

	processedInput, ipErr := e.applyInputPath(execCtx, execCtx.Input, state.GetInputPath())
	if ipErr != nil {
		return "", "", ipErr
	}
	applied, err := e.applyParameters(execCtx, "", processedInput, state.Parameters)
	if err != nil {
		return "", "", err
	}
	processedInput = applied

	eventId := execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:             execCtx.Execution.ExecutionArn,
		EventId:                  eventId,
		PreviousEventId:          eventId - 1,
		Type:                     "PassStateEntered",
		Timestamp:                time.Now().UTC(),
		StateEnteredEventDetails: stateEnteredDetails(execCtx, processedInput),
	})

	output := processedInput
	if state.Result != nil {
		resultJSON, err := json.Marshal(state.Result)
		if err != nil {
			return "", "", fmt.Errorf("failed to marshal result: %w", err)
		}
		output = string(resultJSON)
	}

	// JSONPath Pass Assign evaluates against the result ("For Pass, $
	// refers to the result, whether generated by the Result field or the
	// InputPath/Parameters fields"); new values become visible in the next
	// state.
	if len(state.Assign) > 0 {
		var root interface{}
		if err := json.Unmarshal([]byte(output), &root); err != nil {
			root = nil
		}
		evaluated, err := e.evaluateJSONPathAssign(execCtx, state.Assign, root)
		if err != nil {
			return "", "", newJSONPathEvalError("Assign", err)
		}
		execCtx.PendingAssign = evaluated
	}

	selected, selErr := e.applyResultSelector(execCtx, output, state.GetResultSelector(), "")
	if selErr != nil {
		return "", "", selErr
	}
	output = selected
	folded, rpErr := e.applyResultPath(processedInput, output, state.ResultPath)
	if rpErr != nil {
		return "", "", rpErr
	}
	output = folded
	selectedOut, opErr := e.applyOutputPath(execCtx, output, state.GetOutputPath())
	if opErr != nil {
		return "", "", opErr
	}
	output = selectedOut

	eventId = execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:            execCtx.Execution.ExecutionArn,
		EventId:                 eventId,
		PreviousEventId:         eventId - 1,
		Type:                    "PassStateExited",
		Timestamp:               time.Now().UTC(),
		StateExitedEventDetails: stateExitedDetails(execCtx, output),
	})

	return output, state.Next, nil
}

func (e *Executor) executePassJSONata(ctx context.Context, execCtx *ExecutionContext, state *sfnstore.PassState) (string, string, error) {
	var inputData interface{}
	if execCtx.Input != "" {
		if err := json.Unmarshal([]byte(execCtx.Input), &inputData); err != nil {
			return "", "", e.newQueryEvalError(ctx, execCtx, "Input", "failed to parse input JSON")
		}
	}

	jsonataOutput, jerr := jsonataOutputOf(state)
	if jerr != nil {
		return "", "", e.newQueryEvalError(ctx, execCtx, "Output", jerr.Error())
	}

	statesVar := e.buildStatesVarWithContext(execCtx, inputData, nil, nil)

	eventId := execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:             execCtx.Execution.ExecutionArn,
		EventId:                  eventId,
		PreviousEventId:          eventId - 1,
		Type:                     "PassStateEntered",
		Timestamp:                time.Now().UTC(),
		StateEnteredEventDetails: stateEnteredDetails(execCtx, execCtx.Input),
	})

	if len(state.Assign) > 0 {
		evaluated, err := evaluateAssign(ctx, state.Assign, statesVar, execCtx.VariableScope)
		if err != nil {
			return "", "", e.newQueryEvalError(ctx, execCtx, "Assign", err.Error())
		}
		execCtx.PendingAssign = evaluated
	}

	output := inputData
	if jsonataOutput != nil {
		resolved, err := e.applyJSONataOutput(ctx, jsonataOutput, statesVar, execCtx.VariableScope)
		if err != nil {
			return "", "", e.newQueryEvalError(ctx, execCtx, "Output", err.Error())
		}
		output = resolved
	} else if state.Result != nil {
		output = state.Result
	}

	outputJSON, err := json.Marshal(output)
	if err != nil {
		return "", "", fmt.Errorf("failed to marshal output: %w", err)
	}
	outputStr := string(outputJSON)

	eventId = execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:            execCtx.Execution.ExecutionArn,
		EventId:                 eventId,
		PreviousEventId:         eventId - 1,
		Type:                    "PassStateExited",
		Timestamp:               time.Now().UTC(),
		StateExitedEventDetails: stateExitedDetails(execCtx, outputStr),
	})

	return outputStr, state.Next, nil
}

// waitWithCancel blocks until the wait deadline (Timestamp) or duration
// (Seconds) elapses, returning ctx's error if the execution is cancelled
// first. A zero waitUntil defers to waitSeconds; a deadline already past
// returns immediately.
func waitWithCancel(ctx context.Context, waitUntil time.Time, waitSeconds int32) error {
	if !waitUntil.IsZero() {
		now := time.Now().UTC()
		if waitUntil.After(now) {
			timer := time.NewTimer(waitUntil.Sub(now))
			select {
			case <-timer.C:
			case <-ctx.Done():
				timer.Stop()
				return ctx.Err()
			}
		}
		return nil
	}
	if waitSeconds > 0 {
		timer := time.NewTimer(time.Duration(waitSeconds) * time.Second)
		select {
		case <-timer.C:
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		}
	}
	return nil
}

func (e *Executor) executeWait(ctx context.Context, execCtx *ExecutionContext, state *sfnstore.WaitState) (string, string, error) {
	isJSONata := IsJSONataState(state, execCtx.QueryLanguage)

	if isJSONata {
		return e.executeWaitJSONata(ctx, execCtx, state)
	}

	processedInput, ipErr := e.applyInputPath(execCtx, execCtx.Input, state.GetInputPath())
	if ipErr != nil {
		return "", "", ipErr
	}

	var waitSeconds int32 = state.GetSeconds()
	var waitUntil time.Time

	if state.Timestamp != "" {
		targetTime, ok := parseASLTimestamp(state.Timestamp)
		if !ok {
			return "", "", newJSONPathEvalError("Timestamp", fmt.Errorf("value %q does not conform to the RFC3339 profile of ISO 8601", state.Timestamp))
		}
		waitUntil = targetTime
	}

	if state.TimestampPath != "" {
		var inputData map[string]interface{}
		if err := json.Unmarshal([]byte(processedInput), &inputData); err != nil {
			return "", "", newJSONPathEvalError("TimestampPath", fmt.Errorf("input is not a JSON object"))
		}
		val, ok := getJSONPathValueRaw(inputData, state.TimestampPath)
		if !ok {
			return "", "", newJSONPathEvalError("TimestampPath", fmt.Errorf("path %s does not select a value", state.TimestampPath))
		}
		tsStr, ok := val.(string)
		if !ok {
			return "", "", newJSONPathEvalError("TimestampPath", fmt.Errorf("path %s selected a non-string value", state.TimestampPath))
		}
		targetTime, ok := parseASLTimestamp(tsStr)
		if !ok {
			return "", "", newJSONPathEvalError("TimestampPath", fmt.Errorf("value %q does not conform to the RFC3339 profile of ISO 8601", tsStr))
		}
		waitUntil = targetTime
	}

	if state.SecondsPath != "" {
		var inputData map[string]interface{}
		if err := json.Unmarshal([]byte(processedInput), &inputData); err != nil {
			return "", "", newJSONPathEvalError("SecondsPath", fmt.Errorf("input is not a JSON object"))
		}
		val, ok := getJSONPathValueRaw(inputData, state.SecondsPath)
		if !ok {
			return "", "", newJSONPathEvalError("SecondsPath", fmt.Errorf("path %s does not select a value", state.SecondsPath))
		}
		numVal, ok := toFloat64(val)
		if !ok || numVal != math.Trunc(numVal) || numVal < 0 || numVal > sfnstore.MaxWaitSeconds {
			return "", "", newJSONPathEvalError("SecondsPath", fmt.Errorf("path %s selected %v, not an integer value from 0 to %d", state.SecondsPath, val, sfnstore.MaxWaitSeconds))
		}
		waitSeconds = int32(numVal)
	}

	// A negative literal reaches here only through definitions persisted
	// before creation-time validation existed.
	if waitSeconds < 0 {
		return "", "", newJSONPathEvalError("Seconds", fmt.Errorf("value %d is not an integer value from 0 to %d", waitSeconds, sfnstore.MaxWaitSeconds))
	}
	// AWS truncates wait timestamps to whole seconds.
	waitUntil = waitUntil.Truncate(time.Second)

	eventId := execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:             execCtx.Execution.ExecutionArn,
		EventId:                  eventId,
		PreviousEventId:          eventId - 1,
		Type:                     "WaitStateEntered",
		Timestamp:                time.Now().UTC(),
		StateEnteredEventDetails: stateEnteredDetails(execCtx, processedInput),
	})

	if err := waitWithCancel(ctx, waitUntil, waitSeconds); err != nil {
		return "", "", err
	}

	// JSONPath Wait Assign evaluates against the effective input ("For
	// Choice and Wait, $ refers to the effective input").
	if len(state.Assign) > 0 {
		var root interface{}
		if err := json.Unmarshal([]byte(processedInput), &root); err != nil {
			root = nil
		}
		evaluated, err := e.evaluateJSONPathAssign(execCtx, state.Assign, root)
		if err != nil {
			return "", "", newJSONPathEvalError("Assign", err)
		}
		execCtx.PendingAssign = evaluated
	}

	output, opErr := e.applyOutputPath(execCtx, processedInput, state.GetOutputPath())
	if opErr != nil {
		return "", "", opErr
	}

	eventId = execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:            execCtx.Execution.ExecutionArn,
		EventId:                 eventId,
		PreviousEventId:         eventId - 1,
		Type:                    "WaitStateExited",
		Timestamp:               time.Now().UTC(),
		StateExitedEventDetails: stateExitedDetails(execCtx, output),
	})

	return output, state.Next, nil
}

// waitTimestampStringFromResult normalises a JSONata expression result
// to a timestamp string: a direct string is used as-is, any other value
// must marshal and decode as a JSON string.
func waitTimestampStringFromResult(result interface{}) (string, bool) {
	if s, ok := result.(string); ok {
		return s, true
	}
	b, err := json.Marshal(result)
	if err != nil {
		return "", false
	}
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return "", false
	}
	return s, true
}

func (e *Executor) executeWaitJSONata(ctx context.Context, execCtx *ExecutionContext, state *sfnstore.WaitState) (string, string, error) {
	var inputData interface{}
	if execCtx.Input != "" {
		if err := json.Unmarshal([]byte(execCtx.Input), &inputData); err != nil {
			return "", "", e.newQueryEvalError(ctx, execCtx, "Input", "failed to parse input JSON")
		}
	}

	statesVar := e.buildStatesVarWithContext(execCtx, inputData, nil, nil)

	eventId := execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:             execCtx.Execution.ExecutionArn,
		EventId:                  eventId,
		PreviousEventId:          eventId - 1,
		Type:                     "WaitStateEntered",
		Timestamp:                time.Now().UTC(),
		StateEnteredEventDetails: stateEnteredDetails(execCtx, execCtx.Input),
	})

	if len(state.Assign) > 0 {
		evaluated, err := evaluateAssign(ctx, state.Assign, statesVar, execCtx.VariableScope)
		if err != nil {
			return "", "", e.newQueryEvalError(ctx, execCtx, "Assign", err.Error())
		}
		execCtx.PendingAssign = evaluated
	}

	// A JSONata Wait specifies exactly one of Seconds or Timestamp. A
	// Timestamp expression must evaluate to a string conforming to the
	// same RFC3339 profile as the JSONPath literal; both wait values are
	// held to the integer range 0..MaxWaitSeconds at run time.
	var waitSeconds int32
	var waitUntil time.Time

	if state.Timestamp != "" {
		value := state.Timestamp
		fromExpression := IsExpression(value)
		if fromExpression {
			vars := buildVarsMap(statesVar, execCtx.VariableScope)
			result, err := EvaluateJSONata(ctx, UnwrapExpression(value), nil, vars)
			if err != nil {
				return "", "", e.newQueryEvalError(ctx, execCtx, "Timestamp", err.Error())
			}
			s, ok := waitTimestampStringFromResult(result)
			if !ok {
				return "", "", e.newQueryEvalError(ctx, execCtx, "Timestamp", fmt.Sprintf("expression result %v is not a timestamp string", result))
			}
			value = s
		}
		targetTime, ok := parseASLTimestamp(value)
		if !ok {
			reason := fmt.Sprintf("value %q does not conform to the RFC3339 profile of ISO 8601", value)
			if fromExpression {
				return "", "", e.newQueryEvalError(ctx, execCtx, "Timestamp", reason)
			}
			return "", "", newRuntimeValueError("Timestamp", reason)
		}
		// AWS truncates wait timestamps to whole seconds.
		waitUntil = targetTime.Truncate(time.Second)
	} else if state.Seconds != nil {
		secondsLiteral, isExpression := state.Seconds.(string)
		if isExpression && IsExpression(secondsLiteral) {
			vars := buildVarsMap(statesVar, execCtx.VariableScope)
			result, err := EvaluateJSONata(ctx, UnwrapExpression(secondsLiteral), nil, vars)
			if err != nil {
				return "", "", e.newQueryEvalError(ctx, execCtx, "Seconds", err.Error())
			}
			f, ok := toFloat64(result)
			if !ok || f != math.Trunc(f) || f < 0 || f > sfnstore.MaxWaitSeconds {
				return "", "", e.newQueryEvalError(ctx, execCtx, "Seconds", fmt.Sprintf("expression result %v is not an integer value from 0 to %d", result, sfnstore.MaxWaitSeconds))
			}
			waitSeconds = int32(f)
		} else {
			f, ok := toFloat64(state.Seconds)
			if !ok || f != math.Trunc(f) || f < 0 || f > sfnstore.MaxWaitSeconds {
				return "", "", newRuntimeValueError("Seconds", fmt.Sprintf("value %v is not an integer value from 0 to %d", state.Seconds, sfnstore.MaxWaitSeconds))
			}
			waitSeconds = int32(f)
		}
	}

	if err := waitWithCancel(ctx, waitUntil, waitSeconds); err != nil {
		return "", "", err
	}

	outputJSON, err := json.Marshal(inputData)
	if err != nil {
		outputJSON = []byte("{}")
	}

	eventId = execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:            execCtx.Execution.ExecutionArn,
		EventId:                 eventId,
		PreviousEventId:         eventId - 1,
		Type:                    "WaitStateExited",
		Timestamp:               time.Now().UTC(),
		StateExitedEventDetails: stateExitedDetails(execCtx, string(outputJSON)),
	})

	return string(outputJSON), state.Next, nil
}

func (e *Executor) executeFail(ctx context.Context, execCtx *ExecutionContext, state *sfnstore.FailState) error {
	errorName := state.GetError()
	cause := state.GetCause()

	var inputData interface{}
	ensureInput := func() bool {
		if inputData != nil || execCtx.Input == "" {
			return true
		}
		return json.Unmarshal([]byte(execCtx.Input), &inputData) == nil
	}

	if IsJSONataState(state, execCtx.QueryLanguage) {
		// In JSONata states the Error and Cause members may carry
		// expressions; both resolve against the state input.
		if s, ok := state.Error.(string); ok && IsExpression(s) && ensureInput() {
			statesVar := e.buildStatesVarWithContext(execCtx, inputData, nil, nil)
			vars := buildVarsMap(statesVar, execCtx.VariableScope)
			if result, err := EvaluateJSONata(ctx, UnwrapExpression(s), nil, vars); err == nil {
				errorName = stringifyFailValue(result)
			} else {
				return e.newQueryEvalError(ctx, execCtx, "Error", err.Error())
			}
		}
		if s, ok := state.Cause.(string); ok && IsExpression(s) && ensureInput() {
			statesVar := e.buildStatesVarWithContext(execCtx, inputData, nil, nil)
			vars := buildVarsMap(statesVar, execCtx.VariableScope)
			if result, err := EvaluateJSONata(ctx, UnwrapExpression(s), nil, vars); err == nil {
				cause = stringifyFailValue(result)
			} else {
				return e.newQueryEvalError(ctx, execCtx, "Cause", err.Error())
			}
		}
	} else {
		// ErrorPath and CausePath are reference paths selecting string
		// values from the state input, or intrinsic invocations that
		// return a string; each excludes its literal form.
		var failInput map[string]interface{}
		resolveDynamic := func(spec, field string) (string, bool, *ExecutionError) {
			if looksLikeIntrinsic(spec) {
				if failInput == nil && execCtx.Input != "" {
					var data interface{}
					if err := json.Unmarshal([]byte(execCtx.Input), &data); err == nil {
						if m, ok := data.(map[string]interface{}); ok {
							failInput = m
						}
					}
				}
				resolved, err := e.evaluateIntrinsic(execCtx, "", spec, failInput, 1)
				if err != nil {
					return "", false, newJSONPathEvalError(field, err)
				}
				s, ok := resolved.(string)
				if !ok {
					return "", false, newJSONPathEvalError(field, fmt.Errorf("intrinsic function did not return a string"))
				}
				return s, true, nil
			}
			resolved, ok := resolveFailPathString(execCtx.Input, spec)
			return resolved, ok, nil
		}
		if state.ErrorPath != "" {
			resolved, ok, evalErr := resolveDynamic(state.ErrorPath, "ErrorPath")
			if evalErr != nil {
				return evalErr
			}
			if ok {
				errorName = resolved
			}
		}
		if state.CausePath != "" {
			resolved, ok, evalErr := resolveDynamic(state.CausePath, "CausePath")
			if evalErr != nil {
				return evalErr
			}
			if ok {
				cause = resolved
			}
		}
	}

	eventId := execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:             execCtx.Execution.ExecutionArn,
		EventId:                  eventId,
		PreviousEventId:          eventId - 1,
		Type:                     "FailStateEntered",
		Timestamp:                time.Now().UTC(),
		StateEnteredEventDetails: stateEnteredDetails(execCtx, execCtx.Input),
	})

	return &ExecutionError{ErrorCode: errorName, Cause: cause}
}

// stringifyFailValue renders a resolved Fail Error or Cause value: strings
// pass through, anything else renders as its JSON text.
func stringifyFailValue(value interface{}) string {
	if s, ok := value.(string); ok {
		return s
	}
	b, _ := json.Marshal(value)
	return string(b)
}

// resolveFailPathString resolves a Fail ErrorPath or CausePath reference
// path against the state input; the documented contract requires the
// selected field to hold a string.
func resolveFailPathString(input, path string) (string, bool) {
	if input == "" {
		return "", false
	}
	var data interface{}
	if err := json.Unmarshal([]byte(input), &data); err != nil {
		return "", false
	}
	inputMap, ok := data.(map[string]interface{})
	if !ok {
		return "", false
	}
	value, err := getJSONPathValue(inputMap, path)
	if err != nil {
		return "", false
	}
	str, ok := value.(string)
	return str, ok
}

func (e *Executor) executeSucceed(ctx context.Context, execCtx *ExecutionContext, state *sfnstore.SucceedState) (string, string, error) {
	isJSONata := IsJSONataState(state, execCtx.QueryLanguage)

	if isJSONata {
		jsonataOutput, jerr := jsonataOutputOf(state)
		if jerr != nil {
			return "", "", e.newQueryEvalError(ctx, execCtx, "Output", jerr.Error())
		}
		if jsonataOutput != nil {
			var inputData interface{}
			if execCtx.Input != "" {
				if err := json.Unmarshal([]byte(execCtx.Input), &inputData); err != nil {
					return "", "", e.newQueryEvalError(ctx, execCtx, "Input", "failed to parse input JSON")
				}
			}
			statesVar := e.buildStatesVarWithContext(execCtx, inputData, nil, nil)

			eventId := execCtx.nextEventId()
			e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
				ExecutionArn:             execCtx.Execution.ExecutionArn,
				EventId:                  eventId,
				PreviousEventId:          eventId - 1,
				Type:                     "SucceedStateEntered",
				Timestamp:                time.Now().UTC(),
				StateEnteredEventDetails: stateEnteredDetails(execCtx, execCtx.Input),
			})

			resolved, err := e.applyJSONataOutput(ctx, jsonataOutput, statesVar, execCtx.VariableScope)
			if err != nil {
				return "", "", e.newQueryEvalError(ctx, execCtx, "Output", err.Error())
			}
			outputJSON, err := json.Marshal(resolved)
			if err != nil {
				return "", "", fmt.Errorf("failed to marshal output: %w", err)
			}
			eventId = execCtx.nextEventId()
			e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
				ExecutionArn:            execCtx.Execution.ExecutionArn,
				EventId:                 eventId,
				PreviousEventId:         eventId - 1,
				Type:                    "SucceedStateExited",
				Timestamp:               time.Now().UTC(),
				StateExitedEventDetails: stateExitedDetails(execCtx, string(outputJSON)),
			})
			return string(outputJSON), "", nil
		}
	}

	processedInput, ipErr := e.applyInputPath(execCtx, execCtx.Input, state.GetInputPath())
	if ipErr != nil {
		return "", "", ipErr
	}

	eventId := execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:             execCtx.Execution.ExecutionArn,
		EventId:                  eventId,
		PreviousEventId:          eventId - 1,
		Type:                     "SucceedStateEntered",
		Timestamp:                time.Now().UTC(),
		StateEnteredEventDetails: stateEnteredDetails(execCtx, execCtx.Input),
	})

	output, opErr := e.applyOutputPath(execCtx, processedInput, state.GetOutputPath())
	if opErr != nil {
		return "", "", opErr
	}

	eventId = execCtx.nextEventId()
	e.logHistoryEvent(ctx, execCtx.Execution, &sfnstore.ExecutionHistoryEvent{
		ExecutionArn:            execCtx.Execution.ExecutionArn,
		EventId:                 eventId,
		PreviousEventId:         eventId - 1,
		Type:                    "SucceedStateExited",
		Timestamp:               time.Now().UTC(),
		StateExitedEventDetails: stateExitedDetails(execCtx, output),
	})

	return output, "", nil
}
