// Code generated by proto_generator. DO NOT EDIT.
// source: kinesis

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: kinesis.proto

package kinesisconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	common "vorpalstacks/internal/pb/aws/common"
	kinesis "vorpalstacks/internal/pb/aws/kinesis"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// KinesisServiceName is the fully-qualified name of the KinesisService service.
	KinesisServiceName = "kinesis.KinesisService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// KinesisServiceAddTagsToStreamProcedure is the fully-qualified name of the KinesisService's
	// AddTagsToStream RPC.
	KinesisServiceAddTagsToStreamProcedure = "/kinesis.KinesisService/AddTagsToStream"
	// KinesisServiceCreateStreamProcedure is the fully-qualified name of the KinesisService's
	// CreateStream RPC.
	KinesisServiceCreateStreamProcedure = "/kinesis.KinesisService/CreateStream"
	// KinesisServiceDecreaseStreamRetentionPeriodProcedure is the fully-qualified name of the
	// KinesisService's DecreaseStreamRetentionPeriod RPC.
	KinesisServiceDecreaseStreamRetentionPeriodProcedure = "/kinesis.KinesisService/DecreaseStreamRetentionPeriod"
	// KinesisServiceDeleteResourcePolicyProcedure is the fully-qualified name of the KinesisService's
	// DeleteResourcePolicy RPC.
	KinesisServiceDeleteResourcePolicyProcedure = "/kinesis.KinesisService/DeleteResourcePolicy"
	// KinesisServiceDeleteStreamProcedure is the fully-qualified name of the KinesisService's
	// DeleteStream RPC.
	KinesisServiceDeleteStreamProcedure = "/kinesis.KinesisService/DeleteStream"
	// KinesisServiceDeregisterStreamConsumerProcedure is the fully-qualified name of the
	// KinesisService's DeregisterStreamConsumer RPC.
	KinesisServiceDeregisterStreamConsumerProcedure = "/kinesis.KinesisService/DeregisterStreamConsumer"
	// KinesisServiceDescribeAccountSettingsProcedure is the fully-qualified name of the
	// KinesisService's DescribeAccountSettings RPC.
	KinesisServiceDescribeAccountSettingsProcedure = "/kinesis.KinesisService/DescribeAccountSettings"
	// KinesisServiceDescribeLimitsProcedure is the fully-qualified name of the KinesisService's
	// DescribeLimits RPC.
	KinesisServiceDescribeLimitsProcedure = "/kinesis.KinesisService/DescribeLimits"
	// KinesisServiceDescribeStreamProcedure is the fully-qualified name of the KinesisService's
	// DescribeStream RPC.
	KinesisServiceDescribeStreamProcedure = "/kinesis.KinesisService/DescribeStream"
	// KinesisServiceDescribeStreamConsumerProcedure is the fully-qualified name of the KinesisService's
	// DescribeStreamConsumer RPC.
	KinesisServiceDescribeStreamConsumerProcedure = "/kinesis.KinesisService/DescribeStreamConsumer"
	// KinesisServiceDescribeStreamSummaryProcedure is the fully-qualified name of the KinesisService's
	// DescribeStreamSummary RPC.
	KinesisServiceDescribeStreamSummaryProcedure = "/kinesis.KinesisService/DescribeStreamSummary"
	// KinesisServiceDisableEnhancedMonitoringProcedure is the fully-qualified name of the
	// KinesisService's DisableEnhancedMonitoring RPC.
	KinesisServiceDisableEnhancedMonitoringProcedure = "/kinesis.KinesisService/DisableEnhancedMonitoring"
	// KinesisServiceEnableEnhancedMonitoringProcedure is the fully-qualified name of the
	// KinesisService's EnableEnhancedMonitoring RPC.
	KinesisServiceEnableEnhancedMonitoringProcedure = "/kinesis.KinesisService/EnableEnhancedMonitoring"
	// KinesisServiceGetRecordsProcedure is the fully-qualified name of the KinesisService's GetRecords
	// RPC.
	KinesisServiceGetRecordsProcedure = "/kinesis.KinesisService/GetRecords"
	// KinesisServiceGetResourcePolicyProcedure is the fully-qualified name of the KinesisService's
	// GetResourcePolicy RPC.
	KinesisServiceGetResourcePolicyProcedure = "/kinesis.KinesisService/GetResourcePolicy"
	// KinesisServiceGetShardIteratorProcedure is the fully-qualified name of the KinesisService's
	// GetShardIterator RPC.
	KinesisServiceGetShardIteratorProcedure = "/kinesis.KinesisService/GetShardIterator"
	// KinesisServiceIncreaseStreamRetentionPeriodProcedure is the fully-qualified name of the
	// KinesisService's IncreaseStreamRetentionPeriod RPC.
	KinesisServiceIncreaseStreamRetentionPeriodProcedure = "/kinesis.KinesisService/IncreaseStreamRetentionPeriod"
	// KinesisServiceListShardsProcedure is the fully-qualified name of the KinesisService's ListShards
	// RPC.
	KinesisServiceListShardsProcedure = "/kinesis.KinesisService/ListShards"
	// KinesisServiceListStreamConsumersProcedure is the fully-qualified name of the KinesisService's
	// ListStreamConsumers RPC.
	KinesisServiceListStreamConsumersProcedure = "/kinesis.KinesisService/ListStreamConsumers"
	// KinesisServiceListStreamsProcedure is the fully-qualified name of the KinesisService's
	// ListStreams RPC.
	KinesisServiceListStreamsProcedure = "/kinesis.KinesisService/ListStreams"
	// KinesisServiceListTagsForResourceProcedure is the fully-qualified name of the KinesisService's
	// ListTagsForResource RPC.
	KinesisServiceListTagsForResourceProcedure = "/kinesis.KinesisService/ListTagsForResource"
	// KinesisServiceListTagsForStreamProcedure is the fully-qualified name of the KinesisService's
	// ListTagsForStream RPC.
	KinesisServiceListTagsForStreamProcedure = "/kinesis.KinesisService/ListTagsForStream"
	// KinesisServiceMergeShardsProcedure is the fully-qualified name of the KinesisService's
	// MergeShards RPC.
	KinesisServiceMergeShardsProcedure = "/kinesis.KinesisService/MergeShards"
	// KinesisServicePutRecordProcedure is the fully-qualified name of the KinesisService's PutRecord
	// RPC.
	KinesisServicePutRecordProcedure = "/kinesis.KinesisService/PutRecord"
	// KinesisServicePutRecordsProcedure is the fully-qualified name of the KinesisService's PutRecords
	// RPC.
	KinesisServicePutRecordsProcedure = "/kinesis.KinesisService/PutRecords"
	// KinesisServicePutResourcePolicyProcedure is the fully-qualified name of the KinesisService's
	// PutResourcePolicy RPC.
	KinesisServicePutResourcePolicyProcedure = "/kinesis.KinesisService/PutResourcePolicy"
	// KinesisServiceRegisterStreamConsumerProcedure is the fully-qualified name of the KinesisService's
	// RegisterStreamConsumer RPC.
	KinesisServiceRegisterStreamConsumerProcedure = "/kinesis.KinesisService/RegisterStreamConsumer"
	// KinesisServiceRemoveTagsFromStreamProcedure is the fully-qualified name of the KinesisService's
	// RemoveTagsFromStream RPC.
	KinesisServiceRemoveTagsFromStreamProcedure = "/kinesis.KinesisService/RemoveTagsFromStream"
	// KinesisServiceSplitShardProcedure is the fully-qualified name of the KinesisService's SplitShard
	// RPC.
	KinesisServiceSplitShardProcedure = "/kinesis.KinesisService/SplitShard"
	// KinesisServiceStartStreamEncryptionProcedure is the fully-qualified name of the KinesisService's
	// StartStreamEncryption RPC.
	KinesisServiceStartStreamEncryptionProcedure = "/kinesis.KinesisService/StartStreamEncryption"
	// KinesisServiceStopStreamEncryptionProcedure is the fully-qualified name of the KinesisService's
	// StopStreamEncryption RPC.
	KinesisServiceStopStreamEncryptionProcedure = "/kinesis.KinesisService/StopStreamEncryption"
	// KinesisServiceSubscribeToShardProcedure is the fully-qualified name of the KinesisService's
	// SubscribeToShard RPC.
	KinesisServiceSubscribeToShardProcedure = "/kinesis.KinesisService/SubscribeToShard"
	// KinesisServiceTagResourceProcedure is the fully-qualified name of the KinesisService's
	// TagResource RPC.
	KinesisServiceTagResourceProcedure = "/kinesis.KinesisService/TagResource"
	// KinesisServiceUntagResourceProcedure is the fully-qualified name of the KinesisService's
	// UntagResource RPC.
	KinesisServiceUntagResourceProcedure = "/kinesis.KinesisService/UntagResource"
	// KinesisServiceUpdateAccountSettingsProcedure is the fully-qualified name of the KinesisService's
	// UpdateAccountSettings RPC.
	KinesisServiceUpdateAccountSettingsProcedure = "/kinesis.KinesisService/UpdateAccountSettings"
	// KinesisServiceUpdateMaxRecordSizeProcedure is the fully-qualified name of the KinesisService's
	// UpdateMaxRecordSize RPC.
	KinesisServiceUpdateMaxRecordSizeProcedure = "/kinesis.KinesisService/UpdateMaxRecordSize"
	// KinesisServiceUpdateShardCountProcedure is the fully-qualified name of the KinesisService's
	// UpdateShardCount RPC.
	KinesisServiceUpdateShardCountProcedure = "/kinesis.KinesisService/UpdateShardCount"
	// KinesisServiceUpdateStreamModeProcedure is the fully-qualified name of the KinesisService's
	// UpdateStreamMode RPC.
	KinesisServiceUpdateStreamModeProcedure = "/kinesis.KinesisService/UpdateStreamMode"
	// KinesisServiceUpdateStreamWarmThroughputProcedure is the fully-qualified name of the
	// KinesisService's UpdateStreamWarmThroughput RPC.
	KinesisServiceUpdateStreamWarmThroughputProcedure = "/kinesis.KinesisService/UpdateStreamWarmThroughput"
)

// KinesisServiceClient is a client for the kinesis.KinesisService service.
type KinesisServiceClient interface {
	// Adds or updates tags for the specified Kinesis data stream. You can assign up to 50 tags to a data stream. When invoking this API, you must use either the StreamARN or the StreamName parameter, or ...
	// HTTP:
	// Protocol: awsJson1_1
	AddTagsToStream(context.Context, *connect.Request[kinesis.AddTagsToStreamInput]) (*connect.Response[common.Empty], error)
	// Creates a Kinesis data stream. A stream captures and transports data records that are continuously emitted from different data sources or producers. Scale-out within a stream is explicitly supporte...
	// HTTP:
	// Protocol: awsJson1_1
	CreateStream(context.Context, *connect.Request[kinesis.CreateStreamInput]) (*connect.Response[common.Empty], error)
	// Decreases the Kinesis data stream's retention period, which is the length of time data records are accessible after they are added to the stream. The minimum value of a stream's retention period is...
	// HTTP:
	// Protocol: awsJson1_1
	DecreaseStreamRetentionPeriod(context.Context, *connect.Request[kinesis.DecreaseStreamRetentionPeriodInput]) (*connect.Response[common.Empty], error)
	// Delete a policy for the specified data stream or consumer. Request patterns can be one of the following: Data stream pattern: arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+ Consumer pattern: ^(arn):aws.*...
	// HTTP:
	// Protocol: awsJson1_1
	DeleteResourcePolicy(context.Context, *connect.Request[kinesis.DeleteResourcePolicyInput]) (*connect.Response[common.Empty], error)
	// Deletes a Kinesis data stream and all its shards and data. You must shut down any applications that are operating on the stream before you delete the stream. If an application attempts to operate o...
	// HTTP:
	// Protocol: awsJson1_1
	DeleteStream(context.Context, *connect.Request[kinesis.DeleteStreamInput]) (*connect.Response[common.Empty], error)
	// To deregister a consumer, provide its ARN. Alternatively, you can provide the ARN of the data stream and the name you gave the consumer when you registered it. You may also provide all three parame...
	// HTTP:
	// Protocol: awsJson1_1
	DeregisterStreamConsumer(context.Context, *connect.Request[kinesis.DeregisterStreamConsumerInput]) (*connect.Response[common.Empty], error)
	// Describes the account-level settings for Amazon Kinesis Data Streams. This operation returns information about the minimum throughput billing commitments and other account-level configurations. Thi...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeAccountSettings(context.Context, *connect.Request[kinesis.DescribeAccountSettingsInput]) (*connect.Response[kinesis.DescribeAccountSettingsOutput], error)
	// Describes the shard limits and usage for the account. If you update your account limits, the old limits might be returned for a few minutes. This operation has a limit of one transaction per second...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeLimits(context.Context, *connect.Request[kinesis.DescribeLimitsInput]) (*connect.Response[kinesis.DescribeLimitsOutput], error)
	// Describes the specified Kinesis data stream. This API has been revised. It's highly recommended that you use the DescribeStreamSummary API to get a summarized description of the specified Kinesis d...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeStream(context.Context, *connect.Request[kinesis.DescribeStreamInput]) (*connect.Response[kinesis.DescribeStreamOutput], error)
	// To get the description of a registered consumer, provide the ARN of the consumer. Alternatively, you can provide the ARN of the data stream and the name you gave the consumer when you registered it...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeStreamConsumer(context.Context, *connect.Request[kinesis.DescribeStreamConsumerInput]) (*connect.Response[kinesis.DescribeStreamConsumerOutput], error)
	// Provides a summarized description of the specified Kinesis data stream without the shard list. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is ...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeStreamSummary(context.Context, *connect.Request[kinesis.DescribeStreamSummaryInput]) (*connect.Response[kinesis.DescribeStreamSummaryOutput], error)
	// Disables enhanced monitoring. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is recommended that you use the StreamARN input parameter when you i...
	// HTTP:
	// Protocol: awsJson1_1
	DisableEnhancedMonitoring(context.Context, *connect.Request[kinesis.DisableEnhancedMonitoringInput]) (*connect.Response[kinesis.EnhancedMonitoringOutput], error)
	// Enables enhanced Kinesis data stream monitoring for shard-level metrics. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is recommended that you u...
	// HTTP:
	// Protocol: awsJson1_1
	EnableEnhancedMonitoring(context.Context, *connect.Request[kinesis.EnableEnhancedMonitoringInput]) (*connect.Response[kinesis.EnhancedMonitoringOutput], error)
	// Gets data records from a Kinesis data stream's shard. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is recommended that you use the StreamARN in...
	// HTTP:
	// Protocol: awsJson1_1
	GetRecords(context.Context, *connect.Request[kinesis.GetRecordsInput]) (*connect.Response[kinesis.GetRecordsOutput], error)
	// Returns a policy attached to the specified data stream or consumer. Request patterns can be one of the following: Data stream pattern: arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+ Consumer pattern: ^(a...
	// HTTP:
	// Protocol: awsJson1_1
	GetResourcePolicy(context.Context, *connect.Request[kinesis.GetResourcePolicyInput]) (*connect.Response[kinesis.GetResourcePolicyOutput], error)
	// Gets an Amazon Kinesis shard iterator. A shard iterator expires 5 minutes after it is returned to the requester. When invoking this API, you must use either the StreamARN or the StreamName paramete...
	// HTTP:
	// Protocol: awsJson1_1
	GetShardIterator(context.Context, *connect.Request[kinesis.GetShardIteratorInput]) (*connect.Response[kinesis.GetShardIteratorOutput], error)
	// Increases the Kinesis data stream's retention period, which is the length of time data records are accessible after they are added to the stream. The maximum value of a stream's retention period is...
	// HTTP:
	// Protocol: awsJson1_1
	IncreaseStreamRetentionPeriod(context.Context, *connect.Request[kinesis.IncreaseStreamRetentionPeriodInput]) (*connect.Response[common.Empty], error)
	// Lists the shards in a stream and provides information about each shard. This operation has a limit of 1000 transactions per second per data stream. When invoking this API, you must use either the S...
	// HTTP:
	// Protocol: awsJson1_1
	ListShards(context.Context, *connect.Request[kinesis.ListShardsInput]) (*connect.Response[kinesis.ListShardsOutput], error)
	// Lists the consumers registered to receive data from a stream using enhanced fan-out, and provides information about each consumer. This operation has a limit of 5 transactions per second per stream.
	// HTTP:
	// Protocol: awsJson1_1
	ListStreamConsumers(context.Context, *connect.Request[kinesis.ListStreamConsumersInput]) (*connect.Response[kinesis.ListStreamConsumersOutput], error)
	// Lists your Kinesis data streams. The number of streams may be too large to return from a single call to ListStreams. You can limit the number of returned streams using the Limit parameter. If you d...
	// HTTP:
	// Protocol: awsJson1_1
	ListStreams(context.Context, *connect.Request[kinesis.ListStreamsInput]) (*connect.Response[kinesis.ListStreamsOutput], error)
	// List all tags added to the specified Kinesis resource. Each tag is a label consisting of a user-defined key and value. Tags can help you manage, identify, organize, search for, and filter resources...
	// HTTP:
	// Protocol: awsJson1_1
	ListTagsForResource(context.Context, *connect.Request[kinesis.ListTagsForResourceInput]) (*connect.Response[kinesis.ListTagsForResourceOutput], error)
	// Lists the tags for the specified Kinesis data stream. This operation has a limit of five transactions per second per account. When invoking this API, you must use either the StreamARN or the Stream...
	// HTTP:
	// Protocol: awsJson1_1
	ListTagsForStream(context.Context, *connect.Request[kinesis.ListTagsForStreamInput]) (*connect.Response[kinesis.ListTagsForStreamOutput], error)
	// Merges two adjacent shards in a Kinesis data stream and combines them into a single shard to reduce the stream's capacity to ingest and transport data. This API is only supported for the data strea...
	// HTTP:
	// Protocol: awsJson1_1
	MergeShards(context.Context, *connect.Request[kinesis.MergeShardsInput]) (*connect.Response[common.Empty], error)
	// Writes a single data record into an Amazon Kinesis data stream. Call PutRecord to send data into the stream for real-time ingestion and subsequent processing, one record at a time. Each shard can s...
	// HTTP:
	// Protocol: awsJson1_1
	PutRecord(context.Context, *connect.Request[kinesis.PutRecordInput]) (*connect.Response[kinesis.PutRecordOutput], error)
	// Writes multiple data records into a Kinesis data stream in a single call (also referred to as a PutRecords request). Use this operation to send data into the stream for data ingestion and processin...
	// HTTP:
	// Protocol: awsJson1_1
	PutRecords(context.Context, *connect.Request[kinesis.PutRecordsInput]) (*connect.Response[kinesis.PutRecordsOutput], error)
	// Attaches a resource-based policy to a data stream or registered consumer. If you are using an identity other than the root user of the Amazon Web Services account that owns the resource, the callin...
	// HTTP:
	// Protocol: awsJson1_1
	PutResourcePolicy(context.Context, *connect.Request[kinesis.PutResourcePolicyInput]) (*connect.Response[common.Empty], error)
	// Registers a consumer with a Kinesis data stream. When you use this operation, the consumer you register can then call SubscribeToShard to receive data from the stream using enhanced fan-out, at a r...
	// HTTP:
	// Protocol: awsJson1_1
	RegisterStreamConsumer(context.Context, *connect.Request[kinesis.RegisterStreamConsumerInput]) (*connect.Response[kinesis.RegisterStreamConsumerOutput], error)
	// Removes tags from the specified Kinesis data stream. Removed tags are deleted and cannot be recovered after this operation successfully completes. When invoking this API, you must use either the St...
	// HTTP:
	// Protocol: awsJson1_1
	RemoveTagsFromStream(context.Context, *connect.Request[kinesis.RemoveTagsFromStreamInput]) (*connect.Response[common.Empty], error)
	// Splits a shard into two new shards in the Kinesis data stream, to increase the stream's capacity to ingest and transport data. SplitShard is called when there is a need to increase the overall capa...
	// HTTP:
	// Protocol: awsJson1_1
	SplitShard(context.Context, *connect.Request[kinesis.SplitShardInput]) (*connect.Response[common.Empty], error)
	// Enables or updates server-side encryption using an Amazon Web Services KMS key for a specified stream. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both...
	// HTTP:
	// Protocol: awsJson1_1
	StartStreamEncryption(context.Context, *connect.Request[kinesis.StartStreamEncryptionInput]) (*connect.Response[common.Empty], error)
	// Disables server-side encryption for a specified stream. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is recommended that you use the StreamARN ...
	// HTTP:
	// Protocol: awsJson1_1
	StopStreamEncryption(context.Context, *connect.Request[kinesis.StopStreamEncryptionInput]) (*connect.Response[common.Empty], error)
	// This operation establishes an HTTP/2 connection between the consumer you specify in the ConsumerARN parameter and the shard you specify in the ShardId parameter. After the connection is successfull...
	// HTTP:
	// Protocol: awsJson1_1
	SubscribeToShard(context.Context, *connect.Request[kinesis.SubscribeToShardInput]) (*connect.Response[kinesis.SubscribeToShardOutput], error)
	// Adds or updates tags for the specified Kinesis resource. Each tag is a label consisting of a user-defined key and value. Tags can help you manage, identify, organize, search for, and filter resourc...
	// HTTP:
	// Protocol: awsJson1_1
	TagResource(context.Context, *connect.Request[kinesis.TagResourceInput]) (*connect.Response[common.Empty], error)
	// Removes tags from the specified Kinesis resource. Removed tags are deleted and can't be recovered after this operation completes successfully.
	// HTTP:
	// Protocol: awsJson1_1
	UntagResource(context.Context, *connect.Request[kinesis.UntagResourceInput]) (*connect.Response[common.Empty], error)
	// Updates the account-level settings for Amazon Kinesis Data Streams. Updating account settings is a synchronous operation. Upon receiving the request, Kinesis Data Streams will return immediately wi...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateAccountSettings(context.Context, *connect.Request[kinesis.UpdateAccountSettingsInput]) (*connect.Response[kinesis.UpdateAccountSettingsOutput], error)
	// This allows you to update the MaxRecordSize of a single record that you can write to, and read from a stream. You can ingest and digest single records up to 10240 KiB.
	// HTTP:
	// Protocol: awsJson1_1
	UpdateMaxRecordSize(context.Context, *connect.Request[kinesis.UpdateMaxRecordSizeInput]) (*connect.Response[common.Empty], error)
	// Updates the shard count of the specified stream to the specified number of shards. This API is only supported for the data streams with the provisioned capacity mode. When invoking this API, you mu...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateShardCount(context.Context, *connect.Request[kinesis.UpdateShardCountInput]) (*connect.Response[kinesis.UpdateShardCountOutput], error)
	// Updates the capacity mode of the data stream. Currently, in Kinesis Data Streams, you can choose between an on-demand capacity mode and a provisioned capacity mode for your data stream. If you'd st...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateStreamMode(context.Context, *connect.Request[kinesis.UpdateStreamModeInput]) (*connect.Response[common.Empty], error)
	// Updates the warm throughput configuration for the specified Amazon Kinesis Data Streams on-demand data stream. This operation allows you to proactively scale your on-demand data stream to a specifi...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateStreamWarmThroughput(context.Context, *connect.Request[kinesis.UpdateStreamWarmThroughputInput]) (*connect.Response[kinesis.UpdateStreamWarmThroughputOutput], error)
}

// NewKinesisServiceClient constructs a client for the kinesis.KinesisService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKinesisServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) KinesisServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	kinesisServiceMethods := kinesis.File_kinesis_proto.Services().ByName("KinesisService").Methods()
	return &kinesisServiceClient{
		addTagsToStream: connect.NewClient[kinesis.AddTagsToStreamInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceAddTagsToStreamProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("AddTagsToStream")),
			connect.WithClientOptions(opts...),
		),
		createStream: connect.NewClient[kinesis.CreateStreamInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceCreateStreamProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("CreateStream")),
			connect.WithClientOptions(opts...),
		),
		decreaseStreamRetentionPeriod: connect.NewClient[kinesis.DecreaseStreamRetentionPeriodInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceDecreaseStreamRetentionPeriodProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DecreaseStreamRetentionPeriod")),
			connect.WithClientOptions(opts...),
		),
		deleteResourcePolicy: connect.NewClient[kinesis.DeleteResourcePolicyInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceDeleteResourcePolicyProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DeleteResourcePolicy")),
			connect.WithClientOptions(opts...),
		),
		deleteStream: connect.NewClient[kinesis.DeleteStreamInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceDeleteStreamProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DeleteStream")),
			connect.WithClientOptions(opts...),
		),
		deregisterStreamConsumer: connect.NewClient[kinesis.DeregisterStreamConsumerInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceDeregisterStreamConsumerProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DeregisterStreamConsumer")),
			connect.WithClientOptions(opts...),
		),
		describeAccountSettings: connect.NewClient[kinesis.DescribeAccountSettingsInput, kinesis.DescribeAccountSettingsOutput](
			httpClient,
			baseURL+KinesisServiceDescribeAccountSettingsProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DescribeAccountSettings")),
			connect.WithClientOptions(opts...),
		),
		describeLimits: connect.NewClient[kinesis.DescribeLimitsInput, kinesis.DescribeLimitsOutput](
			httpClient,
			baseURL+KinesisServiceDescribeLimitsProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DescribeLimits")),
			connect.WithClientOptions(opts...),
		),
		describeStream: connect.NewClient[kinesis.DescribeStreamInput, kinesis.DescribeStreamOutput](
			httpClient,
			baseURL+KinesisServiceDescribeStreamProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DescribeStream")),
			connect.WithClientOptions(opts...),
		),
		describeStreamConsumer: connect.NewClient[kinesis.DescribeStreamConsumerInput, kinesis.DescribeStreamConsumerOutput](
			httpClient,
			baseURL+KinesisServiceDescribeStreamConsumerProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DescribeStreamConsumer")),
			connect.WithClientOptions(opts...),
		),
		describeStreamSummary: connect.NewClient[kinesis.DescribeStreamSummaryInput, kinesis.DescribeStreamSummaryOutput](
			httpClient,
			baseURL+KinesisServiceDescribeStreamSummaryProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DescribeStreamSummary")),
			connect.WithClientOptions(opts...),
		),
		disableEnhancedMonitoring: connect.NewClient[kinesis.DisableEnhancedMonitoringInput, kinesis.EnhancedMonitoringOutput](
			httpClient,
			baseURL+KinesisServiceDisableEnhancedMonitoringProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("DisableEnhancedMonitoring")),
			connect.WithClientOptions(opts...),
		),
		enableEnhancedMonitoring: connect.NewClient[kinesis.EnableEnhancedMonitoringInput, kinesis.EnhancedMonitoringOutput](
			httpClient,
			baseURL+KinesisServiceEnableEnhancedMonitoringProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("EnableEnhancedMonitoring")),
			connect.WithClientOptions(opts...),
		),
		getRecords: connect.NewClient[kinesis.GetRecordsInput, kinesis.GetRecordsOutput](
			httpClient,
			baseURL+KinesisServiceGetRecordsProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("GetRecords")),
			connect.WithClientOptions(opts...),
		),
		getResourcePolicy: connect.NewClient[kinesis.GetResourcePolicyInput, kinesis.GetResourcePolicyOutput](
			httpClient,
			baseURL+KinesisServiceGetResourcePolicyProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("GetResourcePolicy")),
			connect.WithClientOptions(opts...),
		),
		getShardIterator: connect.NewClient[kinesis.GetShardIteratorInput, kinesis.GetShardIteratorOutput](
			httpClient,
			baseURL+KinesisServiceGetShardIteratorProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("GetShardIterator")),
			connect.WithClientOptions(opts...),
		),
		increaseStreamRetentionPeriod: connect.NewClient[kinesis.IncreaseStreamRetentionPeriodInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceIncreaseStreamRetentionPeriodProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("IncreaseStreamRetentionPeriod")),
			connect.WithClientOptions(opts...),
		),
		listShards: connect.NewClient[kinesis.ListShardsInput, kinesis.ListShardsOutput](
			httpClient,
			baseURL+KinesisServiceListShardsProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("ListShards")),
			connect.WithClientOptions(opts...),
		),
		listStreamConsumers: connect.NewClient[kinesis.ListStreamConsumersInput, kinesis.ListStreamConsumersOutput](
			httpClient,
			baseURL+KinesisServiceListStreamConsumersProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("ListStreamConsumers")),
			connect.WithClientOptions(opts...),
		),
		listStreams: connect.NewClient[kinesis.ListStreamsInput, kinesis.ListStreamsOutput](
			httpClient,
			baseURL+KinesisServiceListStreamsProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("ListStreams")),
			connect.WithClientOptions(opts...),
		),
		listTagsForResource: connect.NewClient[kinesis.ListTagsForResourceInput, kinesis.ListTagsForResourceOutput](
			httpClient,
			baseURL+KinesisServiceListTagsForResourceProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("ListTagsForResource")),
			connect.WithClientOptions(opts...),
		),
		listTagsForStream: connect.NewClient[kinesis.ListTagsForStreamInput, kinesis.ListTagsForStreamOutput](
			httpClient,
			baseURL+KinesisServiceListTagsForStreamProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("ListTagsForStream")),
			connect.WithClientOptions(opts...),
		),
		mergeShards: connect.NewClient[kinesis.MergeShardsInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceMergeShardsProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("MergeShards")),
			connect.WithClientOptions(opts...),
		),
		putRecord: connect.NewClient[kinesis.PutRecordInput, kinesis.PutRecordOutput](
			httpClient,
			baseURL+KinesisServicePutRecordProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("PutRecord")),
			connect.WithClientOptions(opts...),
		),
		putRecords: connect.NewClient[kinesis.PutRecordsInput, kinesis.PutRecordsOutput](
			httpClient,
			baseURL+KinesisServicePutRecordsProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("PutRecords")),
			connect.WithClientOptions(opts...),
		),
		putResourcePolicy: connect.NewClient[kinesis.PutResourcePolicyInput, common.Empty](
			httpClient,
			baseURL+KinesisServicePutResourcePolicyProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("PutResourcePolicy")),
			connect.WithClientOptions(opts...),
		),
		registerStreamConsumer: connect.NewClient[kinesis.RegisterStreamConsumerInput, kinesis.RegisterStreamConsumerOutput](
			httpClient,
			baseURL+KinesisServiceRegisterStreamConsumerProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("RegisterStreamConsumer")),
			connect.WithClientOptions(opts...),
		),
		removeTagsFromStream: connect.NewClient[kinesis.RemoveTagsFromStreamInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceRemoveTagsFromStreamProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("RemoveTagsFromStream")),
			connect.WithClientOptions(opts...),
		),
		splitShard: connect.NewClient[kinesis.SplitShardInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceSplitShardProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("SplitShard")),
			connect.WithClientOptions(opts...),
		),
		startStreamEncryption: connect.NewClient[kinesis.StartStreamEncryptionInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceStartStreamEncryptionProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("StartStreamEncryption")),
			connect.WithClientOptions(opts...),
		),
		stopStreamEncryption: connect.NewClient[kinesis.StopStreamEncryptionInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceStopStreamEncryptionProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("StopStreamEncryption")),
			connect.WithClientOptions(opts...),
		),
		subscribeToShard: connect.NewClient[kinesis.SubscribeToShardInput, kinesis.SubscribeToShardOutput](
			httpClient,
			baseURL+KinesisServiceSubscribeToShardProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("SubscribeToShard")),
			connect.WithClientOptions(opts...),
		),
		tagResource: connect.NewClient[kinesis.TagResourceInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceTagResourceProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("TagResource")),
			connect.WithClientOptions(opts...),
		),
		untagResource: connect.NewClient[kinesis.UntagResourceInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceUntagResourceProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("UntagResource")),
			connect.WithClientOptions(opts...),
		),
		updateAccountSettings: connect.NewClient[kinesis.UpdateAccountSettingsInput, kinesis.UpdateAccountSettingsOutput](
			httpClient,
			baseURL+KinesisServiceUpdateAccountSettingsProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("UpdateAccountSettings")),
			connect.WithClientOptions(opts...),
		),
		updateMaxRecordSize: connect.NewClient[kinesis.UpdateMaxRecordSizeInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceUpdateMaxRecordSizeProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("UpdateMaxRecordSize")),
			connect.WithClientOptions(opts...),
		),
		updateShardCount: connect.NewClient[kinesis.UpdateShardCountInput, kinesis.UpdateShardCountOutput](
			httpClient,
			baseURL+KinesisServiceUpdateShardCountProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("UpdateShardCount")),
			connect.WithClientOptions(opts...),
		),
		updateStreamMode: connect.NewClient[kinesis.UpdateStreamModeInput, common.Empty](
			httpClient,
			baseURL+KinesisServiceUpdateStreamModeProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("UpdateStreamMode")),
			connect.WithClientOptions(opts...),
		),
		updateStreamWarmThroughput: connect.NewClient[kinesis.UpdateStreamWarmThroughputInput, kinesis.UpdateStreamWarmThroughputOutput](
			httpClient,
			baseURL+KinesisServiceUpdateStreamWarmThroughputProcedure,
			connect.WithSchema(kinesisServiceMethods.ByName("UpdateStreamWarmThroughput")),
			connect.WithClientOptions(opts...),
		),
	}
}

// kinesisServiceClient implements KinesisServiceClient.
type kinesisServiceClient struct {
	addTagsToStream               *connect.Client[kinesis.AddTagsToStreamInput, common.Empty]
	createStream                  *connect.Client[kinesis.CreateStreamInput, common.Empty]
	decreaseStreamRetentionPeriod *connect.Client[kinesis.DecreaseStreamRetentionPeriodInput, common.Empty]
	deleteResourcePolicy          *connect.Client[kinesis.DeleteResourcePolicyInput, common.Empty]
	deleteStream                  *connect.Client[kinesis.DeleteStreamInput, common.Empty]
	deregisterStreamConsumer      *connect.Client[kinesis.DeregisterStreamConsumerInput, common.Empty]
	describeAccountSettings       *connect.Client[kinesis.DescribeAccountSettingsInput, kinesis.DescribeAccountSettingsOutput]
	describeLimits                *connect.Client[kinesis.DescribeLimitsInput, kinesis.DescribeLimitsOutput]
	describeStream                *connect.Client[kinesis.DescribeStreamInput, kinesis.DescribeStreamOutput]
	describeStreamConsumer        *connect.Client[kinesis.DescribeStreamConsumerInput, kinesis.DescribeStreamConsumerOutput]
	describeStreamSummary         *connect.Client[kinesis.DescribeStreamSummaryInput, kinesis.DescribeStreamSummaryOutput]
	disableEnhancedMonitoring     *connect.Client[kinesis.DisableEnhancedMonitoringInput, kinesis.EnhancedMonitoringOutput]
	enableEnhancedMonitoring      *connect.Client[kinesis.EnableEnhancedMonitoringInput, kinesis.EnhancedMonitoringOutput]
	getRecords                    *connect.Client[kinesis.GetRecordsInput, kinesis.GetRecordsOutput]
	getResourcePolicy             *connect.Client[kinesis.GetResourcePolicyInput, kinesis.GetResourcePolicyOutput]
	getShardIterator              *connect.Client[kinesis.GetShardIteratorInput, kinesis.GetShardIteratorOutput]
	increaseStreamRetentionPeriod *connect.Client[kinesis.IncreaseStreamRetentionPeriodInput, common.Empty]
	listShards                    *connect.Client[kinesis.ListShardsInput, kinesis.ListShardsOutput]
	listStreamConsumers           *connect.Client[kinesis.ListStreamConsumersInput, kinesis.ListStreamConsumersOutput]
	listStreams                   *connect.Client[kinesis.ListStreamsInput, kinesis.ListStreamsOutput]
	listTagsForResource           *connect.Client[kinesis.ListTagsForResourceInput, kinesis.ListTagsForResourceOutput]
	listTagsForStream             *connect.Client[kinesis.ListTagsForStreamInput, kinesis.ListTagsForStreamOutput]
	mergeShards                   *connect.Client[kinesis.MergeShardsInput, common.Empty]
	putRecord                     *connect.Client[kinesis.PutRecordInput, kinesis.PutRecordOutput]
	putRecords                    *connect.Client[kinesis.PutRecordsInput, kinesis.PutRecordsOutput]
	putResourcePolicy             *connect.Client[kinesis.PutResourcePolicyInput, common.Empty]
	registerStreamConsumer        *connect.Client[kinesis.RegisterStreamConsumerInput, kinesis.RegisterStreamConsumerOutput]
	removeTagsFromStream          *connect.Client[kinesis.RemoveTagsFromStreamInput, common.Empty]
	splitShard                    *connect.Client[kinesis.SplitShardInput, common.Empty]
	startStreamEncryption         *connect.Client[kinesis.StartStreamEncryptionInput, common.Empty]
	stopStreamEncryption          *connect.Client[kinesis.StopStreamEncryptionInput, common.Empty]
	subscribeToShard              *connect.Client[kinesis.SubscribeToShardInput, kinesis.SubscribeToShardOutput]
	tagResource                   *connect.Client[kinesis.TagResourceInput, common.Empty]
	untagResource                 *connect.Client[kinesis.UntagResourceInput, common.Empty]
	updateAccountSettings         *connect.Client[kinesis.UpdateAccountSettingsInput, kinesis.UpdateAccountSettingsOutput]
	updateMaxRecordSize           *connect.Client[kinesis.UpdateMaxRecordSizeInput, common.Empty]
	updateShardCount              *connect.Client[kinesis.UpdateShardCountInput, kinesis.UpdateShardCountOutput]
	updateStreamMode              *connect.Client[kinesis.UpdateStreamModeInput, common.Empty]
	updateStreamWarmThroughput    *connect.Client[kinesis.UpdateStreamWarmThroughputInput, kinesis.UpdateStreamWarmThroughputOutput]
}

// AddTagsToStream calls kinesis.KinesisService.AddTagsToStream.
func (c *kinesisServiceClient) AddTagsToStream(ctx context.Context, req *connect.Request[kinesis.AddTagsToStreamInput]) (*connect.Response[common.Empty], error) {
	return c.addTagsToStream.CallUnary(ctx, req)
}

// CreateStream calls kinesis.KinesisService.CreateStream.
func (c *kinesisServiceClient) CreateStream(ctx context.Context, req *connect.Request[kinesis.CreateStreamInput]) (*connect.Response[common.Empty], error) {
	return c.createStream.CallUnary(ctx, req)
}

// DecreaseStreamRetentionPeriod calls kinesis.KinesisService.DecreaseStreamRetentionPeriod.
func (c *kinesisServiceClient) DecreaseStreamRetentionPeriod(ctx context.Context, req *connect.Request[kinesis.DecreaseStreamRetentionPeriodInput]) (*connect.Response[common.Empty], error) {
	return c.decreaseStreamRetentionPeriod.CallUnary(ctx, req)
}

// DeleteResourcePolicy calls kinesis.KinesisService.DeleteResourcePolicy.
func (c *kinesisServiceClient) DeleteResourcePolicy(ctx context.Context, req *connect.Request[kinesis.DeleteResourcePolicyInput]) (*connect.Response[common.Empty], error) {
	return c.deleteResourcePolicy.CallUnary(ctx, req)
}

// DeleteStream calls kinesis.KinesisService.DeleteStream.
func (c *kinesisServiceClient) DeleteStream(ctx context.Context, req *connect.Request[kinesis.DeleteStreamInput]) (*connect.Response[common.Empty], error) {
	return c.deleteStream.CallUnary(ctx, req)
}

// DeregisterStreamConsumer calls kinesis.KinesisService.DeregisterStreamConsumer.
func (c *kinesisServiceClient) DeregisterStreamConsumer(ctx context.Context, req *connect.Request[kinesis.DeregisterStreamConsumerInput]) (*connect.Response[common.Empty], error) {
	return c.deregisterStreamConsumer.CallUnary(ctx, req)
}

// DescribeAccountSettings calls kinesis.KinesisService.DescribeAccountSettings.
func (c *kinesisServiceClient) DescribeAccountSettings(ctx context.Context, req *connect.Request[kinesis.DescribeAccountSettingsInput]) (*connect.Response[kinesis.DescribeAccountSettingsOutput], error) {
	return c.describeAccountSettings.CallUnary(ctx, req)
}

// DescribeLimits calls kinesis.KinesisService.DescribeLimits.
func (c *kinesisServiceClient) DescribeLimits(ctx context.Context, req *connect.Request[kinesis.DescribeLimitsInput]) (*connect.Response[kinesis.DescribeLimitsOutput], error) {
	return c.describeLimits.CallUnary(ctx, req)
}

// DescribeStream calls kinesis.KinesisService.DescribeStream.
func (c *kinesisServiceClient) DescribeStream(ctx context.Context, req *connect.Request[kinesis.DescribeStreamInput]) (*connect.Response[kinesis.DescribeStreamOutput], error) {
	return c.describeStream.CallUnary(ctx, req)
}

// DescribeStreamConsumer calls kinesis.KinesisService.DescribeStreamConsumer.
func (c *kinesisServiceClient) DescribeStreamConsumer(ctx context.Context, req *connect.Request[kinesis.DescribeStreamConsumerInput]) (*connect.Response[kinesis.DescribeStreamConsumerOutput], error) {
	return c.describeStreamConsumer.CallUnary(ctx, req)
}

// DescribeStreamSummary calls kinesis.KinesisService.DescribeStreamSummary.
func (c *kinesisServiceClient) DescribeStreamSummary(ctx context.Context, req *connect.Request[kinesis.DescribeStreamSummaryInput]) (*connect.Response[kinesis.DescribeStreamSummaryOutput], error) {
	return c.describeStreamSummary.CallUnary(ctx, req)
}

// DisableEnhancedMonitoring calls kinesis.KinesisService.DisableEnhancedMonitoring.
func (c *kinesisServiceClient) DisableEnhancedMonitoring(ctx context.Context, req *connect.Request[kinesis.DisableEnhancedMonitoringInput]) (*connect.Response[kinesis.EnhancedMonitoringOutput], error) {
	return c.disableEnhancedMonitoring.CallUnary(ctx, req)
}

// EnableEnhancedMonitoring calls kinesis.KinesisService.EnableEnhancedMonitoring.
func (c *kinesisServiceClient) EnableEnhancedMonitoring(ctx context.Context, req *connect.Request[kinesis.EnableEnhancedMonitoringInput]) (*connect.Response[kinesis.EnhancedMonitoringOutput], error) {
	return c.enableEnhancedMonitoring.CallUnary(ctx, req)
}

// GetRecords calls kinesis.KinesisService.GetRecords.
func (c *kinesisServiceClient) GetRecords(ctx context.Context, req *connect.Request[kinesis.GetRecordsInput]) (*connect.Response[kinesis.GetRecordsOutput], error) {
	return c.getRecords.CallUnary(ctx, req)
}

// GetResourcePolicy calls kinesis.KinesisService.GetResourcePolicy.
func (c *kinesisServiceClient) GetResourcePolicy(ctx context.Context, req *connect.Request[kinesis.GetResourcePolicyInput]) (*connect.Response[kinesis.GetResourcePolicyOutput], error) {
	return c.getResourcePolicy.CallUnary(ctx, req)
}

// GetShardIterator calls kinesis.KinesisService.GetShardIterator.
func (c *kinesisServiceClient) GetShardIterator(ctx context.Context, req *connect.Request[kinesis.GetShardIteratorInput]) (*connect.Response[kinesis.GetShardIteratorOutput], error) {
	return c.getShardIterator.CallUnary(ctx, req)
}

// IncreaseStreamRetentionPeriod calls kinesis.KinesisService.IncreaseStreamRetentionPeriod.
func (c *kinesisServiceClient) IncreaseStreamRetentionPeriod(ctx context.Context, req *connect.Request[kinesis.IncreaseStreamRetentionPeriodInput]) (*connect.Response[common.Empty], error) {
	return c.increaseStreamRetentionPeriod.CallUnary(ctx, req)
}

// ListShards calls kinesis.KinesisService.ListShards.
func (c *kinesisServiceClient) ListShards(ctx context.Context, req *connect.Request[kinesis.ListShardsInput]) (*connect.Response[kinesis.ListShardsOutput], error) {
	return c.listShards.CallUnary(ctx, req)
}

// ListStreamConsumers calls kinesis.KinesisService.ListStreamConsumers.
func (c *kinesisServiceClient) ListStreamConsumers(ctx context.Context, req *connect.Request[kinesis.ListStreamConsumersInput]) (*connect.Response[kinesis.ListStreamConsumersOutput], error) {
	return c.listStreamConsumers.CallUnary(ctx, req)
}

// ListStreams calls kinesis.KinesisService.ListStreams.
func (c *kinesisServiceClient) ListStreams(ctx context.Context, req *connect.Request[kinesis.ListStreamsInput]) (*connect.Response[kinesis.ListStreamsOutput], error) {
	return c.listStreams.CallUnary(ctx, req)
}

// ListTagsForResource calls kinesis.KinesisService.ListTagsForResource.
func (c *kinesisServiceClient) ListTagsForResource(ctx context.Context, req *connect.Request[kinesis.ListTagsForResourceInput]) (*connect.Response[kinesis.ListTagsForResourceOutput], error) {
	return c.listTagsForResource.CallUnary(ctx, req)
}

// ListTagsForStream calls kinesis.KinesisService.ListTagsForStream.
func (c *kinesisServiceClient) ListTagsForStream(ctx context.Context, req *connect.Request[kinesis.ListTagsForStreamInput]) (*connect.Response[kinesis.ListTagsForStreamOutput], error) {
	return c.listTagsForStream.CallUnary(ctx, req)
}

// MergeShards calls kinesis.KinesisService.MergeShards.
func (c *kinesisServiceClient) MergeShards(ctx context.Context, req *connect.Request[kinesis.MergeShardsInput]) (*connect.Response[common.Empty], error) {
	return c.mergeShards.CallUnary(ctx, req)
}

// PutRecord calls kinesis.KinesisService.PutRecord.
func (c *kinesisServiceClient) PutRecord(ctx context.Context, req *connect.Request[kinesis.PutRecordInput]) (*connect.Response[kinesis.PutRecordOutput], error) {
	return c.putRecord.CallUnary(ctx, req)
}

// PutRecords calls kinesis.KinesisService.PutRecords.
func (c *kinesisServiceClient) PutRecords(ctx context.Context, req *connect.Request[kinesis.PutRecordsInput]) (*connect.Response[kinesis.PutRecordsOutput], error) {
	return c.putRecords.CallUnary(ctx, req)
}

// PutResourcePolicy calls kinesis.KinesisService.PutResourcePolicy.
func (c *kinesisServiceClient) PutResourcePolicy(ctx context.Context, req *connect.Request[kinesis.PutResourcePolicyInput]) (*connect.Response[common.Empty], error) {
	return c.putResourcePolicy.CallUnary(ctx, req)
}

// RegisterStreamConsumer calls kinesis.KinesisService.RegisterStreamConsumer.
func (c *kinesisServiceClient) RegisterStreamConsumer(ctx context.Context, req *connect.Request[kinesis.RegisterStreamConsumerInput]) (*connect.Response[kinesis.RegisterStreamConsumerOutput], error) {
	return c.registerStreamConsumer.CallUnary(ctx, req)
}

// RemoveTagsFromStream calls kinesis.KinesisService.RemoveTagsFromStream.
func (c *kinesisServiceClient) RemoveTagsFromStream(ctx context.Context, req *connect.Request[kinesis.RemoveTagsFromStreamInput]) (*connect.Response[common.Empty], error) {
	return c.removeTagsFromStream.CallUnary(ctx, req)
}

// SplitShard calls kinesis.KinesisService.SplitShard.
func (c *kinesisServiceClient) SplitShard(ctx context.Context, req *connect.Request[kinesis.SplitShardInput]) (*connect.Response[common.Empty], error) {
	return c.splitShard.CallUnary(ctx, req)
}

// StartStreamEncryption calls kinesis.KinesisService.StartStreamEncryption.
func (c *kinesisServiceClient) StartStreamEncryption(ctx context.Context, req *connect.Request[kinesis.StartStreamEncryptionInput]) (*connect.Response[common.Empty], error) {
	return c.startStreamEncryption.CallUnary(ctx, req)
}

// StopStreamEncryption calls kinesis.KinesisService.StopStreamEncryption.
func (c *kinesisServiceClient) StopStreamEncryption(ctx context.Context, req *connect.Request[kinesis.StopStreamEncryptionInput]) (*connect.Response[common.Empty], error) {
	return c.stopStreamEncryption.CallUnary(ctx, req)
}

// SubscribeToShard calls kinesis.KinesisService.SubscribeToShard.
func (c *kinesisServiceClient) SubscribeToShard(ctx context.Context, req *connect.Request[kinesis.SubscribeToShardInput]) (*connect.Response[kinesis.SubscribeToShardOutput], error) {
	return c.subscribeToShard.CallUnary(ctx, req)
}

// TagResource calls kinesis.KinesisService.TagResource.
func (c *kinesisServiceClient) TagResource(ctx context.Context, req *connect.Request[kinesis.TagResourceInput]) (*connect.Response[common.Empty], error) {
	return c.tagResource.CallUnary(ctx, req)
}

// UntagResource calls kinesis.KinesisService.UntagResource.
func (c *kinesisServiceClient) UntagResource(ctx context.Context, req *connect.Request[kinesis.UntagResourceInput]) (*connect.Response[common.Empty], error) {
	return c.untagResource.CallUnary(ctx, req)
}

// UpdateAccountSettings calls kinesis.KinesisService.UpdateAccountSettings.
func (c *kinesisServiceClient) UpdateAccountSettings(ctx context.Context, req *connect.Request[kinesis.UpdateAccountSettingsInput]) (*connect.Response[kinesis.UpdateAccountSettingsOutput], error) {
	return c.updateAccountSettings.CallUnary(ctx, req)
}

// UpdateMaxRecordSize calls kinesis.KinesisService.UpdateMaxRecordSize.
func (c *kinesisServiceClient) UpdateMaxRecordSize(ctx context.Context, req *connect.Request[kinesis.UpdateMaxRecordSizeInput]) (*connect.Response[common.Empty], error) {
	return c.updateMaxRecordSize.CallUnary(ctx, req)
}

// UpdateShardCount calls kinesis.KinesisService.UpdateShardCount.
func (c *kinesisServiceClient) UpdateShardCount(ctx context.Context, req *connect.Request[kinesis.UpdateShardCountInput]) (*connect.Response[kinesis.UpdateShardCountOutput], error) {
	return c.updateShardCount.CallUnary(ctx, req)
}

// UpdateStreamMode calls kinesis.KinesisService.UpdateStreamMode.
func (c *kinesisServiceClient) UpdateStreamMode(ctx context.Context, req *connect.Request[kinesis.UpdateStreamModeInput]) (*connect.Response[common.Empty], error) {
	return c.updateStreamMode.CallUnary(ctx, req)
}

// UpdateStreamWarmThroughput calls kinesis.KinesisService.UpdateStreamWarmThroughput.
func (c *kinesisServiceClient) UpdateStreamWarmThroughput(ctx context.Context, req *connect.Request[kinesis.UpdateStreamWarmThroughputInput]) (*connect.Response[kinesis.UpdateStreamWarmThroughputOutput], error) {
	return c.updateStreamWarmThroughput.CallUnary(ctx, req)
}

// KinesisServiceHandler is an implementation of the kinesis.KinesisService service.
type KinesisServiceHandler interface {
	// Adds or updates tags for the specified Kinesis data stream. You can assign up to 50 tags to a data stream. When invoking this API, you must use either the StreamARN or the StreamName parameter, or ...
	// HTTP:
	// Protocol: awsJson1_1
	AddTagsToStream(context.Context, *connect.Request[kinesis.AddTagsToStreamInput]) (*connect.Response[common.Empty], error)
	// Creates a Kinesis data stream. A stream captures and transports data records that are continuously emitted from different data sources or producers. Scale-out within a stream is explicitly supporte...
	// HTTP:
	// Protocol: awsJson1_1
	CreateStream(context.Context, *connect.Request[kinesis.CreateStreamInput]) (*connect.Response[common.Empty], error)
	// Decreases the Kinesis data stream's retention period, which is the length of time data records are accessible after they are added to the stream. The minimum value of a stream's retention period is...
	// HTTP:
	// Protocol: awsJson1_1
	DecreaseStreamRetentionPeriod(context.Context, *connect.Request[kinesis.DecreaseStreamRetentionPeriodInput]) (*connect.Response[common.Empty], error)
	// Delete a policy for the specified data stream or consumer. Request patterns can be one of the following: Data stream pattern: arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+ Consumer pattern: ^(arn):aws.*...
	// HTTP:
	// Protocol: awsJson1_1
	DeleteResourcePolicy(context.Context, *connect.Request[kinesis.DeleteResourcePolicyInput]) (*connect.Response[common.Empty], error)
	// Deletes a Kinesis data stream and all its shards and data. You must shut down any applications that are operating on the stream before you delete the stream. If an application attempts to operate o...
	// HTTP:
	// Protocol: awsJson1_1
	DeleteStream(context.Context, *connect.Request[kinesis.DeleteStreamInput]) (*connect.Response[common.Empty], error)
	// To deregister a consumer, provide its ARN. Alternatively, you can provide the ARN of the data stream and the name you gave the consumer when you registered it. You may also provide all three parame...
	// HTTP:
	// Protocol: awsJson1_1
	DeregisterStreamConsumer(context.Context, *connect.Request[kinesis.DeregisterStreamConsumerInput]) (*connect.Response[common.Empty], error)
	// Describes the account-level settings for Amazon Kinesis Data Streams. This operation returns information about the minimum throughput billing commitments and other account-level configurations. Thi...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeAccountSettings(context.Context, *connect.Request[kinesis.DescribeAccountSettingsInput]) (*connect.Response[kinesis.DescribeAccountSettingsOutput], error)
	// Describes the shard limits and usage for the account. If you update your account limits, the old limits might be returned for a few minutes. This operation has a limit of one transaction per second...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeLimits(context.Context, *connect.Request[kinesis.DescribeLimitsInput]) (*connect.Response[kinesis.DescribeLimitsOutput], error)
	// Describes the specified Kinesis data stream. This API has been revised. It's highly recommended that you use the DescribeStreamSummary API to get a summarized description of the specified Kinesis d...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeStream(context.Context, *connect.Request[kinesis.DescribeStreamInput]) (*connect.Response[kinesis.DescribeStreamOutput], error)
	// To get the description of a registered consumer, provide the ARN of the consumer. Alternatively, you can provide the ARN of the data stream and the name you gave the consumer when you registered it...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeStreamConsumer(context.Context, *connect.Request[kinesis.DescribeStreamConsumerInput]) (*connect.Response[kinesis.DescribeStreamConsumerOutput], error)
	// Provides a summarized description of the specified Kinesis data stream without the shard list. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is ...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeStreamSummary(context.Context, *connect.Request[kinesis.DescribeStreamSummaryInput]) (*connect.Response[kinesis.DescribeStreamSummaryOutput], error)
	// Disables enhanced monitoring. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is recommended that you use the StreamARN input parameter when you i...
	// HTTP:
	// Protocol: awsJson1_1
	DisableEnhancedMonitoring(context.Context, *connect.Request[kinesis.DisableEnhancedMonitoringInput]) (*connect.Response[kinesis.EnhancedMonitoringOutput], error)
	// Enables enhanced Kinesis data stream monitoring for shard-level metrics. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is recommended that you u...
	// HTTP:
	// Protocol: awsJson1_1
	EnableEnhancedMonitoring(context.Context, *connect.Request[kinesis.EnableEnhancedMonitoringInput]) (*connect.Response[kinesis.EnhancedMonitoringOutput], error)
	// Gets data records from a Kinesis data stream's shard. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is recommended that you use the StreamARN in...
	// HTTP:
	// Protocol: awsJson1_1
	GetRecords(context.Context, *connect.Request[kinesis.GetRecordsInput]) (*connect.Response[kinesis.GetRecordsOutput], error)
	// Returns a policy attached to the specified data stream or consumer. Request patterns can be one of the following: Data stream pattern: arn:aws.*:kinesis:.*:\d{12}:.*stream/\S+ Consumer pattern: ^(a...
	// HTTP:
	// Protocol: awsJson1_1
	GetResourcePolicy(context.Context, *connect.Request[kinesis.GetResourcePolicyInput]) (*connect.Response[kinesis.GetResourcePolicyOutput], error)
	// Gets an Amazon Kinesis shard iterator. A shard iterator expires 5 minutes after it is returned to the requester. When invoking this API, you must use either the StreamARN or the StreamName paramete...
	// HTTP:
	// Protocol: awsJson1_1
	GetShardIterator(context.Context, *connect.Request[kinesis.GetShardIteratorInput]) (*connect.Response[kinesis.GetShardIteratorOutput], error)
	// Increases the Kinesis data stream's retention period, which is the length of time data records are accessible after they are added to the stream. The maximum value of a stream's retention period is...
	// HTTP:
	// Protocol: awsJson1_1
	IncreaseStreamRetentionPeriod(context.Context, *connect.Request[kinesis.IncreaseStreamRetentionPeriodInput]) (*connect.Response[common.Empty], error)
	// Lists the shards in a stream and provides information about each shard. This operation has a limit of 1000 transactions per second per data stream. When invoking this API, you must use either the S...
	// HTTP:
	// Protocol: awsJson1_1
	ListShards(context.Context, *connect.Request[kinesis.ListShardsInput]) (*connect.Response[kinesis.ListShardsOutput], error)
	// Lists the consumers registered to receive data from a stream using enhanced fan-out, and provides information about each consumer. This operation has a limit of 5 transactions per second per stream.
	// HTTP:
	// Protocol: awsJson1_1
	ListStreamConsumers(context.Context, *connect.Request[kinesis.ListStreamConsumersInput]) (*connect.Response[kinesis.ListStreamConsumersOutput], error)
	// Lists your Kinesis data streams. The number of streams may be too large to return from a single call to ListStreams. You can limit the number of returned streams using the Limit parameter. If you d...
	// HTTP:
	// Protocol: awsJson1_1
	ListStreams(context.Context, *connect.Request[kinesis.ListStreamsInput]) (*connect.Response[kinesis.ListStreamsOutput], error)
	// List all tags added to the specified Kinesis resource. Each tag is a label consisting of a user-defined key and value. Tags can help you manage, identify, organize, search for, and filter resources...
	// HTTP:
	// Protocol: awsJson1_1
	ListTagsForResource(context.Context, *connect.Request[kinesis.ListTagsForResourceInput]) (*connect.Response[kinesis.ListTagsForResourceOutput], error)
	// Lists the tags for the specified Kinesis data stream. This operation has a limit of five transactions per second per account. When invoking this API, you must use either the StreamARN or the Stream...
	// HTTP:
	// Protocol: awsJson1_1
	ListTagsForStream(context.Context, *connect.Request[kinesis.ListTagsForStreamInput]) (*connect.Response[kinesis.ListTagsForStreamOutput], error)
	// Merges two adjacent shards in a Kinesis data stream and combines them into a single shard to reduce the stream's capacity to ingest and transport data. This API is only supported for the data strea...
	// HTTP:
	// Protocol: awsJson1_1
	MergeShards(context.Context, *connect.Request[kinesis.MergeShardsInput]) (*connect.Response[common.Empty], error)
	// Writes a single data record into an Amazon Kinesis data stream. Call PutRecord to send data into the stream for real-time ingestion and subsequent processing, one record at a time. Each shard can s...
	// HTTP:
	// Protocol: awsJson1_1
	PutRecord(context.Context, *connect.Request[kinesis.PutRecordInput]) (*connect.Response[kinesis.PutRecordOutput], error)
	// Writes multiple data records into a Kinesis data stream in a single call (also referred to as a PutRecords request). Use this operation to send data into the stream for data ingestion and processin...
	// HTTP:
	// Protocol: awsJson1_1
	PutRecords(context.Context, *connect.Request[kinesis.PutRecordsInput]) (*connect.Response[kinesis.PutRecordsOutput], error)
	// Attaches a resource-based policy to a data stream or registered consumer. If you are using an identity other than the root user of the Amazon Web Services account that owns the resource, the callin...
	// HTTP:
	// Protocol: awsJson1_1
	PutResourcePolicy(context.Context, *connect.Request[kinesis.PutResourcePolicyInput]) (*connect.Response[common.Empty], error)
	// Registers a consumer with a Kinesis data stream. When you use this operation, the consumer you register can then call SubscribeToShard to receive data from the stream using enhanced fan-out, at a r...
	// HTTP:
	// Protocol: awsJson1_1
	RegisterStreamConsumer(context.Context, *connect.Request[kinesis.RegisterStreamConsumerInput]) (*connect.Response[kinesis.RegisterStreamConsumerOutput], error)
	// Removes tags from the specified Kinesis data stream. Removed tags are deleted and cannot be recovered after this operation successfully completes. When invoking this API, you must use either the St...
	// HTTP:
	// Protocol: awsJson1_1
	RemoveTagsFromStream(context.Context, *connect.Request[kinesis.RemoveTagsFromStreamInput]) (*connect.Response[common.Empty], error)
	// Splits a shard into two new shards in the Kinesis data stream, to increase the stream's capacity to ingest and transport data. SplitShard is called when there is a need to increase the overall capa...
	// HTTP:
	// Protocol: awsJson1_1
	SplitShard(context.Context, *connect.Request[kinesis.SplitShardInput]) (*connect.Response[common.Empty], error)
	// Enables or updates server-side encryption using an Amazon Web Services KMS key for a specified stream. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both...
	// HTTP:
	// Protocol: awsJson1_1
	StartStreamEncryption(context.Context, *connect.Request[kinesis.StartStreamEncryptionInput]) (*connect.Response[common.Empty], error)
	// Disables server-side encryption for a specified stream. When invoking this API, you must use either the StreamARN or the StreamName parameter, or both. It is recommended that you use the StreamARN ...
	// HTTP:
	// Protocol: awsJson1_1
	StopStreamEncryption(context.Context, *connect.Request[kinesis.StopStreamEncryptionInput]) (*connect.Response[common.Empty], error)
	// This operation establishes an HTTP/2 connection between the consumer you specify in the ConsumerARN parameter and the shard you specify in the ShardId parameter. After the connection is successfull...
	// HTTP:
	// Protocol: awsJson1_1
	SubscribeToShard(context.Context, *connect.Request[kinesis.SubscribeToShardInput]) (*connect.Response[kinesis.SubscribeToShardOutput], error)
	// Adds or updates tags for the specified Kinesis resource. Each tag is a label consisting of a user-defined key and value. Tags can help you manage, identify, organize, search for, and filter resourc...
	// HTTP:
	// Protocol: awsJson1_1
	TagResource(context.Context, *connect.Request[kinesis.TagResourceInput]) (*connect.Response[common.Empty], error)
	// Removes tags from the specified Kinesis resource. Removed tags are deleted and can't be recovered after this operation completes successfully.
	// HTTP:
	// Protocol: awsJson1_1
	UntagResource(context.Context, *connect.Request[kinesis.UntagResourceInput]) (*connect.Response[common.Empty], error)
	// Updates the account-level settings for Amazon Kinesis Data Streams. Updating account settings is a synchronous operation. Upon receiving the request, Kinesis Data Streams will return immediately wi...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateAccountSettings(context.Context, *connect.Request[kinesis.UpdateAccountSettingsInput]) (*connect.Response[kinesis.UpdateAccountSettingsOutput], error)
	// This allows you to update the MaxRecordSize of a single record that you can write to, and read from a stream. You can ingest and digest single records up to 10240 KiB.
	// HTTP:
	// Protocol: awsJson1_1
	UpdateMaxRecordSize(context.Context, *connect.Request[kinesis.UpdateMaxRecordSizeInput]) (*connect.Response[common.Empty], error)
	// Updates the shard count of the specified stream to the specified number of shards. This API is only supported for the data streams with the provisioned capacity mode. When invoking this API, you mu...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateShardCount(context.Context, *connect.Request[kinesis.UpdateShardCountInput]) (*connect.Response[kinesis.UpdateShardCountOutput], error)
	// Updates the capacity mode of the data stream. Currently, in Kinesis Data Streams, you can choose between an on-demand capacity mode and a provisioned capacity mode for your data stream. If you'd st...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateStreamMode(context.Context, *connect.Request[kinesis.UpdateStreamModeInput]) (*connect.Response[common.Empty], error)
	// Updates the warm throughput configuration for the specified Amazon Kinesis Data Streams on-demand data stream. This operation allows you to proactively scale your on-demand data stream to a specifi...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateStreamWarmThroughput(context.Context, *connect.Request[kinesis.UpdateStreamWarmThroughputInput]) (*connect.Response[kinesis.UpdateStreamWarmThroughputOutput], error)
}

// NewKinesisServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKinesisServiceHandler(svc KinesisServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	kinesisServiceMethods := kinesis.File_kinesis_proto.Services().ByName("KinesisService").Methods()
	kinesisServiceAddTagsToStreamHandler := connect.NewUnaryHandler(
		KinesisServiceAddTagsToStreamProcedure,
		svc.AddTagsToStream,
		connect.WithSchema(kinesisServiceMethods.ByName("AddTagsToStream")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceCreateStreamHandler := connect.NewUnaryHandler(
		KinesisServiceCreateStreamProcedure,
		svc.CreateStream,
		connect.WithSchema(kinesisServiceMethods.ByName("CreateStream")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDecreaseStreamRetentionPeriodHandler := connect.NewUnaryHandler(
		KinesisServiceDecreaseStreamRetentionPeriodProcedure,
		svc.DecreaseStreamRetentionPeriod,
		connect.WithSchema(kinesisServiceMethods.ByName("DecreaseStreamRetentionPeriod")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDeleteResourcePolicyHandler := connect.NewUnaryHandler(
		KinesisServiceDeleteResourcePolicyProcedure,
		svc.DeleteResourcePolicy,
		connect.WithSchema(kinesisServiceMethods.ByName("DeleteResourcePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDeleteStreamHandler := connect.NewUnaryHandler(
		KinesisServiceDeleteStreamProcedure,
		svc.DeleteStream,
		connect.WithSchema(kinesisServiceMethods.ByName("DeleteStream")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDeregisterStreamConsumerHandler := connect.NewUnaryHandler(
		KinesisServiceDeregisterStreamConsumerProcedure,
		svc.DeregisterStreamConsumer,
		connect.WithSchema(kinesisServiceMethods.ByName("DeregisterStreamConsumer")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDescribeAccountSettingsHandler := connect.NewUnaryHandler(
		KinesisServiceDescribeAccountSettingsProcedure,
		svc.DescribeAccountSettings,
		connect.WithSchema(kinesisServiceMethods.ByName("DescribeAccountSettings")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDescribeLimitsHandler := connect.NewUnaryHandler(
		KinesisServiceDescribeLimitsProcedure,
		svc.DescribeLimits,
		connect.WithSchema(kinesisServiceMethods.ByName("DescribeLimits")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDescribeStreamHandler := connect.NewUnaryHandler(
		KinesisServiceDescribeStreamProcedure,
		svc.DescribeStream,
		connect.WithSchema(kinesisServiceMethods.ByName("DescribeStream")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDescribeStreamConsumerHandler := connect.NewUnaryHandler(
		KinesisServiceDescribeStreamConsumerProcedure,
		svc.DescribeStreamConsumer,
		connect.WithSchema(kinesisServiceMethods.ByName("DescribeStreamConsumer")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDescribeStreamSummaryHandler := connect.NewUnaryHandler(
		KinesisServiceDescribeStreamSummaryProcedure,
		svc.DescribeStreamSummary,
		connect.WithSchema(kinesisServiceMethods.ByName("DescribeStreamSummary")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceDisableEnhancedMonitoringHandler := connect.NewUnaryHandler(
		KinesisServiceDisableEnhancedMonitoringProcedure,
		svc.DisableEnhancedMonitoring,
		connect.WithSchema(kinesisServiceMethods.ByName("DisableEnhancedMonitoring")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceEnableEnhancedMonitoringHandler := connect.NewUnaryHandler(
		KinesisServiceEnableEnhancedMonitoringProcedure,
		svc.EnableEnhancedMonitoring,
		connect.WithSchema(kinesisServiceMethods.ByName("EnableEnhancedMonitoring")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceGetRecordsHandler := connect.NewUnaryHandler(
		KinesisServiceGetRecordsProcedure,
		svc.GetRecords,
		connect.WithSchema(kinesisServiceMethods.ByName("GetRecords")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceGetResourcePolicyHandler := connect.NewUnaryHandler(
		KinesisServiceGetResourcePolicyProcedure,
		svc.GetResourcePolicy,
		connect.WithSchema(kinesisServiceMethods.ByName("GetResourcePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceGetShardIteratorHandler := connect.NewUnaryHandler(
		KinesisServiceGetShardIteratorProcedure,
		svc.GetShardIterator,
		connect.WithSchema(kinesisServiceMethods.ByName("GetShardIterator")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceIncreaseStreamRetentionPeriodHandler := connect.NewUnaryHandler(
		KinesisServiceIncreaseStreamRetentionPeriodProcedure,
		svc.IncreaseStreamRetentionPeriod,
		connect.WithSchema(kinesisServiceMethods.ByName("IncreaseStreamRetentionPeriod")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceListShardsHandler := connect.NewUnaryHandler(
		KinesisServiceListShardsProcedure,
		svc.ListShards,
		connect.WithSchema(kinesisServiceMethods.ByName("ListShards")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceListStreamConsumersHandler := connect.NewUnaryHandler(
		KinesisServiceListStreamConsumersProcedure,
		svc.ListStreamConsumers,
		connect.WithSchema(kinesisServiceMethods.ByName("ListStreamConsumers")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceListStreamsHandler := connect.NewUnaryHandler(
		KinesisServiceListStreamsProcedure,
		svc.ListStreams,
		connect.WithSchema(kinesisServiceMethods.ByName("ListStreams")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceListTagsForResourceHandler := connect.NewUnaryHandler(
		KinesisServiceListTagsForResourceProcedure,
		svc.ListTagsForResource,
		connect.WithSchema(kinesisServiceMethods.ByName("ListTagsForResource")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceListTagsForStreamHandler := connect.NewUnaryHandler(
		KinesisServiceListTagsForStreamProcedure,
		svc.ListTagsForStream,
		connect.WithSchema(kinesisServiceMethods.ByName("ListTagsForStream")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceMergeShardsHandler := connect.NewUnaryHandler(
		KinesisServiceMergeShardsProcedure,
		svc.MergeShards,
		connect.WithSchema(kinesisServiceMethods.ByName("MergeShards")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServicePutRecordHandler := connect.NewUnaryHandler(
		KinesisServicePutRecordProcedure,
		svc.PutRecord,
		connect.WithSchema(kinesisServiceMethods.ByName("PutRecord")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServicePutRecordsHandler := connect.NewUnaryHandler(
		KinesisServicePutRecordsProcedure,
		svc.PutRecords,
		connect.WithSchema(kinesisServiceMethods.ByName("PutRecords")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServicePutResourcePolicyHandler := connect.NewUnaryHandler(
		KinesisServicePutResourcePolicyProcedure,
		svc.PutResourcePolicy,
		connect.WithSchema(kinesisServiceMethods.ByName("PutResourcePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceRegisterStreamConsumerHandler := connect.NewUnaryHandler(
		KinesisServiceRegisterStreamConsumerProcedure,
		svc.RegisterStreamConsumer,
		connect.WithSchema(kinesisServiceMethods.ByName("RegisterStreamConsumer")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceRemoveTagsFromStreamHandler := connect.NewUnaryHandler(
		KinesisServiceRemoveTagsFromStreamProcedure,
		svc.RemoveTagsFromStream,
		connect.WithSchema(kinesisServiceMethods.ByName("RemoveTagsFromStream")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceSplitShardHandler := connect.NewUnaryHandler(
		KinesisServiceSplitShardProcedure,
		svc.SplitShard,
		connect.WithSchema(kinesisServiceMethods.ByName("SplitShard")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceStartStreamEncryptionHandler := connect.NewUnaryHandler(
		KinesisServiceStartStreamEncryptionProcedure,
		svc.StartStreamEncryption,
		connect.WithSchema(kinesisServiceMethods.ByName("StartStreamEncryption")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceStopStreamEncryptionHandler := connect.NewUnaryHandler(
		KinesisServiceStopStreamEncryptionProcedure,
		svc.StopStreamEncryption,
		connect.WithSchema(kinesisServiceMethods.ByName("StopStreamEncryption")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceSubscribeToShardHandler := connect.NewUnaryHandler(
		KinesisServiceSubscribeToShardProcedure,
		svc.SubscribeToShard,
		connect.WithSchema(kinesisServiceMethods.ByName("SubscribeToShard")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceTagResourceHandler := connect.NewUnaryHandler(
		KinesisServiceTagResourceProcedure,
		svc.TagResource,
		connect.WithSchema(kinesisServiceMethods.ByName("TagResource")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceUntagResourceHandler := connect.NewUnaryHandler(
		KinesisServiceUntagResourceProcedure,
		svc.UntagResource,
		connect.WithSchema(kinesisServiceMethods.ByName("UntagResource")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceUpdateAccountSettingsHandler := connect.NewUnaryHandler(
		KinesisServiceUpdateAccountSettingsProcedure,
		svc.UpdateAccountSettings,
		connect.WithSchema(kinesisServiceMethods.ByName("UpdateAccountSettings")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceUpdateMaxRecordSizeHandler := connect.NewUnaryHandler(
		KinesisServiceUpdateMaxRecordSizeProcedure,
		svc.UpdateMaxRecordSize,
		connect.WithSchema(kinesisServiceMethods.ByName("UpdateMaxRecordSize")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceUpdateShardCountHandler := connect.NewUnaryHandler(
		KinesisServiceUpdateShardCountProcedure,
		svc.UpdateShardCount,
		connect.WithSchema(kinesisServiceMethods.ByName("UpdateShardCount")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceUpdateStreamModeHandler := connect.NewUnaryHandler(
		KinesisServiceUpdateStreamModeProcedure,
		svc.UpdateStreamMode,
		connect.WithSchema(kinesisServiceMethods.ByName("UpdateStreamMode")),
		connect.WithHandlerOptions(opts...),
	)
	kinesisServiceUpdateStreamWarmThroughputHandler := connect.NewUnaryHandler(
		KinesisServiceUpdateStreamWarmThroughputProcedure,
		svc.UpdateStreamWarmThroughput,
		connect.WithSchema(kinesisServiceMethods.ByName("UpdateStreamWarmThroughput")),
		connect.WithHandlerOptions(opts...),
	)
	return "/kinesis.KinesisService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case KinesisServiceAddTagsToStreamProcedure:
			kinesisServiceAddTagsToStreamHandler.ServeHTTP(w, r)
		case KinesisServiceCreateStreamProcedure:
			kinesisServiceCreateStreamHandler.ServeHTTP(w, r)
		case KinesisServiceDecreaseStreamRetentionPeriodProcedure:
			kinesisServiceDecreaseStreamRetentionPeriodHandler.ServeHTTP(w, r)
		case KinesisServiceDeleteResourcePolicyProcedure:
			kinesisServiceDeleteResourcePolicyHandler.ServeHTTP(w, r)
		case KinesisServiceDeleteStreamProcedure:
			kinesisServiceDeleteStreamHandler.ServeHTTP(w, r)
		case KinesisServiceDeregisterStreamConsumerProcedure:
			kinesisServiceDeregisterStreamConsumerHandler.ServeHTTP(w, r)
		case KinesisServiceDescribeAccountSettingsProcedure:
			kinesisServiceDescribeAccountSettingsHandler.ServeHTTP(w, r)
		case KinesisServiceDescribeLimitsProcedure:
			kinesisServiceDescribeLimitsHandler.ServeHTTP(w, r)
		case KinesisServiceDescribeStreamProcedure:
			kinesisServiceDescribeStreamHandler.ServeHTTP(w, r)
		case KinesisServiceDescribeStreamConsumerProcedure:
			kinesisServiceDescribeStreamConsumerHandler.ServeHTTP(w, r)
		case KinesisServiceDescribeStreamSummaryProcedure:
			kinesisServiceDescribeStreamSummaryHandler.ServeHTTP(w, r)
		case KinesisServiceDisableEnhancedMonitoringProcedure:
			kinesisServiceDisableEnhancedMonitoringHandler.ServeHTTP(w, r)
		case KinesisServiceEnableEnhancedMonitoringProcedure:
			kinesisServiceEnableEnhancedMonitoringHandler.ServeHTTP(w, r)
		case KinesisServiceGetRecordsProcedure:
			kinesisServiceGetRecordsHandler.ServeHTTP(w, r)
		case KinesisServiceGetResourcePolicyProcedure:
			kinesisServiceGetResourcePolicyHandler.ServeHTTP(w, r)
		case KinesisServiceGetShardIteratorProcedure:
			kinesisServiceGetShardIteratorHandler.ServeHTTP(w, r)
		case KinesisServiceIncreaseStreamRetentionPeriodProcedure:
			kinesisServiceIncreaseStreamRetentionPeriodHandler.ServeHTTP(w, r)
		case KinesisServiceListShardsProcedure:
			kinesisServiceListShardsHandler.ServeHTTP(w, r)
		case KinesisServiceListStreamConsumersProcedure:
			kinesisServiceListStreamConsumersHandler.ServeHTTP(w, r)
		case KinesisServiceListStreamsProcedure:
			kinesisServiceListStreamsHandler.ServeHTTP(w, r)
		case KinesisServiceListTagsForResourceProcedure:
			kinesisServiceListTagsForResourceHandler.ServeHTTP(w, r)
		case KinesisServiceListTagsForStreamProcedure:
			kinesisServiceListTagsForStreamHandler.ServeHTTP(w, r)
		case KinesisServiceMergeShardsProcedure:
			kinesisServiceMergeShardsHandler.ServeHTTP(w, r)
		case KinesisServicePutRecordProcedure:
			kinesisServicePutRecordHandler.ServeHTTP(w, r)
		case KinesisServicePutRecordsProcedure:
			kinesisServicePutRecordsHandler.ServeHTTP(w, r)
		case KinesisServicePutResourcePolicyProcedure:
			kinesisServicePutResourcePolicyHandler.ServeHTTP(w, r)
		case KinesisServiceRegisterStreamConsumerProcedure:
			kinesisServiceRegisterStreamConsumerHandler.ServeHTTP(w, r)
		case KinesisServiceRemoveTagsFromStreamProcedure:
			kinesisServiceRemoveTagsFromStreamHandler.ServeHTTP(w, r)
		case KinesisServiceSplitShardProcedure:
			kinesisServiceSplitShardHandler.ServeHTTP(w, r)
		case KinesisServiceStartStreamEncryptionProcedure:
			kinesisServiceStartStreamEncryptionHandler.ServeHTTP(w, r)
		case KinesisServiceStopStreamEncryptionProcedure:
			kinesisServiceStopStreamEncryptionHandler.ServeHTTP(w, r)
		case KinesisServiceSubscribeToShardProcedure:
			kinesisServiceSubscribeToShardHandler.ServeHTTP(w, r)
		case KinesisServiceTagResourceProcedure:
			kinesisServiceTagResourceHandler.ServeHTTP(w, r)
		case KinesisServiceUntagResourceProcedure:
			kinesisServiceUntagResourceHandler.ServeHTTP(w, r)
		case KinesisServiceUpdateAccountSettingsProcedure:
			kinesisServiceUpdateAccountSettingsHandler.ServeHTTP(w, r)
		case KinesisServiceUpdateMaxRecordSizeProcedure:
			kinesisServiceUpdateMaxRecordSizeHandler.ServeHTTP(w, r)
		case KinesisServiceUpdateShardCountProcedure:
			kinesisServiceUpdateShardCountHandler.ServeHTTP(w, r)
		case KinesisServiceUpdateStreamModeProcedure:
			kinesisServiceUpdateStreamModeHandler.ServeHTTP(w, r)
		case KinesisServiceUpdateStreamWarmThroughputProcedure:
			kinesisServiceUpdateStreamWarmThroughputHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedKinesisServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedKinesisServiceHandler struct{}

func (UnimplementedKinesisServiceHandler) AddTagsToStream(context.Context, *connect.Request[kinesis.AddTagsToStreamInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.AddTagsToStream is not implemented"))
}

func (UnimplementedKinesisServiceHandler) CreateStream(context.Context, *connect.Request[kinesis.CreateStreamInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.CreateStream is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DecreaseStreamRetentionPeriod(context.Context, *connect.Request[kinesis.DecreaseStreamRetentionPeriodInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DecreaseStreamRetentionPeriod is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DeleteResourcePolicy(context.Context, *connect.Request[kinesis.DeleteResourcePolicyInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DeleteResourcePolicy is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DeleteStream(context.Context, *connect.Request[kinesis.DeleteStreamInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DeleteStream is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DeregisterStreamConsumer(context.Context, *connect.Request[kinesis.DeregisterStreamConsumerInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DeregisterStreamConsumer is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DescribeAccountSettings(context.Context, *connect.Request[kinesis.DescribeAccountSettingsInput]) (*connect.Response[kinesis.DescribeAccountSettingsOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DescribeAccountSettings is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DescribeLimits(context.Context, *connect.Request[kinesis.DescribeLimitsInput]) (*connect.Response[kinesis.DescribeLimitsOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DescribeLimits is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DescribeStream(context.Context, *connect.Request[kinesis.DescribeStreamInput]) (*connect.Response[kinesis.DescribeStreamOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DescribeStream is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DescribeStreamConsumer(context.Context, *connect.Request[kinesis.DescribeStreamConsumerInput]) (*connect.Response[kinesis.DescribeStreamConsumerOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DescribeStreamConsumer is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DescribeStreamSummary(context.Context, *connect.Request[kinesis.DescribeStreamSummaryInput]) (*connect.Response[kinesis.DescribeStreamSummaryOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DescribeStreamSummary is not implemented"))
}

func (UnimplementedKinesisServiceHandler) DisableEnhancedMonitoring(context.Context, *connect.Request[kinesis.DisableEnhancedMonitoringInput]) (*connect.Response[kinesis.EnhancedMonitoringOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.DisableEnhancedMonitoring is not implemented"))
}

func (UnimplementedKinesisServiceHandler) EnableEnhancedMonitoring(context.Context, *connect.Request[kinesis.EnableEnhancedMonitoringInput]) (*connect.Response[kinesis.EnhancedMonitoringOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.EnableEnhancedMonitoring is not implemented"))
}

func (UnimplementedKinesisServiceHandler) GetRecords(context.Context, *connect.Request[kinesis.GetRecordsInput]) (*connect.Response[kinesis.GetRecordsOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.GetRecords is not implemented"))
}

func (UnimplementedKinesisServiceHandler) GetResourcePolicy(context.Context, *connect.Request[kinesis.GetResourcePolicyInput]) (*connect.Response[kinesis.GetResourcePolicyOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.GetResourcePolicy is not implemented"))
}

func (UnimplementedKinesisServiceHandler) GetShardIterator(context.Context, *connect.Request[kinesis.GetShardIteratorInput]) (*connect.Response[kinesis.GetShardIteratorOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.GetShardIterator is not implemented"))
}

func (UnimplementedKinesisServiceHandler) IncreaseStreamRetentionPeriod(context.Context, *connect.Request[kinesis.IncreaseStreamRetentionPeriodInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.IncreaseStreamRetentionPeriod is not implemented"))
}

func (UnimplementedKinesisServiceHandler) ListShards(context.Context, *connect.Request[kinesis.ListShardsInput]) (*connect.Response[kinesis.ListShardsOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.ListShards is not implemented"))
}

func (UnimplementedKinesisServiceHandler) ListStreamConsumers(context.Context, *connect.Request[kinesis.ListStreamConsumersInput]) (*connect.Response[kinesis.ListStreamConsumersOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.ListStreamConsumers is not implemented"))
}

func (UnimplementedKinesisServiceHandler) ListStreams(context.Context, *connect.Request[kinesis.ListStreamsInput]) (*connect.Response[kinesis.ListStreamsOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.ListStreams is not implemented"))
}

func (UnimplementedKinesisServiceHandler) ListTagsForResource(context.Context, *connect.Request[kinesis.ListTagsForResourceInput]) (*connect.Response[kinesis.ListTagsForResourceOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.ListTagsForResource is not implemented"))
}

func (UnimplementedKinesisServiceHandler) ListTagsForStream(context.Context, *connect.Request[kinesis.ListTagsForStreamInput]) (*connect.Response[kinesis.ListTagsForStreamOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.ListTagsForStream is not implemented"))
}

func (UnimplementedKinesisServiceHandler) MergeShards(context.Context, *connect.Request[kinesis.MergeShardsInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.MergeShards is not implemented"))
}

func (UnimplementedKinesisServiceHandler) PutRecord(context.Context, *connect.Request[kinesis.PutRecordInput]) (*connect.Response[kinesis.PutRecordOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.PutRecord is not implemented"))
}

func (UnimplementedKinesisServiceHandler) PutRecords(context.Context, *connect.Request[kinesis.PutRecordsInput]) (*connect.Response[kinesis.PutRecordsOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.PutRecords is not implemented"))
}

func (UnimplementedKinesisServiceHandler) PutResourcePolicy(context.Context, *connect.Request[kinesis.PutResourcePolicyInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.PutResourcePolicy is not implemented"))
}

func (UnimplementedKinesisServiceHandler) RegisterStreamConsumer(context.Context, *connect.Request[kinesis.RegisterStreamConsumerInput]) (*connect.Response[kinesis.RegisterStreamConsumerOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.RegisterStreamConsumer is not implemented"))
}

func (UnimplementedKinesisServiceHandler) RemoveTagsFromStream(context.Context, *connect.Request[kinesis.RemoveTagsFromStreamInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.RemoveTagsFromStream is not implemented"))
}

func (UnimplementedKinesisServiceHandler) SplitShard(context.Context, *connect.Request[kinesis.SplitShardInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.SplitShard is not implemented"))
}

func (UnimplementedKinesisServiceHandler) StartStreamEncryption(context.Context, *connect.Request[kinesis.StartStreamEncryptionInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.StartStreamEncryption is not implemented"))
}

func (UnimplementedKinesisServiceHandler) StopStreamEncryption(context.Context, *connect.Request[kinesis.StopStreamEncryptionInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.StopStreamEncryption is not implemented"))
}

func (UnimplementedKinesisServiceHandler) SubscribeToShard(context.Context, *connect.Request[kinesis.SubscribeToShardInput]) (*connect.Response[kinesis.SubscribeToShardOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.SubscribeToShard is not implemented"))
}

func (UnimplementedKinesisServiceHandler) TagResource(context.Context, *connect.Request[kinesis.TagResourceInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.TagResource is not implemented"))
}

func (UnimplementedKinesisServiceHandler) UntagResource(context.Context, *connect.Request[kinesis.UntagResourceInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.UntagResource is not implemented"))
}

func (UnimplementedKinesisServiceHandler) UpdateAccountSettings(context.Context, *connect.Request[kinesis.UpdateAccountSettingsInput]) (*connect.Response[kinesis.UpdateAccountSettingsOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.UpdateAccountSettings is not implemented"))
}

func (UnimplementedKinesisServiceHandler) UpdateMaxRecordSize(context.Context, *connect.Request[kinesis.UpdateMaxRecordSizeInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.UpdateMaxRecordSize is not implemented"))
}

func (UnimplementedKinesisServiceHandler) UpdateShardCount(context.Context, *connect.Request[kinesis.UpdateShardCountInput]) (*connect.Response[kinesis.UpdateShardCountOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.UpdateShardCount is not implemented"))
}

func (UnimplementedKinesisServiceHandler) UpdateStreamMode(context.Context, *connect.Request[kinesis.UpdateStreamModeInput]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.UpdateStreamMode is not implemented"))
}

func (UnimplementedKinesisServiceHandler) UpdateStreamWarmThroughput(context.Context, *connect.Request[kinesis.UpdateStreamWarmThroughputInput]) (*connect.Response[kinesis.UpdateStreamWarmThroughputOutput], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kinesis.KinesisService.UpdateStreamWarmThroughput is not implemented"))
}
