// Code generated by proto_generator. DO NOT EDIT.
// source: secretsmanager

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: secretsmanager.proto

package secretsmanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "vorpalstacks/internal/pb/aws/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretsManagerService_BatchGetSecretValue_FullMethodName          = "/secretsmanager.SecretsManagerService/BatchGetSecretValue"
	SecretsManagerService_CancelRotateSecret_FullMethodName           = "/secretsmanager.SecretsManagerService/CancelRotateSecret"
	SecretsManagerService_CreateSecret_FullMethodName                 = "/secretsmanager.SecretsManagerService/CreateSecret"
	SecretsManagerService_DeleteResourcePolicy_FullMethodName         = "/secretsmanager.SecretsManagerService/DeleteResourcePolicy"
	SecretsManagerService_DeleteSecret_FullMethodName                 = "/secretsmanager.SecretsManagerService/DeleteSecret"
	SecretsManagerService_DescribeSecret_FullMethodName               = "/secretsmanager.SecretsManagerService/DescribeSecret"
	SecretsManagerService_GetRandomPassword_FullMethodName            = "/secretsmanager.SecretsManagerService/GetRandomPassword"
	SecretsManagerService_GetResourcePolicy_FullMethodName            = "/secretsmanager.SecretsManagerService/GetResourcePolicy"
	SecretsManagerService_GetSecretValue_FullMethodName               = "/secretsmanager.SecretsManagerService/GetSecretValue"
	SecretsManagerService_ListSecrets_FullMethodName                  = "/secretsmanager.SecretsManagerService/ListSecrets"
	SecretsManagerService_ListSecretVersionIds_FullMethodName         = "/secretsmanager.SecretsManagerService/ListSecretVersionIds"
	SecretsManagerService_PutResourcePolicy_FullMethodName            = "/secretsmanager.SecretsManagerService/PutResourcePolicy"
	SecretsManagerService_PutSecretValue_FullMethodName               = "/secretsmanager.SecretsManagerService/PutSecretValue"
	SecretsManagerService_RemoveRegionsFromReplication_FullMethodName = "/secretsmanager.SecretsManagerService/RemoveRegionsFromReplication"
	SecretsManagerService_ReplicateSecretToRegions_FullMethodName     = "/secretsmanager.SecretsManagerService/ReplicateSecretToRegions"
	SecretsManagerService_RestoreSecret_FullMethodName                = "/secretsmanager.SecretsManagerService/RestoreSecret"
	SecretsManagerService_RotateSecret_FullMethodName                 = "/secretsmanager.SecretsManagerService/RotateSecret"
	SecretsManagerService_StopReplicationToReplica_FullMethodName     = "/secretsmanager.SecretsManagerService/StopReplicationToReplica"
	SecretsManagerService_TagResource_FullMethodName                  = "/secretsmanager.SecretsManagerService/TagResource"
	SecretsManagerService_UntagResource_FullMethodName                = "/secretsmanager.SecretsManagerService/UntagResource"
	SecretsManagerService_UpdateSecret_FullMethodName                 = "/secretsmanager.SecretsManagerService/UpdateSecret"
	SecretsManagerService_UpdateSecretVersionStage_FullMethodName     = "/secretsmanager.SecretsManagerService/UpdateSecretVersionStage"
	SecretsManagerService_ValidateResourcePolicy_FullMethodName       = "/secretsmanager.SecretsManagerService/ValidateResourcePolicy"
)

// SecretsManagerServiceClient is the client API for SecretsManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretsManagerService provides secretsmanager API operations.
type SecretsManagerServiceClient interface {
	// Retrieves the contents of the encrypted fields SecretString or SecretBinary for up to 20 secrets. To retrieve a single secret, call GetSecretValue. To choose which secrets to retrieve, you can spec...
	// HTTP:
	// Protocol: awsJson1_1
	BatchGetSecretValue(ctx context.Context, in *BatchGetSecretValueRequest, opts ...grpc.CallOption) (*BatchGetSecretValueResponse, error)
	// Turns off automatic rotation, and if a rotation is currently in progress, cancels the rotation. If you cancel a rotation in progress, it can leave the VersionStage labels in an unexpected state. Yo...
	// HTTP:
	// Protocol: awsJson1_1
	CancelRotateSecret(ctx context.Context, in *CancelRotateSecretRequest, opts ...grpc.CallOption) (*CancelRotateSecretResponse, error)
	// Creates a new secret. A secret can be a password, a set of credentials such as a user name and password, an OAuth token, or other secret information that you store in an encrypted form in Secrets M...
	// HTTP:
	// Protocol: awsJson1_1
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error)
	// Deletes the resource-based permission policy attached to the secret. To attach a policy to a secret, use PutResourcePolicy. Secrets Manager generates a CloudTrail log entry when you call this actio...
	// HTTP:
	// Protocol: awsJson1_1
	DeleteResourcePolicy(ctx context.Context, in *DeleteResourcePolicyRequest, opts ...grpc.CallOption) (*DeleteResourcePolicyResponse, error)
	// Deletes a secret and all of its versions. You can specify a recovery window during which you can restore the secret. The minimum recovery window is 7 days. The default recovery window is 30 days. S...
	// HTTP:
	// Protocol: awsJson1_1
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
	// Retrieves the details of a secret. It does not include the encrypted secret value. Secrets Manager only returns fields that have a value in the response. Secrets Manager generates a CloudTrail log ...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeSecret(ctx context.Context, in *DescribeSecretRequest, opts ...grpc.CallOption) (*DescribeSecretResponse, error)
	// Generates a random password. We recommend that you specify the maximum length and include every character type that the system you are generating a password for can support. By default, Secrets Man...
	// HTTP:
	// Protocol: awsJson1_1
	GetRandomPassword(ctx context.Context, in *GetRandomPasswordRequest, opts ...grpc.CallOption) (*GetRandomPasswordResponse, error)
	// Retrieves the JSON text of the resource-based policy document attached to the secret. For more information about permissions policies attached to a secret, see Permissions policies attached to a se...
	// HTTP:
	// Protocol: awsJson1_1
	GetResourcePolicy(ctx context.Context, in *GetResourcePolicyRequest, opts ...grpc.CallOption) (*GetResourcePolicyResponse, error)
	// Retrieves the contents of the encrypted fields SecretString or SecretBinary from the specified version of a secret, whichever contains content. To retrieve the values for a group of secrets, call B...
	// HTTP:
	// Protocol: awsJson1_1
	GetSecretValue(ctx context.Context, in *GetSecretValueRequest, opts ...grpc.CallOption) (*GetSecretValueResponse, error)
	// Lists the secrets that are stored by Secrets Manager in the Amazon Web Services account, not including secrets that are marked for deletion. To see secrets marked for deletion, use the Secrets Mana...
	// HTTP:
	// Protocol: awsJson1_1
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
	// Lists the versions of a secret. Secrets Manager uses staging labels to indicate the different versions of a secret. For more information, see Secrets Manager concepts: Versions. To list the secrets...
	// HTTP:
	// Protocol: awsJson1_1
	ListSecretVersionIds(ctx context.Context, in *ListSecretVersionIdsRequest, opts ...grpc.CallOption) (*ListSecretVersionIdsResponse, error)
	// Attaches a resource-based permission policy to a secret. A resource-based policy is optional. For more information, see Authentication and access control for Secrets Manager For information about a...
	// HTTP:
	// Protocol: awsJson1_1
	PutResourcePolicy(ctx context.Context, in *PutResourcePolicyRequest, opts ...grpc.CallOption) (*PutResourcePolicyResponse, error)
	// Creates a new version of your secret by creating a new encrypted value and attaching it to the secret. version can contain a new SecretString value or a new SecretBinary value. Do not call PutSecre...
	// HTTP:
	// Protocol: awsJson1_1
	PutSecretValue(ctx context.Context, in *PutSecretValueRequest, opts ...grpc.CallOption) (*PutSecretValueResponse, error)
	// For a secret that is replicated to other Regions, deletes the secret replicas from the Regions you specify. Secrets Manager generates a CloudTrail log entry when you call this action. Do not includ...
	// HTTP:
	// Protocol: awsJson1_1
	RemoveRegionsFromReplication(ctx context.Context, in *RemoveRegionsFromReplicationRequest, opts ...grpc.CallOption) (*RemoveRegionsFromReplicationResponse, error)
	// Replicates the secret to a new Regions. See Multi-Region secrets. Secrets Manager generates a CloudTrail log entry when you call this action. Do not include sensitive information in request paramet...
	// HTTP:
	// Protocol: awsJson1_1
	ReplicateSecretToRegions(ctx context.Context, in *ReplicateSecretToRegionsRequest, opts ...grpc.CallOption) (*ReplicateSecretToRegionsResponse, error)
	// Cancels the scheduled deletion of a secret by removing the DeletedDate time stamp. You can access a secret again after it has been restored. Secrets Manager generates a CloudTrail log entry when yo...
	// HTTP:
	// Protocol: awsJson1_1
	RestoreSecret(ctx context.Context, in *RestoreSecretRequest, opts ...grpc.CallOption) (*RestoreSecretResponse, error)
	// Configures and starts the asynchronous process of rotating the secret. For information about rotation, see Rotate secrets in the Secrets Manager User Guide. If you include the configuration paramet...
	// HTTP:
	// Protocol: awsJson1_1
	RotateSecret(ctx context.Context, in *RotateSecretRequest, opts ...grpc.CallOption) (*RotateSecretResponse, error)
	// Removes the link between the replica secret and the primary secret and promotes the replica to a primary secret in the replica Region. You must call this operation from the Region in which you want...
	// HTTP:
	// Protocol: awsJson1_1
	StopReplicationToReplica(ctx context.Context, in *StopReplicationToReplicaRequest, opts ...grpc.CallOption) (*StopReplicationToReplicaResponse, error)
	// Attaches tags to a secret. Tags consist of a key name and a value. Tags are part of the secret's metadata. They are not associated with specific versions of the secret. This operation appends tags ...
	// HTTP:
	// Protocol: awsJson1_1
	TagResource(ctx context.Context, in *TagResourceRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// Removes specific tags from a secret. This operation is idempotent. If a requested tag is not attached to the secret, no error is returned and the secret metadata is unchanged. If you use tags as pa...
	// HTTP:
	// Protocol: awsJson1_1
	UntagResource(ctx context.Context, in *UntagResourceRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// Modifies the details of a secret, including metadata and the secret value. To change the secret value, you can also use PutSecretValue. To change the rotation configuration of a secret, use RotateS...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error)
	// Modifies the staging labels attached to a version of a secret. Secrets Manager uses staging labels to track a version as it progresses through the secret rotation process. Each staging label can be...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateSecretVersionStage(ctx context.Context, in *UpdateSecretVersionStageRequest, opts ...grpc.CallOption) (*UpdateSecretVersionStageResponse, error)
	// Validates that a resource policy does not grant a wide range of principals access to your secret. A resource-based policy is optional for secrets. The API performs three checks when validating the ...
	// HTTP:
	// Protocol: awsJson1_1
	ValidateResourcePolicy(ctx context.Context, in *ValidateResourcePolicyRequest, opts ...grpc.CallOption) (*ValidateResourcePolicyResponse, error)
}

type secretsManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsManagerServiceClient(cc grpc.ClientConnInterface) SecretsManagerServiceClient {
	return &secretsManagerServiceClient{cc}
}

func (c *secretsManagerServiceClient) BatchGetSecretValue(ctx context.Context, in *BatchGetSecretValueRequest, opts ...grpc.CallOption) (*BatchGetSecretValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetSecretValueResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_BatchGetSecretValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) CancelRotateSecret(ctx context.Context, in *CancelRotateSecretRequest, opts ...grpc.CallOption) (*CancelRotateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRotateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_CancelRotateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) DeleteResourcePolicy(ctx context.Context, in *DeleteResourcePolicyRequest, opts ...grpc.CallOption) (*DeleteResourcePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourcePolicyResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_DeleteResourcePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) DescribeSecret(ctx context.Context, in *DescribeSecretRequest, opts ...grpc.CallOption) (*DescribeSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeSecretResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_DescribeSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) GetRandomPassword(ctx context.Context, in *GetRandomPasswordRequest, opts ...grpc.CallOption) (*GetRandomPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRandomPasswordResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_GetRandomPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) GetResourcePolicy(ctx context.Context, in *GetResourcePolicyRequest, opts ...grpc.CallOption) (*GetResourcePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourcePolicyResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_GetResourcePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) GetSecretValue(ctx context.Context, in *GetSecretValueRequest, opts ...grpc.CallOption) (*GetSecretValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretValueResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_GetSecretValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) ListSecretVersionIds(ctx context.Context, in *ListSecretVersionIdsRequest, opts ...grpc.CallOption) (*ListSecretVersionIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretVersionIdsResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_ListSecretVersionIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) PutResourcePolicy(ctx context.Context, in *PutResourcePolicyRequest, opts ...grpc.CallOption) (*PutResourcePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResourcePolicyResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_PutResourcePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) PutSecretValue(ctx context.Context, in *PutSecretValueRequest, opts ...grpc.CallOption) (*PutSecretValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutSecretValueResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_PutSecretValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) RemoveRegionsFromReplication(ctx context.Context, in *RemoveRegionsFromReplicationRequest, opts ...grpc.CallOption) (*RemoveRegionsFromReplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRegionsFromReplicationResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_RemoveRegionsFromReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) ReplicateSecretToRegions(ctx context.Context, in *ReplicateSecretToRegionsRequest, opts ...grpc.CallOption) (*ReplicateSecretToRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateSecretToRegionsResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_ReplicateSecretToRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) RestoreSecret(ctx context.Context, in *RestoreSecretRequest, opts ...grpc.CallOption) (*RestoreSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSecretResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_RestoreSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) RotateSecret(ctx context.Context, in *RotateSecretRequest, opts ...grpc.CallOption) (*RotateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_RotateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) StopReplicationToReplica(ctx context.Context, in *StopReplicationToReplicaRequest, opts ...grpc.CallOption) (*StopReplicationToReplicaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopReplicationToReplicaResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_StopReplicationToReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) TagResource(ctx context.Context, in *TagResourceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, SecretsManagerService_TagResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) UntagResource(ctx context.Context, in *UntagResourceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, SecretsManagerService_UntagResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_UpdateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) UpdateSecretVersionStage(ctx context.Context, in *UpdateSecretVersionStageRequest, opts ...grpc.CallOption) (*UpdateSecretVersionStageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretVersionStageResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_UpdateSecretVersionStage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsManagerServiceClient) ValidateResourcePolicy(ctx context.Context, in *ValidateResourcePolicyRequest, opts ...grpc.CallOption) (*ValidateResourcePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResourcePolicyResponse)
	err := c.cc.Invoke(ctx, SecretsManagerService_ValidateResourcePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsManagerServiceServer is the server API for SecretsManagerService service.
// All implementations must embed UnimplementedSecretsManagerServiceServer
// for forward compatibility.
//
// SecretsManagerService provides secretsmanager API operations.
type SecretsManagerServiceServer interface {
	// Retrieves the contents of the encrypted fields SecretString or SecretBinary for up to 20 secrets. To retrieve a single secret, call GetSecretValue. To choose which secrets to retrieve, you can spec...
	// HTTP:
	// Protocol: awsJson1_1
	BatchGetSecretValue(context.Context, *BatchGetSecretValueRequest) (*BatchGetSecretValueResponse, error)
	// Turns off automatic rotation, and if a rotation is currently in progress, cancels the rotation. If you cancel a rotation in progress, it can leave the VersionStage labels in an unexpected state. Yo...
	// HTTP:
	// Protocol: awsJson1_1
	CancelRotateSecret(context.Context, *CancelRotateSecretRequest) (*CancelRotateSecretResponse, error)
	// Creates a new secret. A secret can be a password, a set of credentials such as a user name and password, an OAuth token, or other secret information that you store in an encrypted form in Secrets M...
	// HTTP:
	// Protocol: awsJson1_1
	CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error)
	// Deletes the resource-based permission policy attached to the secret. To attach a policy to a secret, use PutResourcePolicy. Secrets Manager generates a CloudTrail log entry when you call this actio...
	// HTTP:
	// Protocol: awsJson1_1
	DeleteResourcePolicy(context.Context, *DeleteResourcePolicyRequest) (*DeleteResourcePolicyResponse, error)
	// Deletes a secret and all of its versions. You can specify a recovery window during which you can restore the secret. The minimum recovery window is 7 days. The default recovery window is 30 days. S...
	// HTTP:
	// Protocol: awsJson1_1
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
	// Retrieves the details of a secret. It does not include the encrypted secret value. Secrets Manager only returns fields that have a value in the response. Secrets Manager generates a CloudTrail log ...
	// HTTP:
	// Protocol: awsJson1_1
	DescribeSecret(context.Context, *DescribeSecretRequest) (*DescribeSecretResponse, error)
	// Generates a random password. We recommend that you specify the maximum length and include every character type that the system you are generating a password for can support. By default, Secrets Man...
	// HTTP:
	// Protocol: awsJson1_1
	GetRandomPassword(context.Context, *GetRandomPasswordRequest) (*GetRandomPasswordResponse, error)
	// Retrieves the JSON text of the resource-based policy document attached to the secret. For more information about permissions policies attached to a secret, see Permissions policies attached to a se...
	// HTTP:
	// Protocol: awsJson1_1
	GetResourcePolicy(context.Context, *GetResourcePolicyRequest) (*GetResourcePolicyResponse, error)
	// Retrieves the contents of the encrypted fields SecretString or SecretBinary from the specified version of a secret, whichever contains content. To retrieve the values for a group of secrets, call B...
	// HTTP:
	// Protocol: awsJson1_1
	GetSecretValue(context.Context, *GetSecretValueRequest) (*GetSecretValueResponse, error)
	// Lists the secrets that are stored by Secrets Manager in the Amazon Web Services account, not including secrets that are marked for deletion. To see secrets marked for deletion, use the Secrets Mana...
	// HTTP:
	// Protocol: awsJson1_1
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	// Lists the versions of a secret. Secrets Manager uses staging labels to indicate the different versions of a secret. For more information, see Secrets Manager concepts: Versions. To list the secrets...
	// HTTP:
	// Protocol: awsJson1_1
	ListSecretVersionIds(context.Context, *ListSecretVersionIdsRequest) (*ListSecretVersionIdsResponse, error)
	// Attaches a resource-based permission policy to a secret. A resource-based policy is optional. For more information, see Authentication and access control for Secrets Manager For information about a...
	// HTTP:
	// Protocol: awsJson1_1
	PutResourcePolicy(context.Context, *PutResourcePolicyRequest) (*PutResourcePolicyResponse, error)
	// Creates a new version of your secret by creating a new encrypted value and attaching it to the secret. version can contain a new SecretString value or a new SecretBinary value. Do not call PutSecre...
	// HTTP:
	// Protocol: awsJson1_1
	PutSecretValue(context.Context, *PutSecretValueRequest) (*PutSecretValueResponse, error)
	// For a secret that is replicated to other Regions, deletes the secret replicas from the Regions you specify. Secrets Manager generates a CloudTrail log entry when you call this action. Do not includ...
	// HTTP:
	// Protocol: awsJson1_1
	RemoveRegionsFromReplication(context.Context, *RemoveRegionsFromReplicationRequest) (*RemoveRegionsFromReplicationResponse, error)
	// Replicates the secret to a new Regions. See Multi-Region secrets. Secrets Manager generates a CloudTrail log entry when you call this action. Do not include sensitive information in request paramet...
	// HTTP:
	// Protocol: awsJson1_1
	ReplicateSecretToRegions(context.Context, *ReplicateSecretToRegionsRequest) (*ReplicateSecretToRegionsResponse, error)
	// Cancels the scheduled deletion of a secret by removing the DeletedDate time stamp. You can access a secret again after it has been restored. Secrets Manager generates a CloudTrail log entry when yo...
	// HTTP:
	// Protocol: awsJson1_1
	RestoreSecret(context.Context, *RestoreSecretRequest) (*RestoreSecretResponse, error)
	// Configures and starts the asynchronous process of rotating the secret. For information about rotation, see Rotate secrets in the Secrets Manager User Guide. If you include the configuration paramet...
	// HTTP:
	// Protocol: awsJson1_1
	RotateSecret(context.Context, *RotateSecretRequest) (*RotateSecretResponse, error)
	// Removes the link between the replica secret and the primary secret and promotes the replica to a primary secret in the replica Region. You must call this operation from the Region in which you want...
	// HTTP:
	// Protocol: awsJson1_1
	StopReplicationToReplica(context.Context, *StopReplicationToReplicaRequest) (*StopReplicationToReplicaResponse, error)
	// Attaches tags to a secret. Tags consist of a key name and a value. Tags are part of the secret's metadata. They are not associated with specific versions of the secret. This operation appends tags ...
	// HTTP:
	// Protocol: awsJson1_1
	TagResource(context.Context, *TagResourceRequest) (*common.Empty, error)
	// Removes specific tags from a secret. This operation is idempotent. If a requested tag is not attached to the secret, no error is returned and the secret metadata is unchanged. If you use tags as pa...
	// HTTP:
	// Protocol: awsJson1_1
	UntagResource(context.Context, *UntagResourceRequest) (*common.Empty, error)
	// Modifies the details of a secret, including metadata and the secret value. To change the secret value, you can also use PutSecretValue. To change the rotation configuration of a secret, use RotateS...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error)
	// Modifies the staging labels attached to a version of a secret. Secrets Manager uses staging labels to track a version as it progresses through the secret rotation process. Each staging label can be...
	// HTTP:
	// Protocol: awsJson1_1
	UpdateSecretVersionStage(context.Context, *UpdateSecretVersionStageRequest) (*UpdateSecretVersionStageResponse, error)
	// Validates that a resource policy does not grant a wide range of principals access to your secret. A resource-based policy is optional for secrets. The API performs three checks when validating the ...
	// HTTP:
	// Protocol: awsJson1_1
	ValidateResourcePolicy(context.Context, *ValidateResourcePolicyRequest) (*ValidateResourcePolicyResponse, error)
	mustEmbedUnimplementedSecretsManagerServiceServer()
}

// UnimplementedSecretsManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsManagerServiceServer struct{}

func (UnimplementedSecretsManagerServiceServer) BatchGetSecretValue(context.Context, *BatchGetSecretValueRequest) (*BatchGetSecretValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetSecretValue not implemented")
}
func (UnimplementedSecretsManagerServiceServer) CancelRotateSecret(context.Context, *CancelRotateSecretRequest) (*CancelRotateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRotateSecret not implemented")
}
func (UnimplementedSecretsManagerServiceServer) CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedSecretsManagerServiceServer) DeleteResourcePolicy(context.Context, *DeleteResourcePolicyRequest) (*DeleteResourcePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResourcePolicy not implemented")
}
func (UnimplementedSecretsManagerServiceServer) DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedSecretsManagerServiceServer) DescribeSecret(context.Context, *DescribeSecretRequest) (*DescribeSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeSecret not implemented")
}
func (UnimplementedSecretsManagerServiceServer) GetRandomPassword(context.Context, *GetRandomPasswordRequest) (*GetRandomPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRandomPassword not implemented")
}
func (UnimplementedSecretsManagerServiceServer) GetResourcePolicy(context.Context, *GetResourcePolicyRequest) (*GetResourcePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResourcePolicy not implemented")
}
func (UnimplementedSecretsManagerServiceServer) GetSecretValue(context.Context, *GetSecretValueRequest) (*GetSecretValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecretValue not implemented")
}
func (UnimplementedSecretsManagerServiceServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedSecretsManagerServiceServer) ListSecretVersionIds(context.Context, *ListSecretVersionIdsRequest) (*ListSecretVersionIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecretVersionIds not implemented")
}
func (UnimplementedSecretsManagerServiceServer) PutResourcePolicy(context.Context, *PutResourcePolicyRequest) (*PutResourcePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutResourcePolicy not implemented")
}
func (UnimplementedSecretsManagerServiceServer) PutSecretValue(context.Context, *PutSecretValueRequest) (*PutSecretValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutSecretValue not implemented")
}
func (UnimplementedSecretsManagerServiceServer) RemoveRegionsFromReplication(context.Context, *RemoveRegionsFromReplicationRequest) (*RemoveRegionsFromReplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRegionsFromReplication not implemented")
}
func (UnimplementedSecretsManagerServiceServer) ReplicateSecretToRegions(context.Context, *ReplicateSecretToRegionsRequest) (*ReplicateSecretToRegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateSecretToRegions not implemented")
}
func (UnimplementedSecretsManagerServiceServer) RestoreSecret(context.Context, *RestoreSecretRequest) (*RestoreSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSecret not implemented")
}
func (UnimplementedSecretsManagerServiceServer) RotateSecret(context.Context, *RotateSecretRequest) (*RotateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSecret not implemented")
}
func (UnimplementedSecretsManagerServiceServer) StopReplicationToReplica(context.Context, *StopReplicationToReplicaRequest) (*StopReplicationToReplicaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopReplicationToReplica not implemented")
}
func (UnimplementedSecretsManagerServiceServer) TagResource(context.Context, *TagResourceRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TagResource not implemented")
}
func (UnimplementedSecretsManagerServiceServer) UntagResource(context.Context, *UntagResourceRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UntagResource not implemented")
}
func (UnimplementedSecretsManagerServiceServer) UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecret not implemented")
}
func (UnimplementedSecretsManagerServiceServer) UpdateSecretVersionStage(context.Context, *UpdateSecretVersionStageRequest) (*UpdateSecretVersionStageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecretVersionStage not implemented")
}
func (UnimplementedSecretsManagerServiceServer) ValidateResourcePolicy(context.Context, *ValidateResourcePolicyRequest) (*ValidateResourcePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateResourcePolicy not implemented")
}
func (UnimplementedSecretsManagerServiceServer) mustEmbedUnimplementedSecretsManagerServiceServer() {}
func (UnimplementedSecretsManagerServiceServer) testEmbeddedByValue()                               {}

// UnsafeSecretsManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsManagerServiceServer will
// result in compilation errors.
type UnsafeSecretsManagerServiceServer interface {
	mustEmbedUnimplementedSecretsManagerServiceServer()
}

func RegisterSecretsManagerServiceServer(s grpc.ServiceRegistrar, srv SecretsManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedSecretsManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretsManagerService_ServiceDesc, srv)
}

func _SecretsManagerService_BatchGetSecretValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetSecretValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).BatchGetSecretValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_BatchGetSecretValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).BatchGetSecretValue(ctx, req.(*BatchGetSecretValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_CancelRotateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRotateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).CancelRotateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_CancelRotateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).CancelRotateSecret(ctx, req.(*CancelRotateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_DeleteResourcePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourcePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).DeleteResourcePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_DeleteResourcePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).DeleteResourcePolicy(ctx, req.(*DeleteResourcePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_DescribeSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).DescribeSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_DescribeSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).DescribeSecret(ctx, req.(*DescribeSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_GetRandomPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).GetRandomPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_GetRandomPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).GetRandomPassword(ctx, req.(*GetRandomPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_GetResourcePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).GetResourcePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_GetResourcePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).GetResourcePolicy(ctx, req.(*GetResourcePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_GetSecretValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).GetSecretValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_GetSecretValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).GetSecretValue(ctx, req.(*GetSecretValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_ListSecretVersionIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretVersionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).ListSecretVersionIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_ListSecretVersionIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).ListSecretVersionIds(ctx, req.(*ListSecretVersionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_PutResourcePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutResourcePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).PutResourcePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_PutResourcePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).PutResourcePolicy(ctx, req.(*PutResourcePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_PutSecretValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutSecretValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).PutSecretValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_PutSecretValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).PutSecretValue(ctx, req.(*PutSecretValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_RemoveRegionsFromReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRegionsFromReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).RemoveRegionsFromReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_RemoveRegionsFromReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).RemoveRegionsFromReplication(ctx, req.(*RemoveRegionsFromReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_ReplicateSecretToRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateSecretToRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).ReplicateSecretToRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_ReplicateSecretToRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).ReplicateSecretToRegions(ctx, req.(*ReplicateSecretToRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_RestoreSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).RestoreSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_RestoreSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).RestoreSecret(ctx, req.(*RestoreSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_RotateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).RotateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_RotateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).RotateSecret(ctx, req.(*RotateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_StopReplicationToReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopReplicationToReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).StopReplicationToReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_StopReplicationToReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).StopReplicationToReplica(ctx, req.(*StopReplicationToReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_TagResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).TagResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_TagResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).TagResource(ctx, req.(*TagResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_UntagResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntagResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).UntagResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_UntagResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).UntagResource(ctx, req.(*UntagResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_UpdateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).UpdateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_UpdateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).UpdateSecret(ctx, req.(*UpdateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_UpdateSecretVersionStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretVersionStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).UpdateSecretVersionStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_UpdateSecretVersionStage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).UpdateSecretVersionStage(ctx, req.(*UpdateSecretVersionStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsManagerService_ValidateResourcePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateResourcePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsManagerServiceServer).ValidateResourcePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsManagerService_ValidateResourcePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsManagerServiceServer).ValidateResourcePolicy(ctx, req.(*ValidateResourcePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsManagerService_ServiceDesc is the grpc.ServiceDesc for SecretsManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secretsmanager.SecretsManagerService",
	HandlerType: (*SecretsManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchGetSecretValue",
			Handler:    _SecretsManagerService_BatchGetSecretValue_Handler,
		},
		{
			MethodName: "CancelRotateSecret",
			Handler:    _SecretsManagerService_CancelRotateSecret_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _SecretsManagerService_CreateSecret_Handler,
		},
		{
			MethodName: "DeleteResourcePolicy",
			Handler:    _SecretsManagerService_DeleteResourcePolicy_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _SecretsManagerService_DeleteSecret_Handler,
		},
		{
			MethodName: "DescribeSecret",
			Handler:    _SecretsManagerService_DescribeSecret_Handler,
		},
		{
			MethodName: "GetRandomPassword",
			Handler:    _SecretsManagerService_GetRandomPassword_Handler,
		},
		{
			MethodName: "GetResourcePolicy",
			Handler:    _SecretsManagerService_GetResourcePolicy_Handler,
		},
		{
			MethodName: "GetSecretValue",
			Handler:    _SecretsManagerService_GetSecretValue_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _SecretsManagerService_ListSecrets_Handler,
		},
		{
			MethodName: "ListSecretVersionIds",
			Handler:    _SecretsManagerService_ListSecretVersionIds_Handler,
		},
		{
			MethodName: "PutResourcePolicy",
			Handler:    _SecretsManagerService_PutResourcePolicy_Handler,
		},
		{
			MethodName: "PutSecretValue",
			Handler:    _SecretsManagerService_PutSecretValue_Handler,
		},
		{
			MethodName: "RemoveRegionsFromReplication",
			Handler:    _SecretsManagerService_RemoveRegionsFromReplication_Handler,
		},
		{
			MethodName: "ReplicateSecretToRegions",
			Handler:    _SecretsManagerService_ReplicateSecretToRegions_Handler,
		},
		{
			MethodName: "RestoreSecret",
			Handler:    _SecretsManagerService_RestoreSecret_Handler,
		},
		{
			MethodName: "RotateSecret",
			Handler:    _SecretsManagerService_RotateSecret_Handler,
		},
		{
			MethodName: "StopReplicationToReplica",
			Handler:    _SecretsManagerService_StopReplicationToReplica_Handler,
		},
		{
			MethodName: "TagResource",
			Handler:    _SecretsManagerService_TagResource_Handler,
		},
		{
			MethodName: "UntagResource",
			Handler:    _SecretsManagerService_UntagResource_Handler,
		},
		{
			MethodName: "UpdateSecret",
			Handler:    _SecretsManagerService_UpdateSecret_Handler,
		},
		{
			MethodName: "UpdateSecretVersionStage",
			Handler:    _SecretsManagerService_UpdateSecretVersionStage_Handler,
		},
		{
			MethodName: "ValidateResourcePolicy",
			Handler:    _SecretsManagerService_ValidateResourcePolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secretsmanager.proto",
}
