// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: admin_config.proto

package admin_configconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	admin_config "vorpalstacks/internal/pb/aws/admin_config"
	common "vorpalstacks/internal/pb/aws/common"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminConfigServiceName is the fully-qualified name of the AdminConfigService service.
	AdminConfigServiceName = "admin_config.AdminConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminConfigServiceGetConfigProcedure is the fully-qualified name of the AdminConfigService's
	// GetConfig RPC.
	AdminConfigServiceGetConfigProcedure = "/admin_config.AdminConfigService/GetConfig"
	// AdminConfigServiceListConfigProcedure is the fully-qualified name of the AdminConfigService's
	// ListConfig RPC.
	AdminConfigServiceListConfigProcedure = "/admin_config.AdminConfigService/ListConfig"
	// AdminConfigServiceUpdateConfigProcedure is the fully-qualified name of the AdminConfigService's
	// UpdateConfig RPC.
	AdminConfigServiceUpdateConfigProcedure = "/admin_config.AdminConfigService/UpdateConfig"
	// AdminConfigServiceResetConfigProcedure is the fully-qualified name of the AdminConfigService's
	// ResetConfig RPC.
	AdminConfigServiceResetConfigProcedure = "/admin_config.AdminConfigService/ResetConfig"
	// AdminConfigServiceListServicesProcedure is the fully-qualified name of the AdminConfigService's
	// ListServices RPC.
	AdminConfigServiceListServicesProcedure = "/admin_config.AdminConfigService/ListServices"
	// AdminConfigServiceGetServiceStatusProcedure is the fully-qualified name of the
	// AdminConfigService's GetServiceStatus RPC.
	AdminConfigServiceGetServiceStatusProcedure = "/admin_config.AdminConfigService/GetServiceStatus"
	// AdminConfigServiceGetResourcePortProcedure is the fully-qualified name of the
	// AdminConfigService's GetResourcePort RPC.
	AdminConfigServiceGetResourcePortProcedure = "/admin_config.AdminConfigService/GetResourcePort"
	// AdminConfigServiceSetResourcePortProcedure is the fully-qualified name of the
	// AdminConfigService's SetResourcePort RPC.
	AdminConfigServiceSetResourcePortProcedure = "/admin_config.AdminConfigService/SetResourcePort"
)

// AdminConfigServiceClient is a client for the admin_config.AdminConfigService service.
type AdminConfigServiceClient interface {
	// Configuration management (full CRUD)
	GetConfig(context.Context, *connect.Request[admin_config.GetConfigRequest]) (*connect.Response[admin_config.GetConfigResponse], error)
	ListConfig(context.Context, *connect.Request[admin_config.ListConfigRequest]) (*connect.Response[admin_config.ListConfigResponse], error)
	UpdateConfig(context.Context, *connect.Request[admin_config.UpdateConfigRequest]) (*connect.Response[admin_config.ConfigEntry], error)
	ResetConfig(context.Context, *connect.Request[admin_config.ResetConfigRequest]) (*connect.Response[admin_config.ConfigEntry], error)
	// Service information (read-only)
	ListServices(context.Context, *connect.Request[admin_config.ListServicesRequest]) (*connect.Response[admin_config.ListServicesResponse], error)
	GetServiceStatus(context.Context, *connect.Request[admin_config.GetServiceStatusRequest]) (*connect.Response[admin_config.ServiceStatus], error)
	// Port mappings for resources
	GetResourcePort(context.Context, *connect.Request[admin_config.GetResourcePortRequest]) (*connect.Response[admin_config.GetResourcePortResponse], error)
	SetResourcePort(context.Context, *connect.Request[admin_config.SetResourcePortRequest]) (*connect.Response[common.Empty], error)
}

// NewAdminConfigServiceClient constructs a client for the admin_config.AdminConfigService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminConfigServiceMethods := admin_config.File_admin_config_proto.Services().ByName("AdminConfigService").Methods()
	return &adminConfigServiceClient{
		getConfig: connect.NewClient[admin_config.GetConfigRequest, admin_config.GetConfigResponse](
			httpClient,
			baseURL+AdminConfigServiceGetConfigProcedure,
			connect.WithSchema(adminConfigServiceMethods.ByName("GetConfig")),
			connect.WithClientOptions(opts...),
		),
		listConfig: connect.NewClient[admin_config.ListConfigRequest, admin_config.ListConfigResponse](
			httpClient,
			baseURL+AdminConfigServiceListConfigProcedure,
			connect.WithSchema(adminConfigServiceMethods.ByName("ListConfig")),
			connect.WithClientOptions(opts...),
		),
		updateConfig: connect.NewClient[admin_config.UpdateConfigRequest, admin_config.ConfigEntry](
			httpClient,
			baseURL+AdminConfigServiceUpdateConfigProcedure,
			connect.WithSchema(adminConfigServiceMethods.ByName("UpdateConfig")),
			connect.WithClientOptions(opts...),
		),
		resetConfig: connect.NewClient[admin_config.ResetConfigRequest, admin_config.ConfigEntry](
			httpClient,
			baseURL+AdminConfigServiceResetConfigProcedure,
			connect.WithSchema(adminConfigServiceMethods.ByName("ResetConfig")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[admin_config.ListServicesRequest, admin_config.ListServicesResponse](
			httpClient,
			baseURL+AdminConfigServiceListServicesProcedure,
			connect.WithSchema(adminConfigServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		getServiceStatus: connect.NewClient[admin_config.GetServiceStatusRequest, admin_config.ServiceStatus](
			httpClient,
			baseURL+AdminConfigServiceGetServiceStatusProcedure,
			connect.WithSchema(adminConfigServiceMethods.ByName("GetServiceStatus")),
			connect.WithClientOptions(opts...),
		),
		getResourcePort: connect.NewClient[admin_config.GetResourcePortRequest, admin_config.GetResourcePortResponse](
			httpClient,
			baseURL+AdminConfigServiceGetResourcePortProcedure,
			connect.WithSchema(adminConfigServiceMethods.ByName("GetResourcePort")),
			connect.WithClientOptions(opts...),
		),
		setResourcePort: connect.NewClient[admin_config.SetResourcePortRequest, common.Empty](
			httpClient,
			baseURL+AdminConfigServiceSetResourcePortProcedure,
			connect.WithSchema(adminConfigServiceMethods.ByName("SetResourcePort")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminConfigServiceClient implements AdminConfigServiceClient.
type adminConfigServiceClient struct {
	getConfig        *connect.Client[admin_config.GetConfigRequest, admin_config.GetConfigResponse]
	listConfig       *connect.Client[admin_config.ListConfigRequest, admin_config.ListConfigResponse]
	updateConfig     *connect.Client[admin_config.UpdateConfigRequest, admin_config.ConfigEntry]
	resetConfig      *connect.Client[admin_config.ResetConfigRequest, admin_config.ConfigEntry]
	listServices     *connect.Client[admin_config.ListServicesRequest, admin_config.ListServicesResponse]
	getServiceStatus *connect.Client[admin_config.GetServiceStatusRequest, admin_config.ServiceStatus]
	getResourcePort  *connect.Client[admin_config.GetResourcePortRequest, admin_config.GetResourcePortResponse]
	setResourcePort  *connect.Client[admin_config.SetResourcePortRequest, common.Empty]
}

// GetConfig calls admin_config.AdminConfigService.GetConfig.
func (c *adminConfigServiceClient) GetConfig(ctx context.Context, req *connect.Request[admin_config.GetConfigRequest]) (*connect.Response[admin_config.GetConfigResponse], error) {
	return c.getConfig.CallUnary(ctx, req)
}

// ListConfig calls admin_config.AdminConfigService.ListConfig.
func (c *adminConfigServiceClient) ListConfig(ctx context.Context, req *connect.Request[admin_config.ListConfigRequest]) (*connect.Response[admin_config.ListConfigResponse], error) {
	return c.listConfig.CallUnary(ctx, req)
}

// UpdateConfig calls admin_config.AdminConfigService.UpdateConfig.
func (c *adminConfigServiceClient) UpdateConfig(ctx context.Context, req *connect.Request[admin_config.UpdateConfigRequest]) (*connect.Response[admin_config.ConfigEntry], error) {
	return c.updateConfig.CallUnary(ctx, req)
}

// ResetConfig calls admin_config.AdminConfigService.ResetConfig.
func (c *adminConfigServiceClient) ResetConfig(ctx context.Context, req *connect.Request[admin_config.ResetConfigRequest]) (*connect.Response[admin_config.ConfigEntry], error) {
	return c.resetConfig.CallUnary(ctx, req)
}

// ListServices calls admin_config.AdminConfigService.ListServices.
func (c *adminConfigServiceClient) ListServices(ctx context.Context, req *connect.Request[admin_config.ListServicesRequest]) (*connect.Response[admin_config.ListServicesResponse], error) {
	return c.listServices.CallUnary(ctx, req)
}

// GetServiceStatus calls admin_config.AdminConfigService.GetServiceStatus.
func (c *adminConfigServiceClient) GetServiceStatus(ctx context.Context, req *connect.Request[admin_config.GetServiceStatusRequest]) (*connect.Response[admin_config.ServiceStatus], error) {
	return c.getServiceStatus.CallUnary(ctx, req)
}

// GetResourcePort calls admin_config.AdminConfigService.GetResourcePort.
func (c *adminConfigServiceClient) GetResourcePort(ctx context.Context, req *connect.Request[admin_config.GetResourcePortRequest]) (*connect.Response[admin_config.GetResourcePortResponse], error) {
	return c.getResourcePort.CallUnary(ctx, req)
}

// SetResourcePort calls admin_config.AdminConfigService.SetResourcePort.
func (c *adminConfigServiceClient) SetResourcePort(ctx context.Context, req *connect.Request[admin_config.SetResourcePortRequest]) (*connect.Response[common.Empty], error) {
	return c.setResourcePort.CallUnary(ctx, req)
}

// AdminConfigServiceHandler is an implementation of the admin_config.AdminConfigService service.
type AdminConfigServiceHandler interface {
	// Configuration management (full CRUD)
	GetConfig(context.Context, *connect.Request[admin_config.GetConfigRequest]) (*connect.Response[admin_config.GetConfigResponse], error)
	ListConfig(context.Context, *connect.Request[admin_config.ListConfigRequest]) (*connect.Response[admin_config.ListConfigResponse], error)
	UpdateConfig(context.Context, *connect.Request[admin_config.UpdateConfigRequest]) (*connect.Response[admin_config.ConfigEntry], error)
	ResetConfig(context.Context, *connect.Request[admin_config.ResetConfigRequest]) (*connect.Response[admin_config.ConfigEntry], error)
	// Service information (read-only)
	ListServices(context.Context, *connect.Request[admin_config.ListServicesRequest]) (*connect.Response[admin_config.ListServicesResponse], error)
	GetServiceStatus(context.Context, *connect.Request[admin_config.GetServiceStatusRequest]) (*connect.Response[admin_config.ServiceStatus], error)
	// Port mappings for resources
	GetResourcePort(context.Context, *connect.Request[admin_config.GetResourcePortRequest]) (*connect.Response[admin_config.GetResourcePortResponse], error)
	SetResourcePort(context.Context, *connect.Request[admin_config.SetResourcePortRequest]) (*connect.Response[common.Empty], error)
}

// NewAdminConfigServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminConfigServiceHandler(svc AdminConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminConfigServiceMethods := admin_config.File_admin_config_proto.Services().ByName("AdminConfigService").Methods()
	adminConfigServiceGetConfigHandler := connect.NewUnaryHandler(
		AdminConfigServiceGetConfigProcedure,
		svc.GetConfig,
		connect.WithSchema(adminConfigServiceMethods.ByName("GetConfig")),
		connect.WithHandlerOptions(opts...),
	)
	adminConfigServiceListConfigHandler := connect.NewUnaryHandler(
		AdminConfigServiceListConfigProcedure,
		svc.ListConfig,
		connect.WithSchema(adminConfigServiceMethods.ByName("ListConfig")),
		connect.WithHandlerOptions(opts...),
	)
	adminConfigServiceUpdateConfigHandler := connect.NewUnaryHandler(
		AdminConfigServiceUpdateConfigProcedure,
		svc.UpdateConfig,
		connect.WithSchema(adminConfigServiceMethods.ByName("UpdateConfig")),
		connect.WithHandlerOptions(opts...),
	)
	adminConfigServiceResetConfigHandler := connect.NewUnaryHandler(
		AdminConfigServiceResetConfigProcedure,
		svc.ResetConfig,
		connect.WithSchema(adminConfigServiceMethods.ByName("ResetConfig")),
		connect.WithHandlerOptions(opts...),
	)
	adminConfigServiceListServicesHandler := connect.NewUnaryHandler(
		AdminConfigServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(adminConfigServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	adminConfigServiceGetServiceStatusHandler := connect.NewUnaryHandler(
		AdminConfigServiceGetServiceStatusProcedure,
		svc.GetServiceStatus,
		connect.WithSchema(adminConfigServiceMethods.ByName("GetServiceStatus")),
		connect.WithHandlerOptions(opts...),
	)
	adminConfigServiceGetResourcePortHandler := connect.NewUnaryHandler(
		AdminConfigServiceGetResourcePortProcedure,
		svc.GetResourcePort,
		connect.WithSchema(adminConfigServiceMethods.ByName("GetResourcePort")),
		connect.WithHandlerOptions(opts...),
	)
	adminConfigServiceSetResourcePortHandler := connect.NewUnaryHandler(
		AdminConfigServiceSetResourcePortProcedure,
		svc.SetResourcePort,
		connect.WithSchema(adminConfigServiceMethods.ByName("SetResourcePort")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admin_config.AdminConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminConfigServiceGetConfigProcedure:
			adminConfigServiceGetConfigHandler.ServeHTTP(w, r)
		case AdminConfigServiceListConfigProcedure:
			adminConfigServiceListConfigHandler.ServeHTTP(w, r)
		case AdminConfigServiceUpdateConfigProcedure:
			adminConfigServiceUpdateConfigHandler.ServeHTTP(w, r)
		case AdminConfigServiceResetConfigProcedure:
			adminConfigServiceResetConfigHandler.ServeHTTP(w, r)
		case AdminConfigServiceListServicesProcedure:
			adminConfigServiceListServicesHandler.ServeHTTP(w, r)
		case AdminConfigServiceGetServiceStatusProcedure:
			adminConfigServiceGetServiceStatusHandler.ServeHTTP(w, r)
		case AdminConfigServiceGetResourcePortProcedure:
			adminConfigServiceGetResourcePortHandler.ServeHTTP(w, r)
		case AdminConfigServiceSetResourcePortProcedure:
			adminConfigServiceSetResourcePortHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminConfigServiceHandler struct{}

func (UnimplementedAdminConfigServiceHandler) GetConfig(context.Context, *connect.Request[admin_config.GetConfigRequest]) (*connect.Response[admin_config.GetConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin_config.AdminConfigService.GetConfig is not implemented"))
}

func (UnimplementedAdminConfigServiceHandler) ListConfig(context.Context, *connect.Request[admin_config.ListConfigRequest]) (*connect.Response[admin_config.ListConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin_config.AdminConfigService.ListConfig is not implemented"))
}

func (UnimplementedAdminConfigServiceHandler) UpdateConfig(context.Context, *connect.Request[admin_config.UpdateConfigRequest]) (*connect.Response[admin_config.ConfigEntry], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin_config.AdminConfigService.UpdateConfig is not implemented"))
}

func (UnimplementedAdminConfigServiceHandler) ResetConfig(context.Context, *connect.Request[admin_config.ResetConfigRequest]) (*connect.Response[admin_config.ConfigEntry], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin_config.AdminConfigService.ResetConfig is not implemented"))
}

func (UnimplementedAdminConfigServiceHandler) ListServices(context.Context, *connect.Request[admin_config.ListServicesRequest]) (*connect.Response[admin_config.ListServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin_config.AdminConfigService.ListServices is not implemented"))
}

func (UnimplementedAdminConfigServiceHandler) GetServiceStatus(context.Context, *connect.Request[admin_config.GetServiceStatusRequest]) (*connect.Response[admin_config.ServiceStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin_config.AdminConfigService.GetServiceStatus is not implemented"))
}

func (UnimplementedAdminConfigServiceHandler) GetResourcePort(context.Context, *connect.Request[admin_config.GetResourcePortRequest]) (*connect.Response[admin_config.GetResourcePortResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin_config.AdminConfigService.GetResourcePort is not implemented"))
}

func (UnimplementedAdminConfigServiceHandler) SetResourcePort(context.Context, *connect.Request[admin_config.SetResourcePortRequest]) (*connect.Response[common.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin_config.AdminConfigService.SetResourcePort is not implemented"))
}
