// Package cloudtrail provides CloudTrail data store functionality for vorpalstacks.
package cloudtrail

import (
	"crypto/rsa"
	"crypto/x509"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	svcarn "vorpalstacks/internal/utils/aws/arn"
	vcrypto "vorpalstacks/internal/utils/crypto"
)

// Trail represents a CloudTrail trail.
type Trail struct {
	Name                       string `json:"name"`
	TrailARN                   string `json:"trailArn"`
	S3BucketName               string `json:"s3BucketName,omitempty"`
	S3KeyPrefix                string `json:"s3KeyPrefix,omitempty"`
	SnsTopicName               string `json:"snsTopicName,omitempty"`
	SnsTopicARN                string `json:"snsTopicArn,omitempty"`
	IncludeGlobalServiceEvents bool   `json:"includeGlobalServiceEvents"`
	IsMultiRegionTrail         bool   `json:"isMultiRegionTrail"`
	HomeRegion                 string `json:"homeRegion"`
	IsOrganizationTrail        bool   `json:"isOrganizationTrail"`
	IsLogging                  bool   `json:"isLogging"`
	// RecursiveLogging defaults to true: when false, CloudTrail suppresses
	// events generated by CloudTrail itself when delivering log files to
	// the trail's destinations.
	RecursiveLogging          bool                    `json:"recursiveLogging"`
	LogFileValidationEnabled  bool                    `json:"logFileValidationEnabled"`
	CloudWatchLogsLogGroupARN string                  `json:"cloudWatchLogsLogGroupArn,omitempty"`
	CloudWatchLogsRoleARN     string                  `json:"cloudWatchLogsRoleArn,omitempty"`
	KMSKeyID                  string                  `json:"kmsKeyId,omitempty"`
	HasCustomEventSelectors   bool                    `json:"hasCustomEventSelectors"`
	HasInsightSelectors       bool                    `json:"hasInsightSelectors"`
	EventSelectors            []EventSelector         `json:"eventSelectors,omitempty"`
	AdvancedEventSelectors    []AdvancedEventSelector `json:"advancedEventSelectors,omitempty"`
	InsightSelectors          []InsightSelector       `json:"insightSelectors,omitempty"`
	CreatedAt                 time.Time               `json:"createdAt"`
	LastUpdated               time.Time               `json:"lastUpdated"`
	StartedLoggingAt          *time.Time              `json:"startedLoggingAt,omitempty"`
	StoppedLoggingAt          *time.Time              `json:"stoppedLoggingAt,omitempty"`

	// Delivery bookkeeping, owned by the delivery worker under the trail
	// lock: the per-region watermark (events delivered through), the latest
	// delivery and digest outcomes GetTrailStatus reports, and the digest
	// chain state.
	DeliveryWatermarks           map[string]int64 `json:"deliveryWatermarks,omitempty"`
	LatestDeliveryTime           *time.Time       `json:"latestDeliveryTime,omitempty"`
	LatestDeliveryError          string           `json:"latestDeliveryError,omitempty"`
	LatestDeliveryAttemptTime    *time.Time       `json:"latestDeliveryAttemptTime,omitempty"`
	LatestDeliveryAttemptSuccess bool             `json:"latestDeliveryAttemptSuccess,omitempty"`
	LatestDigestTime             *time.Time       `json:"latestDigestTime,omitempty"`
	LatestDigestError            string           `json:"latestDigestError,omitempty"`
	PreviousDigestBucket         string           `json:"previousDigestBucket,omitempty"`
	PreviousDigestObject         string           `json:"previousDigestObject,omitempty"`
	PreviousDigestHash           string           `json:"previousDigestHash,omitempty"`
	PreviousDigestSignature      string           `json:"previousDigestSignature,omitempty"`
	LastDigestEnd                *time.Time       `json:"lastDigestEnd,omitempty"`
	PendingDigestFiles           []DigestLogFile  `json:"pendingDigestFiles,omitempty"`

	// Notification (Amazon SNS) and CloudWatch Logs delivery bookkeeping,
	// owned by the delivery worker under the trail lock; nil times report
	// "never delivered" on GetTrailStatus.
	LatestNotificationTime           *time.Time `json:"latestNotificationTime,omitempty"`
	LatestNotificationError          string     `json:"latestNotificationError,omitempty"`
	LatestNotificationAttemptTime    *time.Time `json:"latestNotificationAttemptTime,omitempty"`
	LatestNotificationAttemptSuccess bool       `json:"latestNotificationAttemptSuccess,omitempty"`
	LatestCWLogsDeliveryTime         *time.Time `json:"latestCwLogsDeliveryTime,omitempty"`
	LatestCWLogsDeliveryError        string     `json:"latestCwLogsDeliveryError,omitempty"`

	// CwlogsWatermarks is the CloudWatch Logs destination's own per-region
	// watermark (events delivered through): the stream advances
	// independently of the S3 watermark so a retried S3 window does not
	// re-deliver stream events.
	CwlogsWatermarks map[string]int64 `json:"cwlogsWatermarks,omitempty"`
}

// DigestLogFile records one delivered log file awaiting its digest: the
// digest references every file delivered since the previous digest. A
// delivered digest itself becomes a chain entry carrying its signature.
type DigestLogFile struct {
	Bucket        string    `json:"bucket"`
	ObjectKey     string    `json:"objectKey"`
	HashHex       string    `json:"hashHex"`
	NewestEventAt time.Time `json:"newestEventAt"`
	OldestEventAt time.Time `json:"oldestEventAt"`
	SignatureHex  string    `json:"signatureHex,omitempty"`
}

// EventSelector represents event selector settings for a CloudTrail trail.
type EventSelector struct {
	ReadWriteType                 string         `json:"readWriteType,omitempty"`
	IncludeManagementEvents       bool           `json:"includeManagementEvents,omitempty"`
	DataResources                 []DataResource `json:"dataResources,omitempty"`
	ExcludeManagementEventSources []string       `json:"excludeManagementEventSources,omitempty"`
}

// DataResource represents a data resource for CloudTrail event selection.
type DataResource struct {
	Type   string   `json:"type"`
	Values []string `json:"values"`
}

// InsightSelector represents insight selector settings for a CloudTrail trail.
type InsightSelector struct {
	InsightType string `json:"insightType"`
}

// Event represents a CloudTrail event.
type Event struct {
	EventID           string                 `json:"eventId"`
	EventName         string                 `json:"eventName"`
	ReadOnly          string                 `json:"readOnly"`
	AccessKeyId       string                 `json:"accessKeyId,omitempty"`
	EventSource       string                 `json:"eventSource"`
	EventTime         time.Time              `json:"eventTime"`
	EventType         string                 `json:"eventType"`
	EventVersion      string                 `json:"eventVersion"`
	AwsRegion         string                 `json:"awsRegion,omitempty"`
	UserIdentity      *UserIdentity          `json:"userIdentity"`
	Resources         []Resource             `json:"resources,omitempty"`
	CloudTrailEvent   string                 `json:"cloudTrailEvent,omitempty"`
	RequestParameters map[string]interface{} `json:"requestParameters,omitempty"`
	ResponseElements  map[string]interface{} `json:"responseElements,omitempty"`
	RequestID         string                 `json:"requestId,omitempty"`
	SourceIPAddress   string                 `json:"sourceIpAddress,omitempty"`
	UserAgent         string                 `json:"userAgent,omitempty"`
	ErrorCode         string                 `json:"errorCode,omitempty"`
	ErrorMessage      string                 `json:"errorMessage,omitempty"`
	EventCategory     string                 `json:"eventCategory,omitempty"`
}

// UserIdentity represents the identity information for a CloudTrail event.
type UserIdentity struct {
	Type           string          `json:"type"`
	PrincipalID    string          `json:"principalId,omitempty"`
	ARN            string          `json:"arn,omitempty"`
	AccountID      string          `json:"accountId,omitempty"`
	AccessKeyID    string          `json:"accessKeyId,omitempty"`
	UserName       string          `json:"userName,omitempty"`
	SessionContext *SessionContext `json:"sessionContext,omitempty"`
}

// SessionContext represents session context information for a CloudTrail event.
type SessionContext struct {
	SessionIssuer *SessionIssuer     `json:"sessionIssuer,omitempty"`
	Attributes    *SessionAttributes `json:"attributes,omitempty"`
}

// SessionIssuer represents session issuer information for a CloudTrail event.
type SessionIssuer struct {
	Type        string `json:"type"`
	PrincipalID string `json:"principalId"`
	ARN         string `json:"arn"`
	AccountID   string `json:"accountId,omitempty"`
	UserName    string `json:"userName,omitempty"`
}

// SessionAttributes represents session attributes for a CloudTrail event.
type SessionAttributes struct {
	CreationDate     time.Time `json:"creationDate"`
	MFAAuthenticated string    `json:"mfaAuthenticated"`
}

// Resource represents a resource associated with a CloudTrail event.
type Resource struct {
	ResourceType string `json:"resourceType,omitempty"`
	ResourceName string `json:"resourceName,omitempty"`
}

// EventDataStore represents a CloudTrail event data store for CloudTrail Lake.
type EventDataStore struct {
	EventDataStoreID             string                  `json:"eventDataStoreId"`
	EventDataStoreARN            string                  `json:"eventDataStoreArn"`
	Name                         string                  `json:"name"`
	TerminationProtectionEnabled bool                    `json:"terminationProtectionEnabled"`
	Status                       string                  `json:"status"`
	AdvancedEventSelectors       []AdvancedEventSelector `json:"advancedEventSelectors,omitempty"`
	MultiRegionEnabled           bool                    `json:"multiRegionEnabled"`
	OrganizationEnabled          bool                    `json:"organizationEnabled"`
	RetentionPeriod              int32                   `json:"retentionPeriod"`
	BillingMode                  string                  `json:"billingMode,omitempty"`
	IngestionEnabled             bool                    `json:"ingestionEnabled"`
	KMSKeyID                     string                  `json:"kmsKeyId,omitempty"`
	CreatedTimestamp             time.Time               `json:"createdTimestamp"`
	UpdatedTimestamp             time.Time               `json:"updatedTimestamp"`
	FederationStatus             string                  `json:"federationStatus,omitempty"`
	FederationRoleARN            string                  `json:"federationRoleArn,omitempty"`
	DeletedTimestamp             *time.Time              `json:"deletedTimestamp,omitempty"`
	Tags                         map[string]string       `json:"tags,omitempty"`
}

// AdvancedEventSelector represents advanced event selector settings for an
// event data store.
type AdvancedEventSelector struct {
	Name           string                  `json:"name,omitempty"`
	FieldSelectors []AdvancedFieldSelector `json:"fieldSelectors"`
}

// AdvancedFieldSelector represents a field selector within an advanced event selector.
type AdvancedFieldSelector struct {
	Field         string   `json:"field"`
	Equals        []string `json:"equals,omitempty"`
	StartsWith    []string `json:"startsWith,omitempty"`
	EndsWith      []string `json:"endsWith,omitempty"`
	NotEquals     []string `json:"notEquals,omitempty"`
	NotStartsWith []string `json:"notStartsWith,omitempty"`
	NotEndsWith   []string `json:"notEndsWith,omitempty"`
}

// NewEventDataStore creates a new CloudTrail event data store with defaults.
func NewEventDataStore(name string, accountID, region string) *EventDataStore {
	now := time.Now().UTC()
	id := uuid.NewString()
	builder := svcarn.NewARNBuilder(accountID, region)
	return &EventDataStore{
		EventDataStoreID:             id,
		EventDataStoreARN:            builder.CloudTrail().EventDataStore(id),
		Name:                         name,
		TerminationProtectionEnabled: true,
		Status:                       "ENABLED",
		// A store created without advanced event selectors ingests
		// management events — the documented CloudTrail default. The
		// default selector is materialised on the record so ingestion and
		// every response echo share one configuration (the AWS CLI
		// create-event-data-store example response shows the synthesised
		// "Default management events" selector).
		AdvancedEventSelectors: DefaultEDSEventSelectors(),
		MultiRegionEnabled:     true,
		OrganizationEnabled:    false,
		RetentionPeriod:        DefaultEventDataStoreRetentionDays,
		IngestionEnabled:       true,
		BillingMode:            "EXTENDABLE_RETENTION_PRICING",
		CreatedTimestamp:       now,
		UpdatedTimestamp:       now,
		Tags:                   make(map[string]string),
	}
}

// ResourcePolicy represents a resource policy for CloudTrail.
type ResourcePolicy struct {
	ResourceARN string `json:"resourceArn"`
	Policy      string `json:"policy"`
}

// QueryRecord represents a stored CloudTrail Lake query.
type QueryRecord struct {
	QueryID               string                `json:"queryId"`
	EventDataStore        string                `json:"eventDataStore"`
	QueryStatement        string                `json:"queryStatement"`
	QueryStatus           string                `json:"queryStatus"`
	ErrorMessage          string                `json:"errorMessage,omitempty"`
	QueryResultRows       [][]map[string]string `json:"queryResultRows,omitempty"`
	ResultsCount          int32                 `json:"resultsCount"`
	EventsMatched         int64                 `json:"eventsMatched"`
	EventsScanned         int64                 `json:"eventsScanned"`
	BytesScanned          int64                 `json:"bytesScanned"`
	ExecutionTimeInMillis int64                 `json:"executionTimeInMillis"`
	StartTime             time.Time             `json:"startTime"`
	EndTime               *time.Time            `json:"endTime,omitempty"`
	DeliveryS3URI         string                `json:"deliveryS3Uri,omitempty"`
	DeliveryStatus        string                `json:"deliveryStatus,omitempty"`
}

// QueryTerminalStatus reports whether a query status admits no further
// transitions. TIMED_OUT and CANCELLED are terminal exactly like FINISHED
// and FAILED; QUEUED and RUNNING are the live states.
func QueryTerminalStatus(status string) bool {
	return status == "FINISHED" || status == "FAILED" ||
		status == "CANCELLED" || status == "TIMED_OUT"
}

// Channel represents a CloudTrail Lake channel for external data ingestion.
type Channel struct {
	ChannelARN      string            `json:"channelArn"`
	Name            string            `json:"name"`
	Source          string            `json:"source"`
	Destinations    []Destination     `json:"destinations,omitempty"`
	IngestionStatus string            `json:"ingestionStatus,omitempty"`
	Tags            map[string]string `json:"tags,omitempty"`
	CreatedAt       time.Time         `json:"createdAt"`
	UpdatedAt       time.Time         `json:"updatedAt"`
}

// DestinationTypeEventDataStore is the Destination.Type value for a
// CloudTrail Lake integration destination: Location carries the ARN of the
// event data store that receives the channel's events (the model's other
// type, AWS_SERVICE, names a service instead).
const DestinationTypeEventDataStore = "EVENT_DATA_STORE"

// Destination represents a destination for a CloudTrail channel.
type Destination struct {
	Type     string `json:"type"`
	Location string `json:"location,omitempty"`
}

// NewChannel creates a new CloudTrail channel with defaults.
func NewChannel(name, source, accountID, region string) *Channel {
	now := time.Now().UTC()
	id := uuid.NewString()
	builder := svcarn.NewARNBuilder(accountID, region)
	return &Channel{
		ChannelARN:      builder.CloudTrail().Channel(id),
		Name:            name,
		Source:          source,
		IngestionStatus: "STOPPED",
		Tags:            make(map[string]string),
		CreatedAt:       now,
		UpdatedAt:       now,
	}
}

// PublicKey represents a CloudTrail public key used for log file validation.
type PublicKey struct {
	PublicKeyID       string    `json:"publicKeyId"`
	Value             []byte    `json:"value"`
	ValidityStartTime time.Time `json:"validityStartTime"`
	ValidityEndTime   time.Time `json:"validityEndTime"`
	TrailName         string    `json:"trailName,omitempty"`
	// PrivateKeyDER carries the PKCS#1 DER private half for trail
	// validation keys so the hourly digest chain can keep signing across
	// restarts. Per-delivery query signing keys leave it empty.
	PrivateKeyDER []byte `json:"privateKeyDer,omitempty"`
}

// GenerateKeyPair generates an RSA key pair using the common crypto utility.
// The returned public half is DER encoded in PKCS#1 form — the PublicKey
// contract documents Value as "The DER encoded public key value in PKCS#1
// format" — and is suitable for CloudTrail log file validation; the private
// half is the signer for digest and query result sign files and is never
// persisted.
func GenerateKeyPair() (*PublicKey, *rsa.PrivateKey, error) {
	privKey, err := vcrypto.GenerateRSAKey(vcrypto.DefaultRSAKeySize)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate RSA key pair: %w", err)
	}

	derBytes := x509.MarshalPKCS1PublicKey(&privKey.PublicKey)

	now := time.Now().UTC()
	return &PublicKey{
		PublicKeyID:       "K" + uuid.NewString(),
		Value:             derBytes,
		ValidityStartTime: now,
		ValidityEndTime:   now.Add(PublicKeyValidity),
	}, privKey, nil
}

// Fingerprint derives the key's fingerprint from the exact bytes Value
// serves: the lowercase hexadecimal encoding of the MD5 digest of the DER
// value. The digest file reference documents the fingerprint as
// "hexadecimal encoded" and its sample value is 32 hex characters (16
// bytes), which fixes the length; the digest algorithm itself is not
// documented, and hashing the served bytes lets a validator recompute the
// fingerprint from Value. The identifier is matched by equality only —
// the signatures carry the integrity protection (SHA256withRSA).
func (pk *PublicKey) Fingerprint() string {
	return hex.EncodeToString(vcrypto.MD5Hash(pk.Value))
}

// NewTrail creates a new CloudTrail trail with default settings.
func NewTrail(name, s3BucketName, region string) *Trail {
	now := time.Now().UTC()
	return &Trail{
		Name:                       name,
		S3BucketName:               s3BucketName,
		HomeRegion:                 region,
		IncludeGlobalServiceEvents: true,
		IsLogging:                  false,
		RecursiveLogging:           true,
		LogFileValidationEnabled:   false,
		HasCustomEventSelectors:    false,
		HasInsightSelectors:        false,
		EventSelectors: []EventSelector{
			{
				ReadWriteType:           "All",
				IncludeManagementEvents: true,
			},
		},
		CreatedAt:   now,
		LastUpdated: now,
	}
}

// Import represents a CloudTrail Lake import operation for copying trail
// events from an S3 bucket into an event data store. Attempt numbers the
// executions of one import record: a retry increments it, and an executor
// still walking from an earlier attempt abandons at its next checkpoint
// when the record carries a different number — without it, a retry issued
// while a stopped attempt's goroutine is still draining would run two
// executors over the same walk.
type Import struct {
	ImportID         string           `json:"importId"`
	Destinations     []string         `json:"destinations"`
	ImportSource     ImportSource     `json:"importSource"`
	StartEventTime   *time.Time       `json:"startEventTime,omitempty"`
	EndEventTime     *time.Time       `json:"endEventTime,omitempty"`
	ImportStatus     string           `json:"importStatus"`
	Attempt          int64            `json:"attempt"`
	CreatedTimestamp time.Time        `json:"createdTimestamp"`
	UpdatedTimestamp time.Time        `json:"updatedTimestamp"`
	ImportStatistics ImportStatistics `json:"importStatistics,omitempty"`
	Failures         []ImportFailure  `json:"failures,omitempty"`
}

// ImportSource specifies the S3 bucket source for a CloudTrail import.
type ImportSource struct {
	S3LocationURI         string `json:"s3LocationUri"`
	S3BucketRegion        string `json:"s3BucketRegion"`
	S3BucketAccessRoleARN string `json:"s3BucketAccessRoleArn,omitempty"`
}

// ImportStatistics tracks the progress of a CloudTrail import.
type ImportStatistics struct {
	PrefixesFound     int64 `json:"prefixesFound,omitempty"`
	PrefixesCompleted int64 `json:"prefixesCompleted,omitempty"`
	FilesCompleted    int64 `json:"filesCompleted,omitempty"`
	EventsCompleted   int64 `json:"eventsCompleted,omitempty"`
	FailedEntries     int64 `json:"failedEntries,omitempty"`
}

// ImportFailure represents a single failure during a CloudTrail import.
type ImportFailure struct {
	Location        string     `json:"location,omitempty"`
	Status          string     `json:"status,omitempty"`
	ErrorType       string     `json:"errorType,omitempty"`
	ErrorMessage    string     `json:"errorMessage,omitempty"`
	LastUpdatedTime *time.Time `json:"lastUpdatedTime,omitempty"`
}

// NewImport creates a new CloudTrail import with default status.
func NewImport(destinations []string, source ImportSource) *Import {
	now := time.Now().UTC()
	return &Import{
		ImportID:         uuid.NewString(),
		Destinations:     destinations,
		ImportSource:     source,
		ImportStatus:     "INITIALIZING",
		CreatedTimestamp: now,
		UpdatedTimestamp: now,
	}
}

// NewEvent creates a new CloudTrail event. The readOnly flag carries the
// operation's read-only classification in the wire string form the
// LookupEvents response and the record JSON use.
func NewEvent(eventName, eventSource string, userIdentity *UserIdentity, readOnly bool) *Event {
	now := time.Now().UTC()
	readOnlyStr := "false"
	if readOnly {
		readOnlyStr = "true"
	}
	return &Event{
		EventID:       generateEventID(),
		EventName:     eventName,
		EventSource:   eventSource,
		EventTime:     now,
		EventType:     "AwsApiCall",
		EventVersion:  "1.08",
		EventCategory: "Management",
		UserIdentity:  userIdentity,
		Resources:     []Resource{},
		ReadOnly:      readOnlyStr,
	}
}

func generateEventID() string {
	return uuid.NewString()
}

// generateCloudTrailEvent populates the CloudTrailEvent field with the
// event's JSON in the AWS CloudTrail record format (the CloudTrail record
// contents reference): eventID and requestID spellings, boolean readOnly,
// awsRegion, record-shaped resources entries, and the identity's
// sessionContext when temporary credentials made the call.
func (e *Event) generateCloudTrailEvent() {
	if e.CloudTrailEvent != "" {
		return
	}

	record := &cloudTrailRecord{
		EventVersion:      e.EventVersion,
		UserIdentity:      e.UserIdentity,
		EventTime:         e.EventTime.UTC().Truncate(time.Second).Format(time.RFC3339),
		EventSource:       e.EventSource,
		EventName:         e.EventName,
		AWSRegion:         e.AwsRegion,
		SourceIPAddress:   e.SourceIPAddress,
		UserAgent:         e.UserAgent,
		ErrorCode:         e.ErrorCode,
		ErrorMessage:      e.ErrorMessage,
		RequestParameters: e.RequestParameters,
		ResponseElements:  e.ResponseElements,
		RequestID:         e.RequestID,
		EventID:           e.EventID,
		ReadOnly:          e.ReadOnly == "true",
		EventType:         e.EventType,
		ManagementEvent:   true,
		EventCategory:     e.EventCategory,
	}
	for _, r := range e.Resources {
		entry := recordResource{ARN: r.ResourceName, Type: r.ResourceType}
		if parsed, err := svcarn.ParseARN(r.ResourceName); err == nil {
			entry.AccountID = parsed.AccountID
		}
		record.Resources = append(record.Resources, entry)
	}

	b, err := json.Marshal(record)
	if err != nil {
		return
	}
	e.CloudTrailEvent = string(b)
}

// cloudTrailRecord mirrors the AWS CloudTrail record format so the stored
// CloudTrailEvent JSON parses as a CloudTrail record: the keys carry the
// record spellings (eventID, requestID), readOnly is a JSON boolean,
// requestParameters and responseElements are always present (null when the
// operation has none, as AWS emits for read-only APIs), and resources
// entries carry ARN, accountId and the AWS::service::type identifier.
type cloudTrailRecord struct {
	EventVersion      string                 `json:"eventVersion"`
	UserIdentity      *UserIdentity          `json:"userIdentity"`
	EventTime         string                 `json:"eventTime"`
	EventSource       string                 `json:"eventSource"`
	EventName         string                 `json:"eventName"`
	AWSRegion         string                 `json:"awsRegion"`
	SourceIPAddress   string                 `json:"sourceIpAddress,omitempty"`
	UserAgent         string                 `json:"userAgent,omitempty"`
	ErrorCode         string                 `json:"errorCode,omitempty"`
	ErrorMessage      string                 `json:"errorMessage,omitempty"`
	RequestParameters map[string]interface{} `json:"requestParameters"`
	ResponseElements  map[string]interface{} `json:"responseElements"`
	RequestID         string                 `json:"requestID,omitempty"`
	EventID           string                 `json:"eventID"`
	ReadOnly          bool                   `json:"readOnly"`
	Resources         []recordResource       `json:"resources,omitempty"`
	EventType         string                 `json:"eventType"`
	ManagementEvent   bool                   `json:"managementEvent"`
	EventCategory     string                 `json:"eventCategory"`
}

// recordResource is a record-format resources entry. The ARN key is
// capitalised per the AWS record example; the type identifier
// (AWS::{{service}}::{{type}}) and the resource owner's accountId are
// optional record fields.
type recordResource struct {
	ARN       string `json:"ARN"`
	AccountID string `json:"accountId,omitempty"`
	Type      string `json:"type,omitempty"`
}
