package iot

import (
	awserrors "vorpalstacks/internal/common/errors"
)

var (
	ErrThingNotFound                    = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrThingAlreadyExists               = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrThingTypeNotFound                = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrThingTypeAlreadyExists           = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrThingGroupNotFound               = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrThingGroupAlreadyExists          = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrBillingGroupNotFound             = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrBillingGroupAlreadyExists        = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrCertificateNotFound              = awserrors.NewAWSError("ResourceNotFoundException", "The specified certificate does not exist.", 404)
	ErrCertificateAlreadyExists         = awserrors.NewAWSError("ResourceAlreadyExistsException", "The certificate already exists.", 409)
	ErrPolicyNotFound                   = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrPolicyVersionNotFound            = awserrors.NewAWSError("ResourceNotFoundException", "The specified policy version does not exist.", 404)
	ErrPolicyAlreadyExists              = awserrors.NewAWSError("ResourceAlreadyExistsException", "The policy already exists.", 409)
	ErrPolicyVersionLimitExceeded       = awserrors.NewAWSError("VersionsLimitExceededException", "The policy has reached the maximum number of versions (5).", 413)
	ErrRuleNotFound                     = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrRuleAlreadyExists                = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrJobNotFound                      = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrJobAlreadyExists                 = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrJobExecutionNotFound             = awserrors.NewAWSError("ResourceNotFoundException", "JobExecution not found.", 404)
	ErrShadowNotFound                   = awserrors.NewAWSError("ResourceNotFoundException", "No shadow exists for the specified thing.", 404)
	ErrAuthorizerNotFound               = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrAuthorizerAlreadyExists          = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrRoleAliasNotFound                = awserrors.NewAWSError("ResourceNotFoundException", "The specified role alias does not exist.", 404)
	ErrRoleAliasAlreadyExists           = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrTemplateNotFound                 = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrTemplateAlreadyExists            = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrSecurityProfileNotFound          = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrSecurityProfileAlreadyExists     = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrDomainConfigurationNotFound      = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrDomainConfigurationAlreadyExists = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)
	ErrIndexingConfigurationNotFound    = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrTemplateVersionNotFound          = awserrors.NewAWSError("ResourceNotFoundException", "The specified resource does not exist.", 404)
	ErrInvalidSecurityProfileBehaviors  = awserrors.NewAWSError("InvalidRequestException", "The security profile behaviors are not valid.", 400)

	// Bulk entities: dedicated NotFound sentinels so Describe/Update
	// can return a proper ResourceNotFoundException (404) instead of a generic
	// InvalidRequestException (400), matching AWS behaviour.
	ErrCustomMetricNotFound          = awserrors.NewAWSError("ResourceNotFoundException", "The specified custom metric does not exist.", 404)
	ErrDimensionNotFound             = awserrors.NewAWSError("ResourceNotFoundException", "The specified dimension does not exist.", 404)
	ErrMitigationActionNotFound      = awserrors.NewAWSError("ResourceNotFoundException", "The specified mitigation action does not exist.", 404)
	ErrFleetMetricNotFound           = awserrors.NewAWSError("ResourceNotFoundException", "The specified fleet metric does not exist.", 404)
	ErrScheduledAuditNotFound        = awserrors.NewAWSError("ResourceNotFoundException", "The specified scheduled audit does not exist.", 404)
	ErrTopicRuleDestinationNotFound  = awserrors.NewAWSError("ResourceNotFoundException", "The specified topic rule destination does not exist.", 404)
	ErrDefaultAuthorizerNotFound     = awserrors.NewAWSError("ResourceNotFoundException", "The specified default authorizer does not exist.", 404)
	ErrThingRegistrationTaskNotFound = awserrors.NewAWSError("ResourceNotFoundException", "The specified thing registration task does not exist.", 404)
	ErrJobTemplateNotFound           = awserrors.NewAWSError("ResourceNotFoundException", "The specified job template does not exist.", 404)

	// Audit subsystem sentinels. AWS returns ResourceNotFoundException when a
	// task, finding, or suppression identifier does not resolve to a record.
	ErrAuditSuppressionNotFound          = awserrors.NewAWSError("ResourceNotFoundException", "The specified audit suppression does not exist.", 404)
	ErrAuditTaskNotFound                 = awserrors.NewAWSError("ResourceNotFoundException", "The specified audit task does not exist.", 404)
	ErrAuditFindingNotFound              = awserrors.NewAWSError("ResourceNotFoundException", "The specified audit finding does not exist.", 404)
	ErrAuditMitigationTaskNotFound       = awserrors.NewAWSError("ResourceNotFoundException", "The specified audit mitigation actions task does not exist.", 404)
	ErrDetectMitigationTaskNotFound      = awserrors.NewAWSError("ResourceNotFoundException", "The specified detect mitigation actions task does not exist.", 404)
	ErrSecurityProfileAttachmentNotFound = awserrors.NewAWSError("ResourceNotFoundException", "The specified security profile attachment does not exist.", 404)
	ErrStreamNotFound                    = awserrors.NewAWSError("ResourceNotFoundException", "The specified stream does not exist.", 404)
	ErrPackageNotFound                   = awserrors.NewAWSError("ResourceNotFoundException", "The specified package does not exist.", 404)
	ErrPackageVersionNotFound            = awserrors.NewAWSError("ResourceNotFoundException", "The specified package version does not exist.", 404)
	ErrCommandNotFound                   = awserrors.NewAWSError("ResourceNotFoundException", "The specified command does not exist.", 404)
	ErrCommandExecutionNotFound          = awserrors.NewAWSError("ResourceNotFoundException", "The specified command execution does not exist.", 404)
	ErrCertificateProviderNotFound       = awserrors.NewAWSError("ResourceNotFoundException", "The specified certificate provider does not exist.", 404)
	ErrCertificateProviderAlreadyExists  = awserrors.NewAWSError("ResourceAlreadyExistsException", "A certificate provider already exists for this account. Only one certificate provider is allowed per account.", 409)
	ErrPackageAlreadyExists              = awserrors.NewAWSError("ConflictException", "The specified package already exists.", 409)
	ErrPackageVersionAlreadyExists       = awserrors.NewAWSError("ConflictException", "The specified package version already exists.", 409)
	ErrCommandAlreadyExists              = awserrors.NewAWSError("ConflictException", "The specified command already exists.", 409)

	ErrInvalidRequest             = awserrors.NewAWSError("InvalidRequestException", "The request is not valid.", 400)
	ErrMissingParam               = awserrors.NewAWSError("InvalidRequestException", "The request must contain the required parameter.", 400)
	ErrInvalidCertStatus          = awserrors.NewAWSError("CertificateStateException", "The certificate is in an invalid state for the requested operation.", 400)
	ErrThingAlreadyInBillingGroup = awserrors.NewAWSError("InvalidRequestException", "The thing is already in a billing group.", 400)
	ErrCertHasAttachments         = awserrors.NewAWSError("CertificateStateException", "The certificate has attached entities and cannot be deleted.", 400)
	ErrShadowTooLarge             = awserrors.NewAWSError("InvalidRequestException", "The shadow document exceeds the maximum size of 8KB.", 400)
	ErrResourceAlreadyExists      = awserrors.NewAWSError("ResourceAlreadyExistsException", "The resource already exists.", 409)

	ErrVersionConflict     = awserrors.NewAWSError("VersionConflictException", "The specified version does not match the version of the document.", 409)
	ErrCertificateConflict = awserrors.NewAWSError("CertificateConflictException", "The certificate is in an invalid state for the requested operation.", 409)
	ErrDeleteConflict      = awserrors.NewAWSError("DeleteConflictException", "The resource cannot be deleted.", 409)

	ErrThrottling             = awserrors.NewAWSError("ThrottlingException", "Rate exceeded.", 429)
	ErrInvalidStateTransition = awserrors.NewAWSError("InvalidStateTransitionException", "An invalid state transition was attempted.", 400)
	ErrInternalFailure        = awserrors.NewAWSError("InternalFailureException", "An internal error occurred.", 500)

	ErrCertificateValidation      = awserrors.NewAWSError("CertificateValidationException", "The certificate is not valid.", 400)
	ErrConflictingUpdate          = awserrors.NewAWSError("ConflictingResourceUpdateException", "A conflicting resource update is in progress.", 409)
	ErrIndexNotReady              = awserrors.NewAWSError("IndexNotReadyException", "The fleet index is not ready.", 400)
	ErrInvalidAggregation         = awserrors.NewAWSError("InvalidAggregationException", "The aggregation field or type is not valid.", 400)
	ErrInvalidQuery               = awserrors.NewAWSError("InvalidQueryException", "The query string is not valid.", 400)
	ErrMalformedPolicy            = awserrors.NewAWSError("MalformedPolicyException", "The policy document is malformed.", 400)
	ErrNotConfigured              = awserrors.NewAWSError("NotConfiguredException", "The resource is not configured.", 400)
	ErrRegistrationCodeValidation = awserrors.NewAWSError("RegistrationCodeValidationException", "The registration code is not valid.", 400)
	ErrSqlParse                   = awserrors.NewAWSError("SqlParseException", "The SQL statement is not valid.", 400)
	ErrUnauthorized               = awserrors.NewAWSError("UnauthorizedException", "The request is not authorized.", 401)
	ErrValidation                 = awserrors.NewAWSError("ValidationException", "The request validation failed.", 400)
	ErrVersionsLimitExceeded      = awserrors.NewAWSError("VersionsLimitExceededException", "The maximum number of versions has been exceeded.", 413)
	ErrServiceQuotaExceeded       = awserrors.NewAWSError("ServiceQuotaExceededException", "The service quota has been exceeded.", 402)
)
