// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: storage_neptune.proto

package storage_neptune

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerlessV2ScalingConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinCapacity   float64                `protobuf:"fixed64,1,opt,name=min_capacity,json=minCapacity,proto3" json:"min_capacity,omitempty"`
	MaxCapacity   float64                `protobuf:"fixed64,2,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerlessV2ScalingConfiguration) Reset() {
	*x = ServerlessV2ScalingConfiguration{}
	mi := &file_storage_neptune_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerlessV2ScalingConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerlessV2ScalingConfiguration) ProtoMessage() {}

func (x *ServerlessV2ScalingConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerlessV2ScalingConfiguration.ProtoReflect.Descriptor instead.
func (*ServerlessV2ScalingConfiguration) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{0}
}

func (x *ServerlessV2ScalingConfiguration) GetMinCapacity() float64 {
	if x != nil {
		return x.MinCapacity
	}
	return 0
}

func (x *ServerlessV2ScalingConfiguration) GetMaxCapacity() float64 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

type DBClusterRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleArn       string                 `protobuf:"bytes,1,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	FeatureName   string                 `protobuf:"bytes,2,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBClusterRole) Reset() {
	*x = DBClusterRole{}
	mi := &file_storage_neptune_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBClusterRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBClusterRole) ProtoMessage() {}

func (x *DBClusterRole) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBClusterRole.ProtoReflect.Descriptor instead.
func (*DBClusterRole) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{1}
}

func (x *DBClusterRole) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *DBClusterRole) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *DBClusterRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DBCluster struct {
	state                            protoimpl.MessageState            `protogen:"open.v1"`
	DbClusterIdentifier              string                            `protobuf:"bytes,1,opt,name=db_cluster_identifier,json=dbClusterIdentifier,proto3" json:"db_cluster_identifier,omitempty"`
	Engine                           string                            `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`
	EngineVersion                    string                            `protobuf:"bytes,3,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	Status                           string                            `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	MasterUsername                   string                            `protobuf:"bytes,5,opt,name=master_username,json=masterUsername,proto3" json:"master_username,omitempty"`
	DatabaseName                     string                            `protobuf:"bytes,6,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Port                             int32                             `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	BackupRetentionPeriod            int32                             `protobuf:"varint,8,opt,name=backup_retention_period,json=backupRetentionPeriod,proto3" json:"backup_retention_period,omitempty"`
	PreferredBackupWindow            string                            `protobuf:"bytes,9,opt,name=preferred_backup_window,json=preferredBackupWindow,proto3" json:"preferred_backup_window,omitempty"`
	PreferredMaintenanceWindow       string                            `protobuf:"bytes,10,opt,name=preferred_maintenance_window,json=preferredMaintenanceWindow,proto3" json:"preferred_maintenance_window,omitempty"`
	AvailabilityZones                []string                          `protobuf:"bytes,11,rep,name=availability_zones,json=availabilityZones,proto3" json:"availability_zones,omitempty"`
	MultiAz                          bool                              `protobuf:"varint,12,opt,name=multi_az,json=multiAz,proto3" json:"multi_az,omitempty"`
	VpcSecurityGroupIds              []string                          `protobuf:"bytes,13,rep,name=vpc_security_group_ids,json=vpcSecurityGroupIds,proto3" json:"vpc_security_group_ids,omitempty"`
	DbSubnetGroupName                string                            `protobuf:"bytes,14,opt,name=db_subnet_group_name,json=dbSubnetGroupName,proto3" json:"db_subnet_group_name,omitempty"`
	DbClusterParameterGroupName      string                            `protobuf:"bytes,15,opt,name=db_cluster_parameter_group_name,json=dbClusterParameterGroupName,proto3" json:"db_cluster_parameter_group_name,omitempty"`
	StorageEncrypted                 bool                              `protobuf:"varint,16,opt,name=storage_encrypted,json=storageEncrypted,proto3" json:"storage_encrypted,omitempty"`
	KmsKeyId                         string                            `protobuf:"bytes,17,opt,name=kms_key_id,json=kmsKeyId,proto3" json:"kms_key_id,omitempty"`
	CopyTagsToSnapshot               bool                              `protobuf:"varint,18,opt,name=copy_tags_to_snapshot,json=copyTagsToSnapshot,proto3" json:"copy_tags_to_snapshot,omitempty"`
	DeletionProtection               bool                              `protobuf:"varint,19,opt,name=deletion_protection,json=deletionProtection,proto3" json:"deletion_protection,omitempty"`
	EnableCloudwatchLogsExports      []string                          `protobuf:"bytes,20,rep,name=enable_cloudwatch_logs_exports,json=enableCloudwatchLogsExports,proto3" json:"enable_cloudwatch_logs_exports,omitempty"`
	EnableIamDatabaseAuthentication  bool                              `protobuf:"varint,21,opt,name=enable_iam_database_authentication,json=enableIamDatabaseAuthentication,proto3" json:"enable_iam_database_authentication,omitempty"`
	ClusterCreateTime                *timestamppb.Timestamp            `protobuf:"bytes,22,opt,name=cluster_create_time,json=clusterCreateTime,proto3" json:"cluster_create_time,omitempty"`
	EarliestRestorableTime           *timestamppb.Timestamp            `protobuf:"bytes,23,opt,name=earliest_restorable_time,json=earliestRestorableTime,proto3" json:"earliest_restorable_time,omitempty"`
	LatestRestorableTime             *timestamppb.Timestamp            `protobuf:"bytes,24,opt,name=latest_restorable_time,json=latestRestorableTime,proto3" json:"latest_restorable_time,omitempty"`
	AssociatedRoles                  []*DBClusterRole                  `protobuf:"bytes,25,rep,name=associated_roles,json=associatedRoles,proto3" json:"associated_roles,omitempty"`
	ReplicationSourceIdentifier      string                            `protobuf:"bytes,26,opt,name=replication_source_identifier,json=replicationSourceIdentifier,proto3" json:"replication_source_identifier,omitempty"`
	GlobalClusterIdentifier          string                            `protobuf:"bytes,27,opt,name=global_cluster_identifier,json=globalClusterIdentifier,proto3" json:"global_cluster_identifier,omitempty"`
	StorageType                      string                            `protobuf:"bytes,28,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	ServerlessV2ScalingConfiguration *ServerlessV2ScalingConfiguration `protobuf:"bytes,29,opt,name=serverless_v2_scaling_configuration,json=serverlessV2ScalingConfiguration,proto3" json:"serverless_v2_scaling_configuration,omitempty"`
	AccountId                        string                            `protobuf:"bytes,30,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Region                           string                            `protobuf:"bytes,31,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DBCluster) Reset() {
	*x = DBCluster{}
	mi := &file_storage_neptune_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBCluster) ProtoMessage() {}

func (x *DBCluster) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBCluster.ProtoReflect.Descriptor instead.
func (*DBCluster) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{2}
}

func (x *DBCluster) GetDbClusterIdentifier() string {
	if x != nil {
		return x.DbClusterIdentifier
	}
	return ""
}

func (x *DBCluster) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *DBCluster) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *DBCluster) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DBCluster) GetMasterUsername() string {
	if x != nil {
		return x.MasterUsername
	}
	return ""
}

func (x *DBCluster) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DBCluster) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DBCluster) GetBackupRetentionPeriod() int32 {
	if x != nil {
		return x.BackupRetentionPeriod
	}
	return 0
}

func (x *DBCluster) GetPreferredBackupWindow() string {
	if x != nil {
		return x.PreferredBackupWindow
	}
	return ""
}

func (x *DBCluster) GetPreferredMaintenanceWindow() string {
	if x != nil {
		return x.PreferredMaintenanceWindow
	}
	return ""
}

func (x *DBCluster) GetAvailabilityZones() []string {
	if x != nil {
		return x.AvailabilityZones
	}
	return nil
}

func (x *DBCluster) GetMultiAz() bool {
	if x != nil {
		return x.MultiAz
	}
	return false
}

func (x *DBCluster) GetVpcSecurityGroupIds() []string {
	if x != nil {
		return x.VpcSecurityGroupIds
	}
	return nil
}

func (x *DBCluster) GetDbSubnetGroupName() string {
	if x != nil {
		return x.DbSubnetGroupName
	}
	return ""
}

func (x *DBCluster) GetDbClusterParameterGroupName() string {
	if x != nil {
		return x.DbClusterParameterGroupName
	}
	return ""
}

func (x *DBCluster) GetStorageEncrypted() bool {
	if x != nil {
		return x.StorageEncrypted
	}
	return false
}

func (x *DBCluster) GetKmsKeyId() string {
	if x != nil {
		return x.KmsKeyId
	}
	return ""
}

func (x *DBCluster) GetCopyTagsToSnapshot() bool {
	if x != nil {
		return x.CopyTagsToSnapshot
	}
	return false
}

func (x *DBCluster) GetDeletionProtection() bool {
	if x != nil {
		return x.DeletionProtection
	}
	return false
}

func (x *DBCluster) GetEnableCloudwatchLogsExports() []string {
	if x != nil {
		return x.EnableCloudwatchLogsExports
	}
	return nil
}

func (x *DBCluster) GetEnableIamDatabaseAuthentication() bool {
	if x != nil {
		return x.EnableIamDatabaseAuthentication
	}
	return false
}

func (x *DBCluster) GetClusterCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClusterCreateTime
	}
	return nil
}

func (x *DBCluster) GetEarliestRestorableTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EarliestRestorableTime
	}
	return nil
}

func (x *DBCluster) GetLatestRestorableTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestRestorableTime
	}
	return nil
}

func (x *DBCluster) GetAssociatedRoles() []*DBClusterRole {
	if x != nil {
		return x.AssociatedRoles
	}
	return nil
}

func (x *DBCluster) GetReplicationSourceIdentifier() string {
	if x != nil {
		return x.ReplicationSourceIdentifier
	}
	return ""
}

func (x *DBCluster) GetGlobalClusterIdentifier() string {
	if x != nil {
		return x.GlobalClusterIdentifier
	}
	return ""
}

func (x *DBCluster) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *DBCluster) GetServerlessV2ScalingConfiguration() *ServerlessV2ScalingConfiguration {
	if x != nil {
		return x.ServerlessV2ScalingConfiguration
	}
	return nil
}

func (x *DBCluster) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DBCluster) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type DBInstance struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	DbInstanceIdentifier            string                 `protobuf:"bytes,1,opt,name=db_instance_identifier,json=dbInstanceIdentifier,proto3" json:"db_instance_identifier,omitempty"`
	DbClusterIdentifier             string                 `protobuf:"bytes,2,opt,name=db_cluster_identifier,json=dbClusterIdentifier,proto3" json:"db_cluster_identifier,omitempty"`
	Engine                          string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	EngineVersion                   string                 `protobuf:"bytes,4,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	DbInstanceClass                 string                 `protobuf:"bytes,5,opt,name=db_instance_class,json=dbInstanceClass,proto3" json:"db_instance_class,omitempty"`
	Status                          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AvailabilityZone                string                 `protobuf:"bytes,7,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	PreferredMaintenanceWindow      string                 `protobuf:"bytes,8,opt,name=preferred_maintenance_window,json=preferredMaintenanceWindow,proto3" json:"preferred_maintenance_window,omitempty"`
	DbParameterGroupName            string                 `protobuf:"bytes,9,opt,name=db_parameter_group_name,json=dbParameterGroupName,proto3" json:"db_parameter_group_name,omitempty"`
	DbSecurityGroups                []string               `protobuf:"bytes,10,rep,name=db_security_groups,json=dbSecurityGroups,proto3" json:"db_security_groups,omitempty"`
	VpcSecurityGroupIds             []string               `protobuf:"bytes,11,rep,name=vpc_security_group_ids,json=vpcSecurityGroupIds,proto3" json:"vpc_security_group_ids,omitempty"`
	DbSubnetGroupName               string                 `protobuf:"bytes,12,opt,name=db_subnet_group_name,json=dbSubnetGroupName,proto3" json:"db_subnet_group_name,omitempty"`
	EnableCloudwatchLogsExports     []string               `protobuf:"bytes,13,rep,name=enable_cloudwatch_logs_exports,json=enableCloudwatchLogsExports,proto3" json:"enable_cloudwatch_logs_exports,omitempty"`
	EnableIamDatabaseAuthentication bool                   `protobuf:"varint,14,opt,name=enable_iam_database_authentication,json=enableIamDatabaseAuthentication,proto3" json:"enable_iam_database_authentication,omitempty"`
	PubliclyAccessible              bool                   `protobuf:"varint,15,opt,name=publicly_accessible,json=publiclyAccessible,proto3" json:"publicly_accessible,omitempty"`
	AutoMinorVersionUpgrade         bool                   `protobuf:"varint,16,opt,name=auto_minor_version_upgrade,json=autoMinorVersionUpgrade,proto3" json:"auto_minor_version_upgrade,omitempty"`
	InstanceCreateTime              *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=instance_create_time,json=instanceCreateTime,proto3" json:"instance_create_time,omitempty"`
	CopyTagsToSnapshot              bool                   `protobuf:"varint,18,opt,name=copy_tags_to_snapshot,json=copyTagsToSnapshot,proto3" json:"copy_tags_to_snapshot,omitempty"`
	AccountId                       string                 `protobuf:"bytes,19,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Region                          string                 `protobuf:"bytes,20,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *DBInstance) Reset() {
	*x = DBInstance{}
	mi := &file_storage_neptune_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBInstance) ProtoMessage() {}

func (x *DBInstance) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBInstance.ProtoReflect.Descriptor instead.
func (*DBInstance) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{3}
}

func (x *DBInstance) GetDbInstanceIdentifier() string {
	if x != nil {
		return x.DbInstanceIdentifier
	}
	return ""
}

func (x *DBInstance) GetDbClusterIdentifier() string {
	if x != nil {
		return x.DbClusterIdentifier
	}
	return ""
}

func (x *DBInstance) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *DBInstance) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *DBInstance) GetDbInstanceClass() string {
	if x != nil {
		return x.DbInstanceClass
	}
	return ""
}

func (x *DBInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DBInstance) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *DBInstance) GetPreferredMaintenanceWindow() string {
	if x != nil {
		return x.PreferredMaintenanceWindow
	}
	return ""
}

func (x *DBInstance) GetDbParameterGroupName() string {
	if x != nil {
		return x.DbParameterGroupName
	}
	return ""
}

func (x *DBInstance) GetDbSecurityGroups() []string {
	if x != nil {
		return x.DbSecurityGroups
	}
	return nil
}

func (x *DBInstance) GetVpcSecurityGroupIds() []string {
	if x != nil {
		return x.VpcSecurityGroupIds
	}
	return nil
}

func (x *DBInstance) GetDbSubnetGroupName() string {
	if x != nil {
		return x.DbSubnetGroupName
	}
	return ""
}

func (x *DBInstance) GetEnableCloudwatchLogsExports() []string {
	if x != nil {
		return x.EnableCloudwatchLogsExports
	}
	return nil
}

func (x *DBInstance) GetEnableIamDatabaseAuthentication() bool {
	if x != nil {
		return x.EnableIamDatabaseAuthentication
	}
	return false
}

func (x *DBInstance) GetPubliclyAccessible() bool {
	if x != nil {
		return x.PubliclyAccessible
	}
	return false
}

func (x *DBInstance) GetAutoMinorVersionUpgrade() bool {
	if x != nil {
		return x.AutoMinorVersionUpgrade
	}
	return false
}

func (x *DBInstance) GetInstanceCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.InstanceCreateTime
	}
	return nil
}

func (x *DBInstance) GetCopyTagsToSnapshot() bool {
	if x != nil {
		return x.CopyTagsToSnapshot
	}
	return false
}

func (x *DBInstance) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DBInstance) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type DBClusterSnapshot struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	DbClusterSnapshotIdentifier string                 `protobuf:"bytes,1,opt,name=db_cluster_snapshot_identifier,json=dbClusterSnapshotIdentifier,proto3" json:"db_cluster_snapshot_identifier,omitempty"`
	DbClusterIdentifier         string                 `protobuf:"bytes,2,opt,name=db_cluster_identifier,json=dbClusterIdentifier,proto3" json:"db_cluster_identifier,omitempty"`
	SnapshotCreateTime          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=snapshot_create_time,json=snapshotCreateTime,proto3" json:"snapshot_create_time,omitempty"`
	Engine                      string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	EngineVersion               string                 `protobuf:"bytes,5,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	Status                      string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Port                        int32                  `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	VpcId                       string                 `protobuf:"bytes,8,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	ClusterCreateTime           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=cluster_create_time,json=clusterCreateTime,proto3" json:"cluster_create_time,omitempty"`
	StorageEncrypted            bool                   `protobuf:"varint,10,opt,name=storage_encrypted,json=storageEncrypted,proto3" json:"storage_encrypted,omitempty"`
	KmsKeyId                    string                 `protobuf:"bytes,11,opt,name=kms_key_id,json=kmsKeyId,proto3" json:"kms_key_id,omitempty"`
	DbSnapshotArn               string                 `protobuf:"bytes,12,opt,name=db_snapshot_arn,json=dbSnapshotArn,proto3" json:"db_snapshot_arn,omitempty"`
	AccountId                   string                 `protobuf:"bytes,13,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Region                      string                 `protobuf:"bytes,14,opt,name=region,proto3" json:"region,omitempty"`
	RestoreAttributeValues      []string               `protobuf:"bytes,15,rep,name=restore_attribute_values,json=restoreAttributeValues,proto3" json:"restore_attribute_values,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DBClusterSnapshot) Reset() {
	*x = DBClusterSnapshot{}
	mi := &file_storage_neptune_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBClusterSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBClusterSnapshot) ProtoMessage() {}

func (x *DBClusterSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBClusterSnapshot.ProtoReflect.Descriptor instead.
func (*DBClusterSnapshot) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{4}
}

func (x *DBClusterSnapshot) GetDbClusterSnapshotIdentifier() string {
	if x != nil {
		return x.DbClusterSnapshotIdentifier
	}
	return ""
}

func (x *DBClusterSnapshot) GetDbClusterIdentifier() string {
	if x != nil {
		return x.DbClusterIdentifier
	}
	return ""
}

func (x *DBClusterSnapshot) GetSnapshotCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotCreateTime
	}
	return nil
}

func (x *DBClusterSnapshot) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *DBClusterSnapshot) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *DBClusterSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DBClusterSnapshot) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DBClusterSnapshot) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *DBClusterSnapshot) GetClusterCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClusterCreateTime
	}
	return nil
}

func (x *DBClusterSnapshot) GetStorageEncrypted() bool {
	if x != nil {
		return x.StorageEncrypted
	}
	return false
}

func (x *DBClusterSnapshot) GetKmsKeyId() string {
	if x != nil {
		return x.KmsKeyId
	}
	return ""
}

func (x *DBClusterSnapshot) GetDbSnapshotArn() string {
	if x != nil {
		return x.DbSnapshotArn
	}
	return ""
}

func (x *DBClusterSnapshot) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DBClusterSnapshot) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DBClusterSnapshot) GetRestoreAttributeValues() []string {
	if x != nil {
		return x.RestoreAttributeValues
	}
	return nil
}

type DBClusterParameterGroup struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	DbClusterParameterGroupName string                 `protobuf:"bytes,1,opt,name=db_cluster_parameter_group_name,json=dbClusterParameterGroupName,proto3" json:"db_cluster_parameter_group_name,omitempty"`
	DbParameterGroupFamily      string                 `protobuf:"bytes,2,opt,name=db_parameter_group_family,json=dbParameterGroupFamily,proto3" json:"db_parameter_group_family,omitempty"`
	Description                 string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Arn                         string                 `protobuf:"bytes,4,opt,name=arn,proto3" json:"arn,omitempty"`
	Parameters                  []*Parameter           `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DBClusterParameterGroup) Reset() {
	*x = DBClusterParameterGroup{}
	mi := &file_storage_neptune_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBClusterParameterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBClusterParameterGroup) ProtoMessage() {}

func (x *DBClusterParameterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBClusterParameterGroup.ProtoReflect.Descriptor instead.
func (*DBClusterParameterGroup) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{5}
}

func (x *DBClusterParameterGroup) GetDbClusterParameterGroupName() string {
	if x != nil {
		return x.DbClusterParameterGroupName
	}
	return ""
}

func (x *DBClusterParameterGroup) GetDbParameterGroupFamily() string {
	if x != nil {
		return x.DbParameterGroupFamily
	}
	return ""
}

func (x *DBClusterParameterGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DBClusterParameterGroup) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

func (x *DBClusterParameterGroup) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DBParameterGroup struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DbParameterGroupName   string                 `protobuf:"bytes,1,opt,name=db_parameter_group_name,json=dbParameterGroupName,proto3" json:"db_parameter_group_name,omitempty"`
	DbParameterGroupFamily string                 `protobuf:"bytes,2,opt,name=db_parameter_group_family,json=dbParameterGroupFamily,proto3" json:"db_parameter_group_family,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Arn                    string                 `protobuf:"bytes,4,opt,name=arn,proto3" json:"arn,omitempty"`
	Parameters             []*Parameter           `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DBParameterGroup) Reset() {
	*x = DBParameterGroup{}
	mi := &file_storage_neptune_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBParameterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBParameterGroup) ProtoMessage() {}

func (x *DBParameterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBParameterGroup.ProtoReflect.Descriptor instead.
func (*DBParameterGroup) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{6}
}

func (x *DBParameterGroup) GetDbParameterGroupName() string {
	if x != nil {
		return x.DbParameterGroupName
	}
	return ""
}

func (x *DBParameterGroup) GetDbParameterGroupFamily() string {
	if x != nil {
		return x.DbParameterGroupFamily
	}
	return ""
}

func (x *DBParameterGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DBParameterGroup) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

func (x *DBParameterGroup) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Subnet struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SubnetIdentifier       string                 `protobuf:"bytes,1,opt,name=subnet_identifier,json=subnetIdentifier,proto3" json:"subnet_identifier,omitempty"`
	SubnetAvailabilityZone string                 `protobuf:"bytes,2,opt,name=subnet_availability_zone,json=subnetAvailabilityZone,proto3" json:"subnet_availability_zone,omitempty"`
	SubnetOutpost          string                 `protobuf:"bytes,3,opt,name=subnet_outpost,json=subnetOutpost,proto3" json:"subnet_outpost,omitempty"`
	SubnetStatus           string                 `protobuf:"bytes,4,opt,name=subnet_status,json=subnetStatus,proto3" json:"subnet_status,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Subnet) Reset() {
	*x = Subnet{}
	mi := &file_storage_neptune_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet) ProtoMessage() {}

func (x *Subnet) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnet.ProtoReflect.Descriptor instead.
func (*Subnet) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{7}
}

func (x *Subnet) GetSubnetIdentifier() string {
	if x != nil {
		return x.SubnetIdentifier
	}
	return ""
}

func (x *Subnet) GetSubnetAvailabilityZone() string {
	if x != nil {
		return x.SubnetAvailabilityZone
	}
	return ""
}

func (x *Subnet) GetSubnetOutpost() string {
	if x != nil {
		return x.SubnetOutpost
	}
	return ""
}

func (x *Subnet) GetSubnetStatus() string {
	if x != nil {
		return x.SubnetStatus
	}
	return ""
}

type DBSubnetGroup struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DbSubnetGroupName        string                 `protobuf:"bytes,1,opt,name=db_subnet_group_name,json=dbSubnetGroupName,proto3" json:"db_subnet_group_name,omitempty"`
	DbSubnetGroupDescription string                 `protobuf:"bytes,2,opt,name=db_subnet_group_description,json=dbSubnetGroupDescription,proto3" json:"db_subnet_group_description,omitempty"`
	VpcId                    string                 `protobuf:"bytes,3,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	SubnetGroupStatus        string                 `protobuf:"bytes,4,opt,name=subnet_group_status,json=subnetGroupStatus,proto3" json:"subnet_group_status,omitempty"`
	Subnets                  []*Subnet              `protobuf:"bytes,5,rep,name=subnets,proto3" json:"subnets,omitempty"`
	Arn                      string                 `protobuf:"bytes,6,opt,name=arn,proto3" json:"arn,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DBSubnetGroup) Reset() {
	*x = DBSubnetGroup{}
	mi := &file_storage_neptune_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBSubnetGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBSubnetGroup) ProtoMessage() {}

func (x *DBSubnetGroup) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBSubnetGroup.ProtoReflect.Descriptor instead.
func (*DBSubnetGroup) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{8}
}

func (x *DBSubnetGroup) GetDbSubnetGroupName() string {
	if x != nil {
		return x.DbSubnetGroupName
	}
	return ""
}

func (x *DBSubnetGroup) GetDbSubnetGroupDescription() string {
	if x != nil {
		return x.DbSubnetGroupDescription
	}
	return ""
}

func (x *DBSubnetGroup) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *DBSubnetGroup) GetSubnetGroupStatus() string {
	if x != nil {
		return x.SubnetGroupStatus
	}
	return ""
}

func (x *DBSubnetGroup) GetSubnets() []*Subnet {
	if x != nil {
		return x.Subnets
	}
	return nil
}

func (x *DBSubnetGroup) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

type GlobalClusterMember struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DbClusterArn            string                 `protobuf:"bytes,1,opt,name=db_cluster_arn,json=dbClusterArn,proto3" json:"db_cluster_arn,omitempty"`
	Readers                 []string               `protobuf:"bytes,2,rep,name=readers,proto3" json:"readers,omitempty"`
	IsWriter                bool                   `protobuf:"varint,3,opt,name=is_writer,json=isWriter,proto3" json:"is_writer,omitempty"`
	GlobalClusterIdentifier string                 `protobuf:"bytes,4,opt,name=global_cluster_identifier,json=globalClusterIdentifier,proto3" json:"global_cluster_identifier,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GlobalClusterMember) Reset() {
	*x = GlobalClusterMember{}
	mi := &file_storage_neptune_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalClusterMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalClusterMember) ProtoMessage() {}

func (x *GlobalClusterMember) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalClusterMember.ProtoReflect.Descriptor instead.
func (*GlobalClusterMember) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{9}
}

func (x *GlobalClusterMember) GetDbClusterArn() string {
	if x != nil {
		return x.DbClusterArn
	}
	return ""
}

func (x *GlobalClusterMember) GetReaders() []string {
	if x != nil {
		return x.Readers
	}
	return nil
}

func (x *GlobalClusterMember) GetIsWriter() bool {
	if x != nil {
		return x.IsWriter
	}
	return false
}

func (x *GlobalClusterMember) GetGlobalClusterIdentifier() string {
	if x != nil {
		return x.GlobalClusterIdentifier
	}
	return ""
}

type GlobalCluster struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	GlobalClusterIdentifier string                 `protobuf:"bytes,1,opt,name=global_cluster_identifier,json=globalClusterIdentifier,proto3" json:"global_cluster_identifier,omitempty"`
	GlobalClusterResourceId string                 `protobuf:"bytes,2,opt,name=global_cluster_resource_id,json=globalClusterResourceId,proto3" json:"global_cluster_resource_id,omitempty"`
	GlobalClusterArn        string                 `protobuf:"bytes,3,opt,name=global_cluster_arn,json=globalClusterArn,proto3" json:"global_cluster_arn,omitempty"`
	Engine                  string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	EngineVersion           string                 `protobuf:"bytes,5,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	Status                  string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StorageEncrypted        bool                   `protobuf:"varint,7,opt,name=storage_encrypted,json=storageEncrypted,proto3" json:"storage_encrypted,omitempty"`
	DeletionProtection      bool                   `protobuf:"varint,8,opt,name=deletion_protection,json=deletionProtection,proto3" json:"deletion_protection,omitempty"`
	GlobalClusterMembers    []*GlobalClusterMember `protobuf:"bytes,9,rep,name=global_cluster_members,json=globalClusterMembers,proto3" json:"global_cluster_members,omitempty"`
	AccountId               string                 `protobuf:"bytes,10,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Region                  string                 `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GlobalCluster) Reset() {
	*x = GlobalCluster{}
	mi := &file_storage_neptune_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalCluster) ProtoMessage() {}

func (x *GlobalCluster) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalCluster.ProtoReflect.Descriptor instead.
func (*GlobalCluster) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{10}
}

func (x *GlobalCluster) GetGlobalClusterIdentifier() string {
	if x != nil {
		return x.GlobalClusterIdentifier
	}
	return ""
}

func (x *GlobalCluster) GetGlobalClusterResourceId() string {
	if x != nil {
		return x.GlobalClusterResourceId
	}
	return ""
}

func (x *GlobalCluster) GetGlobalClusterArn() string {
	if x != nil {
		return x.GlobalClusterArn
	}
	return ""
}

func (x *GlobalCluster) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *GlobalCluster) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *GlobalCluster) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GlobalCluster) GetStorageEncrypted() bool {
	if x != nil {
		return x.StorageEncrypted
	}
	return false
}

func (x *GlobalCluster) GetDeletionProtection() bool {
	if x != nil {
		return x.DeletionProtection
	}
	return false
}

func (x *GlobalCluster) GetGlobalClusterMembers() []*GlobalClusterMember {
	if x != nil {
		return x.GlobalClusterMembers
	}
	return nil
}

func (x *GlobalCluster) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GlobalCluster) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type EventSubscription struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CustSubscriptionId       string                 `protobuf:"bytes,1,opt,name=cust_subscription_id,json=custSubscriptionId,proto3" json:"cust_subscription_id,omitempty"`
	SnsTopicArn              string                 `protobuf:"bytes,2,opt,name=sns_topic_arn,json=snsTopicArn,proto3" json:"sns_topic_arn,omitempty"`
	Status                   string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SubscriptionCreationTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=subscription_creation_time,json=subscriptionCreationTime,proto3" json:"subscription_creation_time,omitempty"`
	SourceType               string                 `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceIdsList            []string               `protobuf:"bytes,6,rep,name=source_ids_list,json=sourceIdsList,proto3" json:"source_ids_list,omitempty"`
	EventCategoriesList      []string               `protobuf:"bytes,7,rep,name=event_categories_list,json=eventCategoriesList,proto3" json:"event_categories_list,omitempty"`
	Enabled                  bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CustSubscriptionArn      string                 `protobuf:"bytes,9,opt,name=cust_subscription_arn,json=custSubscriptionArn,proto3" json:"cust_subscription_arn,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EventSubscription) Reset() {
	*x = EventSubscription{}
	mi := &file_storage_neptune_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscription) ProtoMessage() {}

func (x *EventSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscription.ProtoReflect.Descriptor instead.
func (*EventSubscription) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{11}
}

func (x *EventSubscription) GetCustSubscriptionId() string {
	if x != nil {
		return x.CustSubscriptionId
	}
	return ""
}

func (x *EventSubscription) GetSnsTopicArn() string {
	if x != nil {
		return x.SnsTopicArn
	}
	return ""
}

func (x *EventSubscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventSubscription) GetSubscriptionCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionCreationTime
	}
	return nil
}

func (x *EventSubscription) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *EventSubscription) GetSourceIdsList() []string {
	if x != nil {
		return x.SourceIdsList
	}
	return nil
}

func (x *EventSubscription) GetEventCategoriesList() []string {
	if x != nil {
		return x.EventCategoriesList
	}
	return nil
}

func (x *EventSubscription) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EventSubscription) GetCustSubscriptionArn() string {
	if x != nil {
		return x.CustSubscriptionArn
	}
	return ""
}

type Parameter struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ParameterName        string                 `protobuf:"bytes,1,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	ParameterValue       string                 `protobuf:"bytes,2,opt,name=parameter_value,json=parameterValue,proto3" json:"parameter_value,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Source               string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	ApplyType            string                 `protobuf:"bytes,5,opt,name=apply_type,json=applyType,proto3" json:"apply_type,omitempty"`
	DataType             string                 `protobuf:"bytes,6,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	AllowedValues        string                 `protobuf:"bytes,7,opt,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"`
	IsModifiable         bool                   `protobuf:"varint,8,opt,name=is_modifiable,json=isModifiable,proto3" json:"is_modifiable,omitempty"`
	MinimumEngineVersion string                 `protobuf:"bytes,9,opt,name=minimum_engine_version,json=minimumEngineVersion,proto3" json:"minimum_engine_version,omitempty"`
	ApplyMethod          string                 `protobuf:"bytes,10,opt,name=apply_method,json=applyMethod,proto3" json:"apply_method,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_storage_neptune_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{12}
}

func (x *Parameter) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

func (x *Parameter) GetParameterValue() string {
	if x != nil {
		return x.ParameterValue
	}
	return ""
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Parameter) GetApplyType() string {
	if x != nil {
		return x.ApplyType
	}
	return ""
}

func (x *Parameter) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Parameter) GetAllowedValues() string {
	if x != nil {
		return x.AllowedValues
	}
	return ""
}

func (x *Parameter) GetIsModifiable() bool {
	if x != nil {
		return x.IsModifiable
	}
	return false
}

func (x *Parameter) GetMinimumEngineVersion() string {
	if x != nil {
		return x.MinimumEngineVersion
	}
	return ""
}

func (x *Parameter) GetApplyMethod() string {
	if x != nil {
		return x.ApplyMethod
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_storage_neptune_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{13}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TagList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagList) Reset() {
	*x = TagList{}
	mi := &file_storage_neptune_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagList) ProtoMessage() {}

func (x *TagList) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagList.ProtoReflect.Descriptor instead.
func (*TagList) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{14}
}

func (x *TagList) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DBClusterEndpoint struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	DbClusterEndpointIdentifier string                 `protobuf:"bytes,1,opt,name=db_cluster_endpoint_identifier,json=dbClusterEndpointIdentifier,proto3" json:"db_cluster_endpoint_identifier,omitempty"`
	DbClusterIdentifier         string                 `protobuf:"bytes,2,opt,name=db_cluster_identifier,json=dbClusterIdentifier,proto3" json:"db_cluster_identifier,omitempty"`
	Endpoint                    string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Status                      string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	EndpointType                string                 `protobuf:"bytes,5,opt,name=endpoint_type,json=endpointType,proto3" json:"endpoint_type,omitempty"`
	ExcludedMembers             []string               `protobuf:"bytes,6,rep,name=excluded_members,json=excludedMembers,proto3" json:"excluded_members,omitempty"`
	StaticMembers               []string               `protobuf:"bytes,7,rep,name=static_members,json=staticMembers,proto3" json:"static_members,omitempty"`
	DbClusterEndpointArn        string                 `protobuf:"bytes,8,opt,name=db_cluster_endpoint_arn,json=dbClusterEndpointArn,proto3" json:"db_cluster_endpoint_arn,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DBClusterEndpoint) Reset() {
	*x = DBClusterEndpoint{}
	mi := &file_storage_neptune_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBClusterEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBClusterEndpoint) ProtoMessage() {}

func (x *DBClusterEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBClusterEndpoint.ProtoReflect.Descriptor instead.
func (*DBClusterEndpoint) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{15}
}

func (x *DBClusterEndpoint) GetDbClusterEndpointIdentifier() string {
	if x != nil {
		return x.DbClusterEndpointIdentifier
	}
	return ""
}

func (x *DBClusterEndpoint) GetDbClusterIdentifier() string {
	if x != nil {
		return x.DbClusterIdentifier
	}
	return ""
}

func (x *DBClusterEndpoint) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DBClusterEndpoint) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DBClusterEndpoint) GetEndpointType() string {
	if x != nil {
		return x.EndpointType
	}
	return ""
}

func (x *DBClusterEndpoint) GetExcludedMembers() []string {
	if x != nil {
		return x.ExcludedMembers
	}
	return nil
}

func (x *DBClusterEndpoint) GetStaticMembers() []string {
	if x != nil {
		return x.StaticMembers
	}
	return nil
}

func (x *DBClusterEndpoint) GetDbClusterEndpointArn() string {
	if x != nil {
		return x.DbClusterEndpointArn
	}
	return ""
}

type QueryState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	QueryType     string                 `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	QueryString   string                 `protobuf:"bytes,3,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Result        string                 `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryState) Reset() {
	*x = QueryState{}
	mi := &file_storage_neptune_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryState) ProtoMessage() {}

func (x *QueryState) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryState.ProtoReflect.Descriptor instead.
func (*QueryState) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{16}
}

func (x *QueryState) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryState) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *QueryState) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *QueryState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryState) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryState) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryState) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *QueryState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoaderJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadId        string                 `protobuf:"bytes,1,opt,name=load_id,json=loadId,proto3" json:"load_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	SubmitTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,7,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	TotalErrors   int64                  `protobuf:"varint,8,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	OverallStatus string                 `protobuf:"bytes,9,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,10,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoaderJob) Reset() {
	*x = LoaderJob{}
	mi := &file_storage_neptune_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoaderJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoaderJob) ProtoMessage() {}

func (x *LoaderJob) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoaderJob.ProtoReflect.Descriptor instead.
func (*LoaderJob) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{17}
}

func (x *LoaderJob) GetLoadId() string {
	if x != nil {
		return x.LoadId
	}
	return ""
}

func (x *LoaderJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoaderJob) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LoaderJob) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *LoaderJob) GetSubmitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmitTime
	}
	return nil
}

func (x *LoaderJob) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *LoaderJob) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *LoaderJob) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *LoaderJob) GetOverallStatus() string {
	if x != nil {
		return x.OverallStatus
	}
	return ""
}

func (x *LoaderJob) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type GraphStatistics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Active         bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	AutoCompute    bool                   `protobuf:"varint,2,opt,name=auto_compute,json=autoCompute,proto3" json:"auto_compute,omitempty"`
	Date           string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Note           string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	StatisticsId   string                 `protobuf:"bytes,5,opt,name=statistics_id,json=statisticsId,proto3" json:"statistics_id,omitempty"`
	NodeCount      int64                  `protobuf:"varint,6,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount      int64                  `protobuf:"varint,7,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	LabelCounts    map[string]int64       `protobuf:"bytes,8,rep,name=label_counts,json=labelCounts,proto3" json:"label_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RelCounts      map[string]int64       `protobuf:"bytes,9,rep,name=rel_counts,json=relCounts,proto3" json:"rel_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PredicateCount int64                  `protobuf:"varint,10,opt,name=predicate_count,json=predicateCount,proto3" json:"predicate_count,omitempty"`
	SignatureCount int64                  `protobuf:"varint,11,opt,name=signature_count,json=signatureCount,proto3" json:"signature_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GraphStatistics) Reset() {
	*x = GraphStatistics{}
	mi := &file_storage_neptune_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStatistics) ProtoMessage() {}

func (x *GraphStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_storage_neptune_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStatistics.ProtoReflect.Descriptor instead.
func (*GraphStatistics) Descriptor() ([]byte, []int) {
	return file_storage_neptune_proto_rawDescGZIP(), []int{18}
}

func (x *GraphStatistics) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GraphStatistics) GetAutoCompute() bool {
	if x != nil {
		return x.AutoCompute
	}
	return false
}

func (x *GraphStatistics) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GraphStatistics) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GraphStatistics) GetStatisticsId() string {
	if x != nil {
		return x.StatisticsId
	}
	return ""
}

func (x *GraphStatistics) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *GraphStatistics) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *GraphStatistics) GetLabelCounts() map[string]int64 {
	if x != nil {
		return x.LabelCounts
	}
	return nil
}

func (x *GraphStatistics) GetRelCounts() map[string]int64 {
	if x != nil {
		return x.RelCounts
	}
	return nil
}

func (x *GraphStatistics) GetPredicateCount() int64 {
	if x != nil {
		return x.PredicateCount
	}
	return 0
}

func (x *GraphStatistics) GetSignatureCount() int64 {
	if x != nil {
		return x.SignatureCount
	}
	return 0
}

var File_storage_neptune_proto protoreflect.FileDescriptor

const file_storage_neptune_proto_rawDesc = "" +
	"\n" +
	"\x15storage_neptune.proto\x12\x0fstorage.neptune\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n" +
	" ServerlessV2ScalingConfiguration\x12!\n" +
	"\fmin_capacity\x18\x01 \x01(\x01R\vminCapacity\x12!\n" +
	"\fmax_capacity\x18\x02 \x01(\x01R\vmaxCapacity\"e\n" +
	"\rDBClusterRole\x12\x19\n" +
	"\brole_arn\x18\x01 \x01(\tR\aroleArn\x12!\n" +
	"\ffeature_name\x18\x02 \x01(\tR\vfeatureName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xfd\f\n" +
	"\tDBCluster\x122\n" +
	"\x15db_cluster_identifier\x18\x01 \x01(\tR\x13dbClusterIdentifier\x12\x16\n" +
	"\x06engine\x18\x02 \x01(\tR\x06engine\x12%\n" +
	"\x0eengine_version\x18\x03 \x01(\tR\rengineVersion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fmaster_username\x18\x05 \x01(\tR\x0emasterUsername\x12#\n" +
	"\rdatabase_name\x18\x06 \x01(\tR\fdatabaseName\x12\x12\n" +
	"\x04port\x18\a \x01(\x05R\x04port\x126\n" +
	"\x17backup_retention_period\x18\b \x01(\x05R\x15backupRetentionPeriod\x126\n" +
	"\x17preferred_backup_window\x18\t \x01(\tR\x15preferredBackupWindow\x12@\n" +
	"\x1cpreferred_maintenance_window\x18\n" +
	" \x01(\tR\x1apreferredMaintenanceWindow\x12-\n" +
	"\x12availability_zones\x18\v \x03(\tR\x11availabilityZones\x12\x19\n" +
	"\bmulti_az\x18\f \x01(\bR\amultiAz\x123\n" +
	"\x16vpc_security_group_ids\x18\r \x03(\tR\x13vpcSecurityGroupIds\x12/\n" +
	"\x14db_subnet_group_name\x18\x0e \x01(\tR\x11dbSubnetGroupName\x12D\n" +
	"\x1fdb_cluster_parameter_group_name\x18\x0f \x01(\tR\x1bdbClusterParameterGroupName\x12+\n" +
	"\x11storage_encrypted\x18\x10 \x01(\bR\x10storageEncrypted\x12\x1c\n" +
	"\n" +
	"kms_key_id\x18\x11 \x01(\tR\bkmsKeyId\x121\n" +
	"\x15copy_tags_to_snapshot\x18\x12 \x01(\bR\x12copyTagsToSnapshot\x12/\n" +
	"\x13deletion_protection\x18\x13 \x01(\bR\x12deletionProtection\x12C\n" +
	"\x1eenable_cloudwatch_logs_exports\x18\x14 \x03(\tR\x1benableCloudwatchLogsExports\x12K\n" +
	"\"enable_iam_database_authentication\x18\x15 \x01(\bR\x1fenableIamDatabaseAuthentication\x12J\n" +
	"\x13cluster_create_time\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\x11clusterCreateTime\x12T\n" +
	"\x18earliest_restorable_time\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\x16earliestRestorableTime\x12P\n" +
	"\x16latest_restorable_time\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\x14latestRestorableTime\x12I\n" +
	"\x10associated_roles\x18\x19 \x03(\v2\x1e.storage.neptune.DBClusterRoleR\x0fassociatedRoles\x12B\n" +
	"\x1dreplication_source_identifier\x18\x1a \x01(\tR\x1breplicationSourceIdentifier\x12:\n" +
	"\x19global_cluster_identifier\x18\x1b \x01(\tR\x17globalClusterIdentifier\x12!\n" +
	"\fstorage_type\x18\x1c \x01(\tR\vstorageType\x12\x80\x01\n" +
	"#serverless_v2_scaling_configuration\x18\x1d \x01(\v21.storage.neptune.ServerlessV2ScalingConfigurationR serverlessV2ScalingConfiguration\x12\x1d\n" +
	"\n" +
	"account_id\x18\x1e \x01(\tR\taccountId\x12\x16\n" +
	"\x06region\x18\x1f \x01(\tR\x06region\"\xeb\a\n" +
	"\n" +
	"DBInstance\x124\n" +
	"\x16db_instance_identifier\x18\x01 \x01(\tR\x14dbInstanceIdentifier\x122\n" +
	"\x15db_cluster_identifier\x18\x02 \x01(\tR\x13dbClusterIdentifier\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\x12%\n" +
	"\x0eengine_version\x18\x04 \x01(\tR\rengineVersion\x12*\n" +
	"\x11db_instance_class\x18\x05 \x01(\tR\x0fdbInstanceClass\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12+\n" +
	"\x11availability_zone\x18\a \x01(\tR\x10availabilityZone\x12@\n" +
	"\x1cpreferred_maintenance_window\x18\b \x01(\tR\x1apreferredMaintenanceWindow\x125\n" +
	"\x17db_parameter_group_name\x18\t \x01(\tR\x14dbParameterGroupName\x12,\n" +
	"\x12db_security_groups\x18\n" +
	" \x03(\tR\x10dbSecurityGroups\x123\n" +
	"\x16vpc_security_group_ids\x18\v \x03(\tR\x13vpcSecurityGroupIds\x12/\n" +
	"\x14db_subnet_group_name\x18\f \x01(\tR\x11dbSubnetGroupName\x12C\n" +
	"\x1eenable_cloudwatch_logs_exports\x18\r \x03(\tR\x1benableCloudwatchLogsExports\x12K\n" +
	"\"enable_iam_database_authentication\x18\x0e \x01(\bR\x1fenableIamDatabaseAuthentication\x12/\n" +
	"\x13publicly_accessible\x18\x0f \x01(\bR\x12publiclyAccessible\x12;\n" +
	"\x1aauto_minor_version_upgrade\x18\x10 \x01(\bR\x17autoMinorVersionUpgrade\x12L\n" +
	"\x14instance_create_time\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x12instanceCreateTime\x121\n" +
	"\x15copy_tags_to_snapshot\x18\x12 \x01(\bR\x12copyTagsToSnapshot\x12\x1d\n" +
	"\n" +
	"account_id\x18\x13 \x01(\tR\taccountId\x12\x16\n" +
	"\x06region\x18\x14 \x01(\tR\x06region\"\x8c\x05\n" +
	"\x11DBClusterSnapshot\x12C\n" +
	"\x1edb_cluster_snapshot_identifier\x18\x01 \x01(\tR\x1bdbClusterSnapshotIdentifier\x122\n" +
	"\x15db_cluster_identifier\x18\x02 \x01(\tR\x13dbClusterIdentifier\x12L\n" +
	"\x14snapshot_create_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x12snapshotCreateTime\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12%\n" +
	"\x0eengine_version\x18\x05 \x01(\tR\rengineVersion\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04port\x18\a \x01(\x05R\x04port\x12\x15\n" +
	"\x06vpc_id\x18\b \x01(\tR\x05vpcId\x12J\n" +
	"\x13cluster_create_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x11clusterCreateTime\x12+\n" +
	"\x11storage_encrypted\x18\n" +
	" \x01(\bR\x10storageEncrypted\x12\x1c\n" +
	"\n" +
	"kms_key_id\x18\v \x01(\tR\bkmsKeyId\x12&\n" +
	"\x0fdb_snapshot_arn\x18\f \x01(\tR\rdbSnapshotArn\x12\x1d\n" +
	"\n" +
	"account_id\x18\r \x01(\tR\taccountId\x12\x16\n" +
	"\x06region\x18\x0e \x01(\tR\x06region\x128\n" +
	"\x18restore_attribute_values\x18\x0f \x03(\tR\x16restoreAttributeValues\"\x8a\x02\n" +
	"\x17DBClusterParameterGroup\x12D\n" +
	"\x1fdb_cluster_parameter_group_name\x18\x01 \x01(\tR\x1bdbClusterParameterGroupName\x129\n" +
	"\x19db_parameter_group_family\x18\x02 \x01(\tR\x16dbParameterGroupFamily\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03arn\x18\x04 \x01(\tR\x03arn\x12:\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2\x1a.storage.neptune.ParameterR\n" +
	"parameters\"\xf4\x01\n" +
	"\x10DBParameterGroup\x125\n" +
	"\x17db_parameter_group_name\x18\x01 \x01(\tR\x14dbParameterGroupName\x129\n" +
	"\x19db_parameter_group_family\x18\x02 \x01(\tR\x16dbParameterGroupFamily\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03arn\x18\x04 \x01(\tR\x03arn\x12:\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2\x1a.storage.neptune.ParameterR\n" +
	"parameters\"\xbb\x01\n" +
	"\x06Subnet\x12+\n" +
	"\x11subnet_identifier\x18\x01 \x01(\tR\x10subnetIdentifier\x128\n" +
	"\x18subnet_availability_zone\x18\x02 \x01(\tR\x16subnetAvailabilityZone\x12%\n" +
	"\x0esubnet_outpost\x18\x03 \x01(\tR\rsubnetOutpost\x12#\n" +
	"\rsubnet_status\x18\x04 \x01(\tR\fsubnetStatus\"\x8b\x02\n" +
	"\rDBSubnetGroup\x12/\n" +
	"\x14db_subnet_group_name\x18\x01 \x01(\tR\x11dbSubnetGroupName\x12=\n" +
	"\x1bdb_subnet_group_description\x18\x02 \x01(\tR\x18dbSubnetGroupDescription\x12\x15\n" +
	"\x06vpc_id\x18\x03 \x01(\tR\x05vpcId\x12.\n" +
	"\x13subnet_group_status\x18\x04 \x01(\tR\x11subnetGroupStatus\x121\n" +
	"\asubnets\x18\x05 \x03(\v2\x17.storage.neptune.SubnetR\asubnets\x12\x10\n" +
	"\x03arn\x18\x06 \x01(\tR\x03arn\"\xae\x01\n" +
	"\x13GlobalClusterMember\x12$\n" +
	"\x0edb_cluster_arn\x18\x01 \x01(\tR\fdbClusterArn\x12\x18\n" +
	"\areaders\x18\x02 \x03(\tR\areaders\x12\x1b\n" +
	"\tis_writer\x18\x03 \x01(\bR\bisWriter\x12:\n" +
	"\x19global_cluster_identifier\x18\x04 \x01(\tR\x17globalClusterIdentifier\"\xfe\x03\n" +
	"\rGlobalCluster\x12:\n" +
	"\x19global_cluster_identifier\x18\x01 \x01(\tR\x17globalClusterIdentifier\x12;\n" +
	"\x1aglobal_cluster_resource_id\x18\x02 \x01(\tR\x17globalClusterResourceId\x12,\n" +
	"\x12global_cluster_arn\x18\x03 \x01(\tR\x10globalClusterArn\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12%\n" +
	"\x0eengine_version\x18\x05 \x01(\tR\rengineVersion\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12+\n" +
	"\x11storage_encrypted\x18\a \x01(\bR\x10storageEncrypted\x12/\n" +
	"\x13deletion_protection\x18\b \x01(\bR\x12deletionProtection\x12Z\n" +
	"\x16global_cluster_members\x18\t \x03(\v2$.storage.neptune.GlobalClusterMemberR\x14globalClusterMembers\x12\x1d\n" +
	"\n" +
	"account_id\x18\n" +
	" \x01(\tR\taccountId\x12\x16\n" +
	"\x06region\x18\v \x01(\tR\x06region\"\xa6\x03\n" +
	"\x11EventSubscription\x120\n" +
	"\x14cust_subscription_id\x18\x01 \x01(\tR\x12custSubscriptionId\x12\"\n" +
	"\rsns_topic_arn\x18\x02 \x01(\tR\vsnsTopicArn\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12X\n" +
	"\x1asubscription_creation_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x18subscriptionCreationTime\x12\x1f\n" +
	"\vsource_type\x18\x05 \x01(\tR\n" +
	"sourceType\x12&\n" +
	"\x0fsource_ids_list\x18\x06 \x03(\tR\rsourceIdsList\x122\n" +
	"\x15event_categories_list\x18\a \x03(\tR\x13eventCategoriesList\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x122\n" +
	"\x15cust_subscription_arn\x18\t \x01(\tR\x13custSubscriptionArn\"\xf6\x02\n" +
	"\tParameter\x12%\n" +
	"\x0eparameter_name\x18\x01 \x01(\tR\rparameterName\x12'\n" +
	"\x0fparameter_value\x18\x02 \x01(\tR\x0eparameterValue\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"apply_type\x18\x05 \x01(\tR\tapplyType\x12\x1b\n" +
	"\tdata_type\x18\x06 \x01(\tR\bdataType\x12%\n" +
	"\x0eallowed_values\x18\a \x01(\tR\rallowedValues\x12#\n" +
	"\ris_modifiable\x18\b \x01(\bR\fisModifiable\x124\n" +
	"\x16minimum_engine_version\x18\t \x01(\tR\x14minimumEngineVersion\x12!\n" +
	"\fapply_method\x18\n" +
	" \x01(\tR\vapplyMethod\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"3\n" +
	"\aTagList\x12(\n" +
	"\x04tags\x18\x01 \x03(\v2\x14.storage.neptune.TagR\x04tags\"\xee\x02\n" +
	"\x11DBClusterEndpoint\x12C\n" +
	"\x1edb_cluster_endpoint_identifier\x18\x01 \x01(\tR\x1bdbClusterEndpointIdentifier\x122\n" +
	"\x15db_cluster_identifier\x18\x02 \x01(\tR\x13dbClusterIdentifier\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rendpoint_type\x18\x05 \x01(\tR\fendpointType\x12)\n" +
	"\x10excluded_members\x18\x06 \x03(\tR\x0fexcludedMembers\x12%\n" +
	"\x0estatic_members\x18\a \x03(\tR\rstaticMembers\x125\n" +
	"\x17db_cluster_endpoint_arn\x18\b \x01(\tR\x14dbClusterEndpointArn\"\xa1\x02\n" +
	"\n" +
	"QueryState\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\tR\tqueryType\x12!\n" +
	"\fquery_string\x18\x03 \x01(\tR\vqueryString\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"\xce\x03\n" +
	"\tLoaderJob\x12\x17\n" +
	"\aload_id\x18\x01 \x01(\tR\x06loadId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12;\n" +
	"\vsubmit_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"submitTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\rtotal_records\x18\a \x01(\x03R\ftotalRecords\x12!\n" +
	"\ftotal_errors\x18\b \x01(\x03R\vtotalErrors\x12%\n" +
	"\x0eoverall_status\x18\t \x01(\tR\roverallStatus\x12A\n" +
	"\adetails\x18\n" +
	" \x03(\v2'.storage.neptune.LoaderJob.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x04\n" +
	"\x0fGraphStatistics\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12!\n" +
	"\fauto_compute\x18\x02 \x01(\bR\vautoCompute\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12#\n" +
	"\rstatistics_id\x18\x05 \x01(\tR\fstatisticsId\x12\x1d\n" +
	"\n" +
	"node_count\x18\x06 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\a \x01(\x03R\tedgeCount\x12T\n" +
	"\flabel_counts\x18\b \x03(\v21.storage.neptune.GraphStatistics.LabelCountsEntryR\vlabelCounts\x12N\n" +
	"\n" +
	"rel_counts\x18\t \x03(\v2/.storage.neptune.GraphStatistics.RelCountsEntryR\trelCounts\x12'\n" +
	"\x0fpredicate_count\x18\n" +
	" \x01(\x03R\x0epredicateCount\x12'\n" +
	"\x0fsignature_count\x18\v \x01(\x03R\x0esignatureCount\x1a>\n" +
	"\x10LabelCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a<\n" +
	"\x0eRelCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B2Z0vorpalstacks/internal/pb/storage/storage_neptuneb\x06proto3"

var (
	file_storage_neptune_proto_rawDescOnce sync.Once
	file_storage_neptune_proto_rawDescData []byte
)

func file_storage_neptune_proto_rawDescGZIP() []byte {
	file_storage_neptune_proto_rawDescOnce.Do(func() {
		file_storage_neptune_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_neptune_proto_rawDesc), len(file_storage_neptune_proto_rawDesc)))
	})
	return file_storage_neptune_proto_rawDescData
}

var file_storage_neptune_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_storage_neptune_proto_goTypes = []any{
	(*ServerlessV2ScalingConfiguration)(nil), // 0: storage.neptune.ServerlessV2ScalingConfiguration
	(*DBClusterRole)(nil),                    // 1: storage.neptune.DBClusterRole
	(*DBCluster)(nil),                        // 2: storage.neptune.DBCluster
	(*DBInstance)(nil),                       // 3: storage.neptune.DBInstance
	(*DBClusterSnapshot)(nil),                // 4: storage.neptune.DBClusterSnapshot
	(*DBClusterParameterGroup)(nil),          // 5: storage.neptune.DBClusterParameterGroup
	(*DBParameterGroup)(nil),                 // 6: storage.neptune.DBParameterGroup
	(*Subnet)(nil),                           // 7: storage.neptune.Subnet
	(*DBSubnetGroup)(nil),                    // 8: storage.neptune.DBSubnetGroup
	(*GlobalClusterMember)(nil),              // 9: storage.neptune.GlobalClusterMember
	(*GlobalCluster)(nil),                    // 10: storage.neptune.GlobalCluster
	(*EventSubscription)(nil),                // 11: storage.neptune.EventSubscription
	(*Parameter)(nil),                        // 12: storage.neptune.Parameter
	(*Tag)(nil),                              // 13: storage.neptune.Tag
	(*TagList)(nil),                          // 14: storage.neptune.TagList
	(*DBClusterEndpoint)(nil),                // 15: storage.neptune.DBClusterEndpoint
	(*QueryState)(nil),                       // 16: storage.neptune.QueryState
	(*LoaderJob)(nil),                        // 17: storage.neptune.LoaderJob
	(*GraphStatistics)(nil),                  // 18: storage.neptune.GraphStatistics
	nil,                                      // 19: storage.neptune.LoaderJob.DetailsEntry
	nil,                                      // 20: storage.neptune.GraphStatistics.LabelCountsEntry
	nil,                                      // 21: storage.neptune.GraphStatistics.RelCountsEntry
	(*timestamppb.Timestamp)(nil),            // 22: google.protobuf.Timestamp
}
var file_storage_neptune_proto_depIdxs = []int32{
	22, // 0: storage.neptune.DBCluster.cluster_create_time:type_name -> google.protobuf.Timestamp
	22, // 1: storage.neptune.DBCluster.earliest_restorable_time:type_name -> google.protobuf.Timestamp
	22, // 2: storage.neptune.DBCluster.latest_restorable_time:type_name -> google.protobuf.Timestamp
	1,  // 3: storage.neptune.DBCluster.associated_roles:type_name -> storage.neptune.DBClusterRole
	0,  // 4: storage.neptune.DBCluster.serverless_v2_scaling_configuration:type_name -> storage.neptune.ServerlessV2ScalingConfiguration
	22, // 5: storage.neptune.DBInstance.instance_create_time:type_name -> google.protobuf.Timestamp
	22, // 6: storage.neptune.DBClusterSnapshot.snapshot_create_time:type_name -> google.protobuf.Timestamp
	22, // 7: storage.neptune.DBClusterSnapshot.cluster_create_time:type_name -> google.protobuf.Timestamp
	12, // 8: storage.neptune.DBClusterParameterGroup.parameters:type_name -> storage.neptune.Parameter
	12, // 9: storage.neptune.DBParameterGroup.parameters:type_name -> storage.neptune.Parameter
	7,  // 10: storage.neptune.DBSubnetGroup.subnets:type_name -> storage.neptune.Subnet
	9,  // 11: storage.neptune.GlobalCluster.global_cluster_members:type_name -> storage.neptune.GlobalClusterMember
	22, // 12: storage.neptune.EventSubscription.subscription_creation_time:type_name -> google.protobuf.Timestamp
	13, // 13: storage.neptune.TagList.tags:type_name -> storage.neptune.Tag
	22, // 14: storage.neptune.QueryState.start_time:type_name -> google.protobuf.Timestamp
	22, // 15: storage.neptune.QueryState.end_time:type_name -> google.protobuf.Timestamp
	22, // 16: storage.neptune.LoaderJob.submit_time:type_name -> google.protobuf.Timestamp
	22, // 17: storage.neptune.LoaderJob.end_time:type_name -> google.protobuf.Timestamp
	19, // 18: storage.neptune.LoaderJob.details:type_name -> storage.neptune.LoaderJob.DetailsEntry
	20, // 19: storage.neptune.GraphStatistics.label_counts:type_name -> storage.neptune.GraphStatistics.LabelCountsEntry
	21, // 20: storage.neptune.GraphStatistics.rel_counts:type_name -> storage.neptune.GraphStatistics.RelCountsEntry
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_storage_neptune_proto_init() }
func file_storage_neptune_proto_init() {
	if File_storage_neptune_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_neptune_proto_rawDesc), len(file_storage_neptune_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_neptune_proto_goTypes,
		DependencyIndexes: file_storage_neptune_proto_depIdxs,
		MessageInfos:      file_storage_neptune_proto_msgTypes,
	}.Build()
	File_storage_neptune_proto = out.File
	file_storage_neptune_proto_goTypes = nil
	file_storage_neptune_proto_depIdxs = nil
}
